#!/bin/bash
# Axiom receipts for every blueprint \lean{} declaration.
#
# Why this exists alongside checkdecls.sh: the three CI gates cannot see an
# `axiom`. `lake build` accepts it, `sorries.py` counts no `sorry` in it, and
# checkdecls only asserts the NAME resolves. A blueprint node can therefore sit
# under a `\leanok` proof block, pass every gate, and still rest on an
# unproved stub. Only `#print axioms` distinguishes proved from assumed.
#
# A declaration is CLOSED if its axiom dependencies are a subset of
# {propext, Classical.choice, Quot.sound} -- the standard classical trio that
# essentially all Mathlib rests on. Anything else is a repo-local assumption
# and is reported.
#
# Run blueprint-web.sh first: it writes blueprint/lean_decls.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
PKG="$(dirname "$HERE")"
DECLS="$HERE/lean_decls"
OUT="$HERE/axiomcheck.lean"

[ -f "$DECLS" ] || { echo "no $DECLS -- run ./blueprint-web.sh first" >&2; exit 1; }

{
  echo "-- GENERATED by blueprint/axiomcheck.sh. Do not edit."
  echo "import QuerySystem"
  echo ""
  while IFS= read -r d; do
    [ -z "$d" ] && continue
    echo "#print axioms _root_.$d"
  done < <(cat "$DECLS"; echo)
} > "$OUT"

cd "$PKG"
if ! command -v lake >/dev/null 2>&1 && [ -x "${HOME:-}/.elan/bin/lake" ]; then
  export PATH="${HOME:-}/.elan/bin:$PATH"
fi
command -v lake >/dev/null 2>&1 || {
  echo "AXIOMCHECK FAIL: lake is not on PATH -- the check did not run." >&2; exit 1; }

set +e
lake env lean "$OUT" > "$HERE/axiomcheck.log" 2>&1
rc=$?
set -e
[ "$rc" -eq 0 ] || {
  echo "AXIOMCHECK FAIL (lean exit $rc):" >&2; cat "$HERE/axiomcheck.log" >&2; exit 1; }

python3 - "$HERE/axiomcheck.log" <<'PY'
import re,sys
log=open(sys.argv[1]).read()
STD={'propext','Classical.choice','Quot.sound'}
dirty=[];n=0
for e in re.split(r"\n(?=')",log):
    e=" ".join(e.split())
    m=re.match(r"'([^']+)' (depends on axioms: \[(.*)\]|does not depend on any axioms)",e)
    if not m: continue
    n+=1
    ax=set() if m.group(3) is None else {a.strip() for a in m.group(3).split(',') if a.strip()}
    extra=sorted(ax-STD)
    if extra: dirty.append((m.group(1),extra))
print(f"axiom receipts for {n} blueprint declarations")
if not dirty:
    print(f"AXIOMCHECK OK -- all {n} rest on standard axioms only."); sys.exit(0)
print(f"{n-len(dirty)} closed; {len(dirty)} resting on repo-local axioms:")
for name,ex in dirty:
    print(f"  {name}")
    for a in ex: print(f"        depends on: {a}")
PY
