#!/bin/bash
# Axiom receipts for every blueprint \lean{} declaration, AND a census of every
# axiom declared anywhere in the library.
#
# Why this exists alongside checkdecls.sh: the three CI gates cannot see an
# `axiom`. `lake build` accepts it, `sorries.py` counts no `sorry` in it, and
# checkdecls only asserts the NAME resolves. A blueprint node can therefore sit
# under a `\leanok` proof block, pass every gate, and still rest on an
# unproved stub. Only `#print axioms` distinguishes proved from assumed.
#
# A declaration is CLOSED if its axiom dependencies are a subset of
# {propext, Classical.choice, Quot.sound} -- the standard classical trio that
# essentially all Mathlib rests on.
#
# Anything else is a repo-local assumption and FAILS, with one documented
# exception: axiom_allowlist.txt, which permits a named axiom only when it is
# keyed to a citation. That is the case CLAUDE.md allows -- a known result
# assumed rather than reformalized. Declarations resting on allowlisted axioms
# are reported separately as CITED, never silently folded in with the closed
# ones, so the count of things actually proved stays visible.
#
# THE CENSUS (second check, added 2026-08-30). Reachability from a blueprint
# node was the wrong scope. An axiom in a module the blueprint never mentions is
# invisible to the receipts above, and one such axiom -- KochenSpecker_witness
# in Commensurability.lean, a module with no blueprint nodes -- was FALSE:
# `False` was derivable from it, and all four gates stayed green for months. So
# the environment is now enumerated directly: every `axiom` declared in a
# `QuerySystem.*` module must be on the allowlist with a citation, whether or
# not anything blueprinted reaches it. The census is taken from the Lean
# environment, not by grepping sources -- a source scan missed
# `QuerySystem.L2.instOML`.
#
# Run blueprint-web.sh first: it writes blueprint/lean_decls.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
PKG="$(dirname "$HERE")"
DECLS="$HERE/lean_decls"
ALLOW="$HERE/axiom_allowlist.txt"
OUT="$HERE/axiomcheck.lean"

[ -f "$DECLS" ] || { echo "no $DECLS -- run ./blueprint-web.sh first" >&2; exit 1; }

# `python3` is the Microsoft Store stub on the Windows box, which exits nonzero
# and prints an install advert; pick whichever name actually runs.
PY=""
for c in python3 python py; do
  if command -v "$c" >/dev/null 2>&1 && "$c" -c "import sys" >/dev/null 2>&1; then
    PY="$c"; break
  fi
done
[ -n "$PY" ] || { echo "AXIOMCHECK FAIL: no working python -- the check did not run." >&2; exit 1; }

{
  echo "-- GENERATED by blueprint/axiomcheck.sh. Do not edit."
  echo "import QuerySystem"
  echo ""
  while IFS= read -r d; do
    [ -z "$d" ] && continue
    echo "#print axioms _root_.$d"
  done < <(cat "$DECLS"; echo)
  echo ""
  echo "-- Census: every axiom declared in a QuerySystem.* module. Read off the"
  echo "-- environment rather than the sources, so a declaration form the source"
  echo "-- scanner does not recognise cannot hide."
  echo "open Lean in"
  echo "run_cmd do"
  echo "  let env ← Lean.getEnv"
  echo "  let mut out : Array Name := #[]"
  echo "  for (m, md) in env.header.moduleNames.zip env.header.moduleData do"
  echo "    if (\`QuerySystem).isPrefixOf m then"
  echo "      for n in md.constNames do"
  echo "        if let some (.axiomInfo _) := env.find? n then"
  echo "          out := out.push n"
  echo "  for n in out do"
  echo "    Lean.logInfo m!\"PROJECT_AXIOM {n}\""
} > "$OUT"

cd "$PKG"
if ! command -v lake >/dev/null 2>&1 && [ -x "${HOME:-}/.elan/bin/lake" ]; then
  export PATH="${HOME:-}/.elan/bin:$PATH"
fi
command -v lake >/dev/null 2>&1 || {
  echo "AXIOMCHECK FAIL: lake is not on PATH -- the check did not run." >&2; exit 1; }

set +e
lake env lean "$OUT" > "$HERE/axiomcheck.log" 2>&1
rc=$?
set -e
[ "$rc" -eq 0 ] || {
  echo "AXIOMCHECK FAIL (lean exit $rc):" >&2; cat "$HERE/axiomcheck.log" >&2; exit 1; }

"$PY" - "$HERE/axiomcheck.log" "$ALLOW" <<'PY'
import io, re, sys
log = io.open(sys.argv[1], encoding="utf-8", errors="replace").read()
STD = {'propext', 'Classical.choice', 'Quot.sound'}

# --- the citation-keyed allowlist ------------------------------------------
# name <TAB or 2+ spaces> citation. The citation is mandatory: a bare name is a
# hard error, since an uncited axiom on the allowlist is the unproved stub this
# gate exists to catch.
allow, bad = {}, []
try:
    for ln, raw in enumerate(io.open(sys.argv[2], encoding="utf-8"), 1):
        s = raw.strip()
        if not s or s.startswith('#'):
            continue
        parts = re.split(r"\t|\s{2,}", s, maxsplit=1)
        if len(parts) < 2 or not parts[1].strip():
            bad.append((ln, s)); continue
        allow[parts[0].strip()] = parts[1].strip()
except FileNotFoundError:
    pass

if bad:
    print("AXIOMCHECK FAIL -- allowlist entries with no citation:", file=sys.stderr)
    for ln, s in bad:
        print("  line %d: %s" % (ln, s), file=sys.stderr)
    sys.exit(1)

# --- the census: every axiom DECLARED in the library ------------------------
declared = sorted(set(re.findall(r"PROJECT_AXIOM\s+(\S+)", log)))
if not declared:
    print("AXIOMCHECK FAIL -- the census produced no output; it did not run.",
          file=sys.stderr)
    sys.exit(1)
uncited = [a for a in declared if a not in allow]

# --- the receipts -----------------------------------------------------------
closed, cited, dirty, n, used = 0, [], [], 0, set()
for e in re.split(r"\n(?=')", log):
    e = " ".join(e.split())
    m = re.match(r"'([^']+)' (depends on axioms: \[(.*)\]|does not depend on any axioms)", e)
    if not m:
        continue
    n += 1
    ax = set() if m.group(3) is None else {a.strip() for a in m.group(3).split(',') if a.strip()}
    extra = sorted(ax - STD)
    if not extra:
        closed += 1
        continue
    unlisted = [a for a in extra if a not in allow]
    if unlisted:
        dirty.append((m.group(1), unlisted))
    else:
        cited.append((m.group(1), extra))
        used.update(extra)

print("axiom receipts for %d blueprint declarations; %d axioms declared in the library"
      % (n, len(declared)))

if dirty:
    print("%d closed; %d on cited axioms; %d resting on UNCITED repo-local axioms:"
          % (closed, len(cited), len(dirty)))
    for name, ex in dirty:
        print("  %s" % name)
        for a in ex:
            print("        depends on: %s" % a)
    print("", file=sys.stderr)
    print("AXIOMCHECK FAIL -- an unproved stub is holding up a blueprint node.", file=sys.stderr)
    print("Prove it, or add it to blueprint/axiom_allowlist.txt WITH the citation", file=sys.stderr)
    print("it is read from. Do not add one you have not checked against a source.", file=sys.stderr)
    sys.exit(1)

if uncited:
    print("")
    print("%d axiom%s declared in the library and NOT on the allowlist:"
          % (len(uncited), "" if len(uncited) == 1 else "s"))
    for a in uncited:
        print("        %s" % a)
    print("", file=sys.stderr)
    print("AXIOMCHECK FAIL -- an uncited axiom is sitting in the library.", file=sys.stderr)
    print("It does not have to hold up a blueprint node to be wrong: an axiom no", file=sys.stderr)
    print("node reaches is exactly the one nothing checks. Prove it, delete it, or", file=sys.stderr)
    print("add it to blueprint/axiom_allowlist.txt WITH the citation it is read", file=sys.stderr)
    print("from -- and check that it is TRUE as stated before you do.", file=sys.stderr)
    sys.exit(1)

# an allowlist entry earns its place by being reached from a node OR declared
stale = sorted(set(allow) - used - set(declared))
if cited:
    print("%d closed on standard axioms; %d resting on cited axioms:" % (closed, len(cited)))
    for name, ex in cited:
        print("  %s" % name)
        for a in ex:
            print("        cites: %s  [%s]" % (a, allow[a]))
else:
    print("AXIOMCHECK OK -- all %d rest on standard axioms only." % n)

if stale:
    print("")
    print("note: %d allowlist entr%s neither declared nor reached by a node --"
          % (len(stale), "y" if len(stale) == 1 else "ies"))
    print("      remove them unless a node is about to need them:")
    for a in stale:
        print("        %s" % a)

if cited:
    print("")
    print("AXIOMCHECK OK -- %d closed, %d cited, 0 uncited; %d library axioms all cited."
          % (closed, len(cited), len(declared)))
sys.exit(0)
PY
