#!/bin/bash
# Axiom receipts for every blueprint \lean{} declaration.
#
# Why this exists alongside checkdecls.sh: the three CI gates cannot see an
# `axiom`. `lake build` accepts it, `sorries.py` counts no `sorry` in it, and
# checkdecls only asserts the NAME resolves. A blueprint node can therefore sit
# under a `\leanok` proof block, pass every gate, and still rest on an
# unproved stub. Only `#print axioms` distinguishes proved from assumed.
#
# A declaration is CLOSED if its axiom dependencies are a subset of
# {propext, Classical.choice, Quot.sound} -- the standard classical trio that
# essentially all Mathlib rests on.
#
# Anything else is a repo-local assumption and FAILS, with one documented
# exception: axiom_allowlist.txt, which permits a named axiom only when it is
# keyed to a citation. That is the case CLAUDE.md allows -- a known result
# assumed rather than reformalized. Declarations resting on allowlisted axioms
# are reported separately as CITED, never silently folded in with the closed
# ones, so the count of things actually proved stays visible.
#
# Run blueprint-web.sh first: it writes blueprint/lean_decls.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
PKG="$(dirname "$HERE")"
DECLS="$HERE/lean_decls"
ALLOW="$HERE/axiom_allowlist.txt"
OUT="$HERE/axiomcheck.lean"

[ -f "$DECLS" ] || { echo "no $DECLS -- run ./blueprint-web.sh first" >&2; exit 1; }

# `python3` is the Microsoft Store stub on the Windows box, which exits nonzero
# and prints an install advert; pick whichever name actually runs.
PY=""
for c in python3 python py; do
  if command -v "$c" >/dev/null 2>&1 && "$c" -c "import sys" >/dev/null 2>&1; then
    PY="$c"; break
  fi
done
[ -n "$PY" ] || { echo "AXIOMCHECK FAIL: no working python -- the check did not run." >&2; exit 1; }

{
  echo "-- GENERATED by blueprint/axiomcheck.sh. Do not edit."
  echo "import QuerySystem"
  echo ""
  while IFS= read -r d; do
    [ -z "$d" ] && continue
    echo "#print axioms _root_.$d"
  done < <(cat "$DECLS"; echo)
} > "$OUT"

cd "$PKG"
if ! command -v lake >/dev/null 2>&1 && [ -x "${HOME:-}/.elan/bin/lake" ]; then
  export PATH="${HOME:-}/.elan/bin:$PATH"
fi
command -v lake >/dev/null 2>&1 || {
  echo "AXIOMCHECK FAIL: lake is not on PATH -- the check did not run." >&2; exit 1; }

set +e
lake env lean "$OUT" > "$HERE/axiomcheck.log" 2>&1
rc=$?
set -e
[ "$rc" -eq 0 ] || {
  echo "AXIOMCHECK FAIL (lean exit $rc):" >&2; cat "$HERE/axiomcheck.log" >&2; exit 1; }

"$PY" - "$HERE/axiomcheck.log" "$ALLOW" <<'PY'
import io, re, sys
log = io.open(sys.argv[1], encoding="utf-8", errors="replace").read()
STD = {'propext', 'Classical.choice', 'Quot.sound'}

# --- the citation-keyed allowlist ------------------------------------------
# name <TAB or 2+ spaces> citation. The citation is mandatory: a bare name is a
# hard error, since an uncited axiom on the allowlist is the unproved stub this
# gate exists to catch.
allow, bad = {}, []
try:
    for ln, raw in enumerate(io.open(sys.argv[2], encoding="utf-8"), 1):
        s = raw.strip()
        if not s or s.startswith('#'):
            continue
        parts = re.split(r"\t|\s{2,}", s, maxsplit=1)
        if len(parts) < 2 or not parts[1].strip():
            bad.append((ln, s)); continue
        allow[parts[0].strip()] = parts[1].strip()
except FileNotFoundError:
    pass

if bad:
    print("AXIOMCHECK FAIL -- allowlist entries with no citation:", file=sys.stderr)
    for ln, s in bad:
        print("  line %d: %s" % (ln, s), file=sys.stderr)
    sys.exit(1)

# --- the receipts -----------------------------------------------------------
closed, cited, dirty, n, used = 0, [], [], 0, set()
for e in re.split(r"\n(?=')", log):
    e = " ".join(e.split())
    m = re.match(r"'([^']+)' (depends on axioms: \[(.*)\]|does not depend on any axioms)", e)
    if not m:
        continue
    n += 1
    ax = set() if m.group(3) is None else {a.strip() for a in m.group(3).split(',') if a.strip()}
    extra = sorted(ax - STD)
    if not extra:
        closed += 1
        continue
    unlisted = [a for a in extra if a not in allow]
    if unlisted:
        dirty.append((m.group(1), unlisted))
    else:
        cited.append((m.group(1), extra))
        used.update(extra)

print("axiom receipts for %d blueprint declarations" % n)

if dirty:
    print("%d closed; %d on cited axioms; %d resting on UNCITED repo-local axioms:"
          % (closed, len(cited), len(dirty)))
    for name, ex in dirty:
        print("  %s" % name)
        for a in ex:
            print("        depends on: %s" % a)
    print("", file=sys.stderr)
    print("AXIOMCHECK FAIL -- an unproved stub is holding up a blueprint node.", file=sys.stderr)
    print("Prove it, or add it to blueprint/axiom_allowlist.txt WITH the citation", file=sys.stderr)
    print("it is read from. Do not add one you have not checked against a source.", file=sys.stderr)
    sys.exit(1)

stale = sorted(set(allow) - used)
if cited:
    print("%d closed on standard axioms; %d resting on cited axioms:" % (closed, len(cited)))
    for name, ex in cited:
        print("  %s" % name)
        for a in ex:
            print("        cites: %s  [%s]" % (a, allow[a]))
else:
    print("AXIOMCHECK OK -- all %d rest on standard axioms only." % n)

if stale:
    print("")
    print("note: %d allowlist entr%s used by no blueprint declaration --"
          % (len(stale), "y" if len(stale) == 1 else "ies"))
    print("      remove them unless a node is about to need them:")
    for a in stale:
        print("        %s" % a)

if cited:
    print("")
    print("AXIOMCHECK OK -- %d closed, %d cited, 0 uncited." % (closed, len(cited)))
sys.exit(0)
PY
