#!/bin/bash
# Verify every \lean{...} name in the blueprint names a real declaration.
#
# `leanblueprint checkdecls` would do this via a `lake exe checkdecls`
# dependency. We do not add that dependency: it would touch lake-manifest.json
# and risk the v4.29.0 toolchain pin for a check we can run directly. Instead
# generate a Lean file that `#check`s each name and elaborate it -- an unknown
# identifier is an error, which is exactly the guarantee wanted.
#
# Run blueprint-web.sh first: it writes blueprint/lean_decls.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
PKG="$(dirname "$HERE")"
DECLS="$HERE/lean_decls"
OUT="$HERE/checkdecls.lean"

if [ ! -f "$DECLS" ]; then
  echo "no $DECLS -- run ./blueprint-web.sh first" >&2
  exit 1
fi

{
  echo "-- GENERATED by blueprint/checkdecls.sh. Do not edit."
  # The root module is an index over every submodule, so this one import
  # brings the whole library into scope. (Before 2026-08-21 the root was a
  # duplicate source file and importing it alongside QuerySystem.QuerySystem
  # was a hard error; see the header of QuerySystem.lean.)
  echo "import QuerySystem"
  echo ""
  while IFS= read -r d; do
    [ -z "$d" ] && continue
    echo "#check @_root_.$d"
  done < <(cat "$DECLS"; echo)
} > "$OUT"

n=$(grep -c "^#check" "$OUT")
echo "checking $n blueprint declarations against the Lean environment..."

cd "$PKG"

# lean-action puts elan on PATH for its own step; do not assume it persists.
if ! command -v lake >/dev/null 2>&1 && [ -x "${HOME:-}/.elan/bin/lake" ]; then
  export PATH="${HOME:-}/.elan/bin:$PATH"
fi
if ! command -v lake >/dev/null 2>&1; then
  echo "CHECKDECLS FAIL: lake is not on PATH -- the check did not run." >&2
  exit 1
fi

# Capture rc explicitly. The earlier version piped lean through grep inside an
# `if`, which meant a lean that never ran (missing lake, bad file) produced an
# empty log, matched no "error", and reported OK. A check that passes when it
# did not run is worse than no check -- it is the exact failure this whole
# gate exists to prevent.
set +e
lake env lean "$OUT" > "$HERE/checkdecls.log" 2>&1
rc=$?
set -e

if [ "$rc" -ne 0 ] || grep -qiE "error" "$HERE/checkdecls.log"; then
  echo "CHECKDECLS FAIL (lean exit $rc) -- a blueprint \lean{} name does not resolve:" >&2
  cat "$HERE/checkdecls.log" >&2
  exit 1
fi
echo "CHECKDECLS OK -- all $n names resolve."
