#!/bin/bash
# Verify every \lean{...} name in the blueprint names a real declaration.
#
# `leanblueprint checkdecls` would do this via a `lake exe checkdecls`
# dependency. We do not add that dependency: it would touch lake-manifest.json
# and risk the v4.29.0 toolchain pin for a check we can run directly. Instead
# generate a Lean file that `#check`s each name and elaborate it -- an unknown
# identifier is an error, which is exactly the guarantee wanted.
#
# Run blueprint-web.sh first: it writes blueprint/lean_decls.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
PKG="$(dirname "$HERE")"
DECLS="$HERE/lean_decls"
OUT="$HERE/checkdecls.lean"

if [ ! -f "$DECLS" ]; then
  echo "no $DECLS -- run ./blueprint-web.sh first" >&2
  exit 1
fi

{
  echo "-- GENERATED by blueprint/checkdecls.sh. Do not edit."
  # The root module is an index over every submodule, so this one import
  # brings the whole library into scope. (Before 2026-08-21 the root was a
  # duplicate source file and importing it alongside QuerySystem.QuerySystem
  # was a hard error; see the header of QuerySystem.lean.)
  echo "import QuerySystem"
  echo ""
  while IFS= read -r d; do
    [ -z "$d" ] && continue
    echo "#check @_root_.$d"
  done < <(cat "$DECLS"; echo)
} > "$OUT"

n=$(grep -c '^#check' "$OUT")
echo "checking $n blueprint declarations against the Lean environment..."

cd "$PKG"
if lake env lean "$OUT" 2>&1 | grep -vE "^$" > "$HERE/checkdecls.log"; then
  if grep -qiE "error" "$HERE/checkdecls.log"; then
    echo "CHECKDECLS FAIL -- a blueprint \lean{} name does not exist:" >&2
    grep -iE "error" -A2 "$HERE/checkdecls.log" >&2
    exit 1
  fi
fi
if grep -qiE "error" "$HERE/checkdecls.log"; then
  echo "CHECKDECLS FAIL -- a blueprint \lean{} name does not exist:" >&2
  grep -iE "error" -A2 "$HERE/checkdecls.log" >&2
  exit 1
fi
echo "CHECKDECLS OK -- all $n names resolve."
