/-
# Glued delay windows give a non-Boolean carrier

Falsifier for the hypothesis in
`notes/open_questions/delay_embedding/collision_vs_generation.md` §"Bridge hypothesis":
does gluing real-valued observation windows along shared coordinates give a
non-Boolean σ-complete concrete carrier (a `DynkinSystem` of Borel sets), or does
it collapse to a Boolean one?

Setup. Paths are `x : ι → α`. A window is a set of coordinates `w`; its events are
the sets measurable for the σ-algebra pulled back along the restriction to `w`.
The glued carrier is the Dynkin system generated by the events of all windows.

Result (`glued_not_interClosed`). If two coordinates `i ≠ j` each lie in some window
but in no common window, and `α` has a measurable set that is neither empty nor
everything, the glued carrier is NOT intersection-closed, so it is non-Boolean. The
hypothesis covers every chain of length ≥ 2 and every ring of length ≥ 4. It does
not cover the triangle, where every pair of coordinates shares a window.

Method. The witness `{x i ∈ U} ∩ {x j ∈ U}` violates a four-point rectangle
identity: membership counts at `x`, `x[i↦c]`, `x[j↦c]` and `x[i↦c, j↦c]`. Every
window event satisfies the identity. The identity is preserved by complements and
countable disjoint unions, so every set in the carrier satisfies it.

`glued_le_borel`: the carrier sits inside the product σ-algebra. With `α = ℝ` that
is the Borel σ-algebra of a Polish space, which is the setting of Derr–Williamson
D.6. That does not certify the paper's `PolishRepresentable`, which is an opaque
axiom in `SigmaEssentialOpenCore`.
-/
import Mathlib
import QuerySystem.Admissibility

open Set MeasurableSpace Function
open scoped ENNReal

namespace WindowGluing

variable {ι α : Type*} [MeasurableSpace α]

/-- Events of window `w`: pulled back along restriction to the coordinates in `w`. -/
abbrev windowSigma (w : Set ι) : MeasurableSpace (ι → α) :=
  MeasurableSpace.comap (fun x (k : w) => x k) MeasurableSpace.pi

/-- The union of the window event families. -/
def gens (W : Set (Set ι)) : Set (Set (ι → α)) :=
  {E | ∃ w ∈ W, @MeasurableSet _ (windowSigma w) E}

/-- The glued carrier: the Dynkin system generated by all window events. -/
def glued (W : Set (Set ι)) : DynkinSystem (ι → α) :=
  DynkinSystem.generate (gens W)

/-- A window event only sees the coordinates in its window. -/
lemma window_event_local {w : Set ι} {E : Set (ι → α)}
    (hE : @MeasurableSet _ (windowSigma w) E) {y z : ι → α} (h : ∀ k ∈ w, y k = z k) :
    y ∈ E ↔ z ∈ E := by
  obtain ⟨s, -, rfl⟩ := hE
  have : (fun (k : w) => y k) = (fun (k : w) => z k) := funext fun k => h k k.2
  simp only [mem_preimage, this]

/-- Membership count at a point, valued in `ℕ`. -/
noncomputable def cnt (E : Set (ι → α)) (p : ι → α) : ℕ := by
  classical exact if p ∈ E then 1 else 0

omit [MeasurableSpace α] in
lemma cast_cnt_iUnion {f : ℕ → Set (ι → α)} (hd : Pairwise (Disjoint on f))
    (p : ι → α) : ((cnt (⋃ n, f n) p : ℕ) : ℝ≥0∞) = ∑' n, ((cnt (f n) p : ℕ) : ℝ≥0∞) := by
  classical
  by_cases hp : p ∈ ⋃ n, f n
  · obtain ⟨k, hk⟩ := mem_iUnion.mp hp
    rw [tsum_eq_single k]
    · simp [cnt, hp, hk]
    · intro n hn
      have : p ∉ f n := fun h' => Set.disjoint_left.mp (hd hn) h' hk
      simp [cnt, this]
  · have : ∀ n, p ∉ f n := fun n h' => hp (mem_iUnion.mpr ⟨n, h'⟩)
    simp [cnt, hp, this]

variable [DecidableEq ι]

/-- The rectangle identity at coordinates `i, j` with reset value `c`. -/
def Rect (i j : ι) (c : α) (E : Set (ι → α)) : Prop :=
  ∀ x : ι → α, cnt E x + cnt E (update (update x i c) j c) =
    cnt E (update x i c) + cnt E (update x j c)

lemma rect_of_gens {W : Set (Set ι)} {i j : ι} (hij : i ≠ j)
    (hsep : ∀ w ∈ W, ¬ (i ∈ w ∧ j ∈ w)) (c : α) {E : Set (ι → α)}
    (hE : E ∈ gens W) : Rect i j c E := by
  classical
  obtain ⟨w, hw, hE⟩ := hE
  intro x
  by_cases hi : i ∈ w
  · have hj : j ∉ w := fun hj => hsep w hw ⟨hi, hj⟩
    have h1 := window_event_local hE (y := update x j c) (z := x)
      (fun k hk => update_of_ne (by rintro rfl; exact hj hk) _ _)
    have h2 := window_event_local hE (y := update (update x i c) j c) (z := update x i c)
      (fun k hk => update_of_ne (by rintro rfl; exact hj hk) _ _)
    simp only [cnt, h1, h2]; omega
  · have h1 := window_event_local hE (y := update x i c) (z := x)
      (fun k hk => update_of_ne (by rintro rfl; exact hi hk) _ _)
    have h2 := window_event_local hE (y := update (update x i c) j c) (z := update x j c)
      (fun k hk => by
        have hki : k ≠ i := by rintro rfl; exact hi hk
        by_cases hkj : k = j
        · subst hkj; simp
        · simp [update_of_ne hkj, update_of_ne hki])
    simp only [cnt, h1, h2]

/-- Every set in the glued carrier satisfies the rectangle identity. -/
lemma rect_of_glued {W : Set (Set ι)} {i j : ι} (hij : i ≠ j)
    (hsep : ∀ w ∈ W, ¬ (i ∈ w ∧ j ∈ w)) (c : α) {E : Set (ι → α)}
    (hE : (glued W).Has E) : Rect i j c E := by
  classical
  induction hE with
  | basic t ht => exact rect_of_gens hij hsep c ht
  | empty => intro x; simp [cnt]
  | compl _ ih =>
    intro x
    have := ih x
    simp only [cnt, mem_compl_iff] at this ⊢
    split_ifs at this ⊢ <;> omega
  | iUnion hd _ ih =>
    intro x
    apply Nat.cast_injective (R := ℝ≥0∞)
    push_cast
    rw [cast_cnt_iUnion hd, cast_cnt_iUnion hd, cast_cnt_iUnion hd, cast_cnt_iUnion hd,
      ← ENNReal.tsum_add, ← ENNReal.tsum_add]
    congr 1; ext n
    exact_mod_cast ih n x

/-- **Glued windows are non-Boolean.** Two coordinates that each lie in a window but
share none, plus a measurable set that is neither empty nor everything, make the
glued carrier fail intersection-closure. -/
theorem glued_not_interClosed {W : Set (Set ι)} {i j : ι} (hij : i ≠ j)
    (hi : ∃ w ∈ W, i ∈ w) (hj : ∃ w ∈ W, j ∈ w)
    (hsep : ∀ w ∈ W, ¬ (i ∈ w ∧ j ∈ w))
    {U : Set α} (hU : MeasurableSet U) {u₀ u₁ : α} (h₀ : u₀ ∈ U) (h₁ : u₁ ∉ U) :
    ¬ SigmaEssential.InterClosed (glued (α := α) W) := by
  classical
  intro hclosed
  have mem_coord : ∀ {k : ι}, (∃ w ∈ W, k ∈ w) →
      (glued (α := α) W).Has {x | x k ∈ U} := by
    rintro k ⟨w, hw, hk⟩
    refine DynkinSystem.GenerateHas.basic _ ⟨w, hw, ?_⟩
    exact ⟨{y | y ⟨k, hk⟩ ∈ U}, measurable_pi_apply _ hU, rfl⟩
  have hR := rect_of_glued (α := α) hij hsep u₁ (hclosed (mem_coord hi) (mem_coord hj))
    (fun _ => u₀)
  simp [cnt, update_of_ne hij, update_of_ne hij.symm, h₀, h₁] at hR

omit [DecidableEq ι] in
/-- The glued carrier sits inside the product σ-algebra on paths. -/
theorem glued_le_borel (W : Set (Set ι)) {E : Set (ι → α)} (hE : (glued (α := α) W).Has E) :
    @MeasurableSet _ MeasurableSpace.pi E := by
  induction hE with
  | basic t ht =>
    obtain ⟨w, -, s, hs, rfl⟩ := ht
    exact (show Measurable (fun (x : ι → α) (k : w) => x k) from
      measurable_pi_lambda _ fun k => measurable_pi_apply _) hs
  | empty => exact MeasurableSet.empty
  | compl _ ih => exact ih.compl
  | iUnion _ _ ih => exact MeasurableSet.iUnion ih

/-- The 4-ring of delay windows `{0,1},{1,2},{2,3},{3,0}` on real paths is a
non-Boolean carrier (coordinates 0 and 2 share no window). -/
theorem ring4_real_not_interClosed :
    ¬ SigmaEssential.InterClosed
      (glued (ι := Fin 4) (α := ℝ) {{0, 1}, {1, 2}, {2, 3}, {3, 0}}) := by
  refine glued_not_interClosed (i := 0) (j := 2) (by decide)
    ⟨{0, 1}, by simp, by simp⟩ ⟨{1, 2}, by simp, by simp⟩ ?_
    (measurableSet_Ici (a := (0 : ℝ))) (u₀ := 0) (u₁ := -1) (by simp) (by norm_num)
  intro w hw
  simp only [mem_insert_iff, mem_singleton_iff] at hw
  rcases hw with rfl | rfl | rfl | rfl <;> decide

/-! ## The admissibility tests, in the repo's own notions

Blocks are `SigmaEssential.Blocks.IsMaxBlock` (maximal pairwise-compatible
families, `Compat d A B := d.Has (A ∩ B)`). -/

section Admissibility

open SigmaEssential SigmaEssential.Blocks

omit [DecidableEq ι] in
/-- **The windows generate the full σ-algebra.** If every coordinate lies in a
window, the σ-algebra generated by the glued carrier is the product σ-algebra. -/
theorem generateFrom_glued {W : Set (Set ι)} (hcov : ∀ i, ∃ w ∈ W, i ∈ w) :
    MeasurableSpace.generateFrom {E | (glued (α := α) W).Has E} = MeasurableSpace.pi := by
  apply le_antisymm
  · exact MeasurableSpace.generateFrom_le fun E hE => glued_le_borel W hE
  · refine iSup_le fun i => ?_
    rintro _ ⟨U, hU, rfl⟩
    obtain ⟨w, hw, hi⟩ := hcov i
    refine MeasurableSpace.measurableSet_generateFrom
      (DynkinSystem.GenerateHas.basic _ ⟨w, hw, ?_⟩)
    exact ⟨{y | y ⟨i, hi⟩ ∈ U}, measurable_pi_apply _ hU, rfl⟩

/-- **Not a horizontal σ-sum.** Under the separation hypothesis there are two
distinct maximal blocks sharing a nontrivial element `{x m ∈ U}`, where `m` is a
coordinate sharing a window with `i` and another with `j`. -/
theorem glued_blocks_overlap {W : Set (Set ι)} {i j m : ι} (hij : i ≠ j)
    (hsep : ∀ w ∈ W, ¬ (i ∈ w ∧ j ∈ w))
    (him : ∃ w ∈ W, i ∈ w ∧ m ∈ w) (hjm : ∃ w ∈ W, j ∈ w ∧ m ∈ w)
    {U : Set α} (hU : MeasurableSet U) {u₀ u₁ : α} (h₀ : u₀ ∈ U) (h₁ : u₁ ∉ U) :
    ∃ M₁ M₂, IsMaxBlock (glued (α := α) W) M₁ ∧ IsMaxBlock (glued (α := α) W) M₂ ∧
      M₁ ≠ M₂ ∧ {x : ι → α | x m ∈ U} ∈ M₁ ∩ M₂ ∧
      {x : ι → α | x m ∈ U} ≠ ∅ ∧ {x : ι → α | x m ∈ U} ≠ univ := by
  classical
  set D := glued (α := α) W
  -- window events: anything measurable in one window is in `D`
  have winmem : ∀ {w}, w ∈ W → ∀ {E : Set (ι → α)},
      @MeasurableSet _ (windowSigma w) E → D.Has E :=
    fun hw _ hE => DynkinSystem.GenerateHas.basic _ ⟨_, hw, hE⟩
  have coord : ∀ {w} {k : ι} (hk : k ∈ w), @MeasurableSet _ (windowSigma w) {x : ι → α | x k ∈ U} :=
    fun hk => ⟨{y | y ⟨_, hk⟩ ∈ U}, measurable_pi_apply _ hU, rfl⟩
  have pairFam : ∀ {k l : ι}, (∃ w ∈ W, k ∈ w ∧ l ∈ w) →
      IsCompatFamily D {{x | x k ∈ U}, {x | x l ∈ U}} := by
    rintro k l ⟨w, hw, hk, hl⟩
    have hmeas : ∀ A ∈ ({{x | x k ∈ U}, {x | x l ∈ U}} : Set (Set (ι → α))),
        @MeasurableSet _ (windowSigma w) A := by
      intro A hA; rcases hA with rfl | rfl
      · exact coord hk
      · exact coord hl
    refine ⟨fun A hA => winmem hw (hmeas A hA), fun A hA B hB _ => ?_⟩
    exact winmem hw ((hmeas A hA).inter (hmeas B hB))
  obtain ⟨M₁, hF₁, hM₁⟩ := exists_isMaxBlock_superset (pairFam him)
  obtain ⟨M₂, hF₂, hM₂⟩ := exists_isMaxBlock_superset (pairFam hjm)
  have hA : {x : ι → α | x i ∈ U} ∈ M₁ := hF₁ (by simp)
  have hB : {x : ι → α | x j ∈ U} ∈ M₂ := hF₂ (by simp)
  have hm₁ : {x : ι → α | x m ∈ U} ∈ M₁ := hF₁ (by simp)
  have hm₂ : {x : ι → α | x m ∈ U} ∈ M₂ := hF₂ (by simp)
  refine ⟨M₁, M₂, hM₁, hM₂, ?_, ⟨hm₁, hm₂⟩, ?_, ?_⟩
  · rintro rfl
    -- then {x i ∈ U} and {x j ∈ U} are compatible: their meet is in `D`
    have hc := hM₁.compat_mem hA hB
    have hR := rect_of_glued (α := α) hij hsep u₁ hc (fun _ => u₀)
    simp [cnt, update_of_ne hij, update_of_ne hij.symm, h₀, h₁] at hR
  · exact Set.nonempty_iff_ne_empty.mp ⟨fun _ => u₀, h₀⟩
  · intro h
    have : (fun _ => u₁ : ι → α) ∈ {x : ι → α | x m ∈ U} := h ▸ Set.mem_univ _
    exact h₁ this

end Admissibility

/-- **Non-segregation (real windows).** A finitely additive two-valued state that
escapes to infinity in coordinate `i` has an empty kernel on any maximal block
containing the sets `{x i > n}`. This conjunct of `Admissible` is cheap: every
Borel σ-algebra of `ℝ` already satisfies it, so it does not discriminate. -/
theorem glued_nonSegregated {ι : Type*} {W : Set (Set ι)} {i : ι} (hi : ∃ w ∈ W, i ∈ w) :
    SigmaEssential.Admissibility.NonSegregated (glued (α := ℝ) W) := by
  classical
  open SigmaEssential SigmaEssential.Blocks in
  intro hseg
  set D := glued (α := ℝ) W
  obtain ⟨w, hw, hiw⟩ := hi
  let S : ℕ → Set (ι → ℝ) := fun n => {x | (n : ℝ) < x i}
  have hSmeas : ∀ n, @MeasurableSet _ (windowSigma w) (S n) := fun n =>
    ⟨{y | (n : ℝ) < y ⟨i, hiw⟩}, measurable_pi_apply _ measurableSet_Ioi, rfl⟩
  have hSD : ∀ n, D.Has (S n) := fun n => DynkinSystem.GenerateHas.basic _ ⟨w, hw, hSmeas n⟩
  -- the filter of sets eventually containing a tail `S n`
  let F : Filter (ι → ℝ) := Filter.comap (fun x => x i) Filter.atTop
  haveI : F.NeBot := Filter.comap_neBot fun t ht => by
    obtain ⟨a, ha⟩ := Filter.mem_atTop_sets.mp ht
    exact ⟨fun _ => a, ha a le_rfl⟩
  let 𝒰 : Ultrafilter (ι → ℝ) := Ultrafilter.of F
  have hSU : ∀ n, S n ∈ 𝒰 := fun n => Ultrafilter.of_le F
    (Filter.preimage_mem_comap (Filter.Ioi_mem_atTop (n : ℝ)))
  let μ : FinAddState D :=
    { Val := fun A => A ∈ 𝒰
      decVal := Classical.decPred _
      val_univ := Filter.univ_mem
      not_val_empty := Ultrafilter.empty_notMem
      val_compl := fun _ => Ultrafilter.compl_mem_iff_notMem
      val_union := fun _ _ _ => Ultrafilter.union_mem_iff }
  have hfam : IsCompatFamily D (Set.range S) := by
    refine ⟨by rintro _ ⟨n, rfl⟩; exact hSD n, ?_⟩
    rintro _ ⟨n, rfl⟩ _ ⟨k, rfl⟩ _
    exact DynkinSystem.GenerateHas.basic _ ⟨w, hw, (hSmeas n).inter (hSmeas k)⟩
  obtain ⟨M, hSM, hM⟩ := exists_isMaxBlock_superset hfam
  obtain ⟨x, hx⟩ := hseg μ M hM
  have : ∀ n, x ∈ S n := fun n => hx _ ⟨hSM ⟨n, rfl⟩, hSU n⟩
  obtain ⟨n, hn⟩ := exists_nat_gt (x i)
  exact absurd (this n) (not_lt.mpr hn.le)

/-! ## Essential irreducibility: the centre is trivial

A central `E` meets every carrier element inside the carrier. Intersecting with the
window event `{y | y i = a}` and applying the rectangle identity at a separated
pair `(i, j)` shows `E` does not depend on coordinate `j`. On a ring of length
≥ 4 every coordinate has such a partner, so `E` is `∅` or `univ`. -/

section Centre

open SigmaEssential.Admissibility

variable [MeasurableSingletonClass α]

/-- A central element does not depend on any coordinate `j` that has a separated
partner `i`. -/
lemma centre_indep {W : Set (Set ι)} {i j : ι} (hij : i ≠ j)
    (hi : ∃ w ∈ W, i ∈ w) (hsep : ∀ w ∈ W, ¬ (i ∈ w ∧ j ∈ w))
    (hα : ∀ a : α, ∃ b, b ≠ a) {E : Set (ι → α)} (hE : Centre (glued (α := α) W) E)
    (x : ι → α) (c : α) : update x j c ∈ E ↔ x ∈ E := by
  classical
  obtain ⟨w, hw, hiw⟩ := hi
  -- the step for a reset value different from `x i`
  have step : ∀ (y : ι → α) (c' : α), c' ≠ y i → (update y j c' ∈ E ↔ y ∈ E) := by
    intro y c' hc'
    have hA : (glued (α := α) W).Has {z | z i = y i} :=
      DynkinSystem.GenerateHas.basic _
        ⟨w, hw, {v | v ⟨i, hiw⟩ = y i}, measurable_pi_apply _ (measurableSet_singleton _), rfl⟩
    have hR := rect_of_glued (α := α) hij hsep c' (hE.2 _ hA) y
    simp only [cnt, mem_inter_iff, mem_setOf_eq, update_self,
      update_of_ne hij, and_true] at hR
    split_ifs at hR with h1 h2 h2 <;> simp_all
  by_cases hc : c = x i
  · obtain ⟨c', hc'⟩ := hα (x i)
    have h1 := step x c' hc'
    have h2 := step (update x j c) c' (by rw [update_of_ne hij]; exact hc')
    rw [update_idem] at h2
    exact h2.symm.trans h1
  · exact step x c hc

/-- **The glued real 4-ring is essentially irreducible**: its centre is `{∅, univ}`. -/
theorem ring4_real_essentiallyIrreducible :
    EssentiallyIrreducible
      (glued (ι := Fin 4) (α := ℝ) {{0, 1}, {1, 2}, {2, 3}, {3, 0}}) := by
  classical
  intro E hE
  set W : Set (Set (Fin 4)) := {{0, 1}, {1, 2}, {2, 3}, {3, 0}}
  have hα : ∀ a : ℝ, ∃ b, b ≠ a := fun a => ⟨a + 1, by linarith⟩
  have sep : ∀ i j : Fin 4, (i = 0 ∧ j = 2 ∨ i = 2 ∧ j = 0 ∨ i = 1 ∧ j = 3 ∨ i = 3 ∧ j = 1) →
      ∀ w ∈ W, ¬ (i ∈ w ∧ j ∈ w) := by
    intro i j hij w hw
    simp only [W, mem_insert_iff, mem_singleton_iff] at hw
    rcases hij with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;>
      rcases hw with rfl | rfl | rfl | rfl <;> decide
  have inW : ∀ i : Fin 4, ∃ w ∈ W, i ∈ w := by
    intro i; fin_cases i
    · exact ⟨{0, 1}, by simp [W], by simp⟩
    · exact ⟨{0, 1}, by simp [W], by simp⟩
    · exact ⟨{1, 2}, by simp [W], by simp⟩
    · exact ⟨{2, 3}, by simp [W], by simp⟩
  -- every coordinate is invariant
  have inv : ∀ (j : Fin 4) (x : Fin 4 → ℝ) (c : ℝ), update x j c ∈ E ↔ x ∈ E := by
    intro j x c
    fin_cases j
    · exact centre_indep (i := 2) (by decide) (inW 2) (sep 2 0 (by simp)) hα hE x c
    · exact centre_indep (i := 3) (by decide) (inW 3) (sep 3 1 (by simp)) hα hE x c
    · exact centre_indep (i := 0) (by decide) (inW 0) (sep 0 2 (by simp)) hα hE x c
    · exact centre_indep (i := 1) (by decide) (inW 1) (sep 1 3 (by simp)) hα hE x c
  have all : ∀ x y : Fin 4 → ℝ, x ∈ E ↔ y ∈ E := by
    intro x y
    have hy : y = update (update (update (update x 0 (y 0)) 1 (y 1)) 2 (y 2)) 3 (y 3) := by
      funext k; fin_cases k <;> simp [update]
    rw [hy, inv, inv, inv, inv]
  by_cases hne : E.Nonempty
  · right
    obtain ⟨x, hx⟩ := hne
    have : Eᶜ = ∅ := Set.eq_empty_iff_forall_notMem.mpr fun y hy => hy ((all x y).mp hx)
    simp [this]
  · left
    simp [Set.not_nonempty_iff_eq_empty.mp hne]

/-- **The glued real 4-ring is an admissible carrier** (`Admissible`, both
conjuncts). Together with `generateFrom_glued` it is a Borel, Polish-built test
case for Q6.6 (`DWPolishCut`). -/
theorem ring4_real_admissible :
    Admissible (glued (ι := Fin 4) (α := ℝ) {{0, 1}, {1, 2}, {2, 3}, {3, 0}}) :=
  ⟨ring4_real_essentiallyIrreducible, glued_nonSegregated (i := (0 : Fin 4)) ⟨{0, 1}, by simp, by simp⟩⟩

end Centre

end WindowGluing

#print axioms WindowGluing.glued_not_interClosed
#print axioms WindowGluing.glued_le_borel
#print axioms WindowGluing.ring4_real_not_interClosed
#print axioms WindowGluing.generateFrom_glued
#print axioms WindowGluing.glued_blocks_overlap
#print axioms WindowGluing.glued_nonSegregated
#print axioms WindowGluing.ring4_real_essentiallyIrreducible
#print axioms WindowGluing.ring4_real_admissible
