#!/usr/bin/env python3
"""Merge individual paper bibs into a single combined references.bib.

Run from the papers/combined/ directory:
    python3 merge_bibs.py

Deduplicates by key (first occurrence wins, matching Paper I → II → III order).
"""

import re
import sys
from pathlib import Path

SOURCES = [
    Path("../paper_i/references.bib"),
    Path("../paper_ii/references.bib"),
    Path("../paper_iii/references.bib"),
]

OUT = Path("references.bib")

ENTRY_RE = re.compile(
    r"(@\w+\s*\{[^@]*)",
    re.DOTALL,
)

KEY_RE = re.compile(r"@\w+\s*\{\s*(\w+)")


def parse_entries(text):
    """Return list of (key, raw_entry_text) from a bib file."""
    entries = []
    for m in ENTRY_RE.finditer(text):
        raw = m.group(1).strip()
        km = KEY_RE.match(raw)
        if km:
            entries.append((km.group(1), raw))
    return entries


seen_keys = {}
ordered = []

for src in SOURCES:
    if not src.exists():
        print(f"WARNING: {src} not found, skipping.", file=sys.stderr)
        continue
    text = src.read_text()
    for key, raw in parse_entries(text):
        if key not in seen_keys:
            seen_keys[key] = src.name
            ordered.append((key, raw))

header = """\
% Combined bibliography — AUTO-GENERATED by merge_bibs.py
% Do NOT edit by hand. Edit the individual paper bibs and re-run:
%   python3 papers/combined/merge_bibs.py
%
% Sources (in order; first occurrence of a key wins):
"""
for src in SOURCES:
    header += f"%   {src}\n"

blocks = [header]
for key, raw in ordered:
    blocks.append(raw)

OUT.write_text("\n\n".join(blocks) + "\n")
print(f"Written {len(ordered)} entries to {OUT}")
