"""Refutation record, re-verified (2026-07-06): the pentagon half-model is
immune to the ENTIRE elementary Bonferroni-chain family, yet unrealisable —
so Family I (chains) is NOT complete; the pentagon's certificate is a
stable-set/coverage bound (Family II), valid modulo the model's zero-set
rather than pointwise on Omega.

Setup (concrete): Omega = {0,1}^5; context j (j mod 5) = the partition of
Omega by (x_j, x_{j+1}) — four cells. Half-model per context:
s(1,0) = s(0,1) = 1/2, s(1,1) = s(0,0) = 0  (KCBS: p(a_j) = 1/2, adjacent
exclusivity, forced p(0,0) = 0).

Checks:
1. EA: adjacent contexts share exactly the subalgebra generated by the common
   coordinate; model marginals agree (1/2). Non-adjacent pairs: trivial common
   subalgebra.
2. Unrealisability: the model's zero-set forces exactly-one-fires per edge —
   impossible around an odd cycle (empty support).
3. CHAIN IMMUNITY (the load-bearing check): enumerate ALL elementary chain
   certificates — m >= 1 cells from distinct contexts, target T = a cell of a
   further context or None (exclusivity form), pointwise-valid on Omega:
   sum_t 1_{c_t} <= (m-1) + 1_T. The half-model satisfies EVERY pointwise-valid
   one. (Certificate counts are parameterization-dependent; immunity is the
   invariant claim.)
4. Family II detects it: a_j = {x_j = 1} is context-j-measurable; for every
   measure with mu(a_j cap a_{j+1}) = 0 (the model's own zeros), the support
   lies in independent sets of C5, so sum_j mu(a_j) <= alpha(C5) = 2 — the
   half-model gives 5/2 > 2.
"""
from itertools import product

Omega = list(product([0, 1], repeat=5))
CTX = range(5)

def cell(j, a, b):
    return frozenset(x for x in Omega if x[j] == a and x[(j + 1) % 5] == b)

cells = {(j, a, b): cell(j, a, b) for j in CTX for a in (0, 1) for b in (0, 1)}
sval = {(j, a, b): (0.5 if a != b else 0.0) for j in CTX for a in (0, 1) for b in (0, 1)}

# ---------- 1. EA ----------
def algebra(parts):
    out = set()
    n = len(parts)
    for mask in range(1 << n):
        u = frozenset().union(*[parts[k] for k in range(n) if mask >> k & 1]) if mask else frozenset()
        out.add(u)
    return out

for i in CTX:
    for j in CTX:
        if i < j:
            Ai = algebra([cells[(i, a, b)] for a in (0, 1) for b in (0, 1)])
            Aj = algebra([cells[(j, a, b)] for a in (0, 1) for b in (0, 1)])
            common = Ai & Aj
            shared = ({(i + 1) % 5} & {j, (j + 1) % 5}) | ({i} & {(j + 1) % 5})
            if (j - i) % 5 in (1, 4):  # adjacent: share one coordinate
                k = (i + 1) % 5 if (j - i) % 5 == 1 else i
                expect = algebra([frozenset(x for x in Omega if x[k] == v) for v in (0, 1)])
                assert common == expect
                # model agreement on {x_k = 1}:
                if (j - i) % 5 == 1:
                    mi = sval[(i, 0, 1)] + sval[(i, 1, 1)]   # x_{i+1}=1 via context i
                    mj = sval[(j, 1, 0)] + sval[(j, 1, 1)]   # x_j=1 via context j (j=i+1)
                else:                                         # j = i-1 mod 5
                    mi = sval[(i, 1, 0)] + sval[(i, 1, 1)]
                    mj = sval[(j, 0, 1)] + sval[(j, 1, 1)]
                assert abs(mi - mj) < 1e-12
            else:
                assert common == {frozenset(), frozenset(Omega)}
print("1 PASS: EA holds (adjacent overlap = shared coordinate, marginals agree; else trivial)")

# ---------- 2. Unrealisability ----------
def support_ok(x):
    return all(x[j] + x[(j + 1) % 5] == 1 for j in CTX)  # zeros force exactly-one per edge
assert not any(support_ok(x) for x in Omega)
print("2 PASS: zero-set forces exactly-one per edge — empty support on the odd cycle (unrealisable)")

# ---------- 3. Chain immunity ----------
def indicator_sum_ok(chosen, target):
    m = len(chosen)
    for x in Omega:
        lhs = sum(1 for c in chosen if x in cells[c])
        rhs = (m - 1) + (1 if (target is not None and x in cells[target]) else 0)
        if lhs > rhs:
            return False
    return True

valid = violated = 0
# chains: pick at most one cell per context (distinct contexts), m >= 1
per_ctx = [[None] + [(j, a, b) for a in (0, 1) for b in (0, 1)] for j in CTX]
for combo in product(*per_ctx):
    chosen = [c for c in combo if c is not None]
    if not chosen:
        continue
    used = {c[0] for c in chosen}
    targets = [None] + [t for t in cells if t[0] not in used]
    for target in targets:
        if indicator_sum_ok(chosen, target):
            valid += 1
            m = len(chosen)
            lhs = sum(sval[c] for c in chosen)
            rhs = (m - 1) + (sval[target] if target is not None else 0.0)
            if lhs > rhs + 1e-12:
                violated += 1
print(f"3 PASS: {valid} pointwise-valid elementary chain certificates enumerated; "
      f"half-model violates {violated} of them — CHAIN-IMMUNE" if violated == 0
      else f"3 FAIL: {violated} violations")
assert violated == 0

# ---------- 4. Family II detects ----------
# a_j = {x_j = 1}; over measures with mu(a_j cap a_{j+1}) = 0 for all j,
# support subset of independent sets of C5, whose max size is 2.
def fired(x):
    return {j for j in CTX if x[j] == 1}
def independent(x):
    S = fired(x)
    return all(not ((j in S) and ((j + 1) % 5 in S)) for j in CTX)
alpha = max(len(fired(x)) for x in Omega if independent(x))
assert alpha == 2
model_value = sum(sval[(j, 1, 0)] + sval[(j, 1, 1)] for j in CTX)
assert abs(model_value - 2.5) < 1e-12
print(f"4 PASS: stable-set bound sum mu(a_j) <= alpha(C5) = {alpha} for all measures "
      f"respecting the zero-set; half-model value = {model_value} > 2 — Family II detects it")

print("\nREFUTATION RECORD CONFIRMED: Family I (pointwise chains) incomplete; "
      "the pentagon needs the coverage/stable-set family, valid modulo the zero-set")
