#!/usr/bin/env python3
"""Exact six-generator section-congruence minimization pilot.

For each adjacent orientation, reconstruct the exact retained/opposite
six-bit pattern vectors used by the actual-event audit.  The Boolean algebra
generated by the six mixed leaves has one atom for every realized mixed truth
word z=a|b.  Its elements are therefore P(Z).

The universal-output observation includes the predicate "this section is
top".  Any Boolean congruence preserving that predicate is equality:
if x~y, then x|~y ~ top and y|~x ~ top, hence y<=x and x<=y.  Thus the
partition refinement has no nontrivial compression.  We record the exact
atom alphabets and a symbolic transition-law hash instead of enumerating the
astronomical P(Z) transition tables.

Every divergent single-slot witness substitution from the provenance audit
is replayed.  A distinguishing Boolean context is an explicit union of
mixed-word atoms whose universal-output value differs on the first changed
section.
"""
import argparse
import hashlib
import json
import os
import struct
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import full_cycle_adjacent_rectangle_intersection as inter

SCHEMA = "adjacent-section-congruence-minimization-v1"
BASE = os.path.join(HERE, "adjacent_full_cycle_actual_event_shadow.json")
DIVERSITY = os.path.join(HERE, "adjacent_full_cycle_witness_diversity.json")


def sha(obj):
    return hashlib.sha256(
        json.dumps(obj, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()


def payload():
    started = time.perf_counter()
    baseline = json.load(open(BASE))
    diversity = json.load(open(DIVERSITY))
    _, bank = inter.capture_grammar()
    events = bank["all_events"]
    macros = bank["macros"]
    engines = bank["engines"]
    states = bank["states"]
    roots = {ev: root for root, ev in bank["root_to_event"].items()}
    nstates = len(states)
    assert nstates == 224

    occ = [[[] for _ in range(nstates)] for _ in range(4)]
    for m, (_, domains) in enumerate(macros):
        for pos in range(4):
            for i, state in enumerate(domains[pos]):
                occ[pos][state].append((m, i))

    pcache = {}

    def patterns(m, rs, pos, i):
        key = (m, rs, pos, i)
        if key in pcache:
            return pcache[key]
        if all(r <= 1 for r in rs):
            ans = frozenset(
                (sum((r & 1) << k for k, r in enumerate(rs)),)
            )
        else:
            v = min(engines[m].nodes[r][0] for r in rs if r > 1)
            if v == pos:
                nxt = tuple(
                    engines[m].nodes[r][1][i]
                    if r > 1 and engines[m].nodes[r][0] == v
                    else r
                    for r in rs
                )
                ans = patterns(m, nxt, pos, i)
            else:
                ans = set()
                for q in range(len(engines[m].domains[v])):
                    nxt = tuple(
                        engines[m].nodes[r][1][q]
                        if r > 1 and engines[m].nodes[r][0] == v
                        else r
                        for r in rs
                    )
                    ans.update(patterns(m, nxt, pos, i))
                ans = frozenset(ans)
        pcache[key] = ans
        return ans

    def pattern_vector(indices, pos):
        out = []
        rr = [roots[events[e]] for e in indices]
        for state in range(nstates):
            vals = set()
            for m, i in occ[pos][state]:
                vals.update(patterns(m, tuple(r[m] for r in rr), pos, i))
            assert vals
            out.append(tuple(sorted(vals)))
        return tuple(out)

    def section_system(ap, bp):
        sections = {}
        atoms = set()
        for state in range(nstates):
            for a in ap[state]:
                zs = frozenset(a | b for b in bp[state])
                sections[(state, a)] = zs
                atoms.update(zs)
        return sections, tuple(sorted(atoms))

    orientation_records = []
    baseline_data = {}
    for rec in baseline["orientation_records"]:
        name = rec["orientation"]
        retained = tuple(rec["retained_event_indices"])
        opposite = tuple(rec["opposite_event_indices"])
        retained_pos = 3 if name.startswith("left") else 0
        opposite_pos = 0 if retained_pos == 3 else 3
        ap = pattern_vector(retained, retained_pos)
        bp = pattern_vector(opposite, opposite_pos)
        sections, atoms = section_system(ap, bp)
        atom_count = len(atoms)
        element_count = 1 << atom_count
        law = {
            "atom_words": atoms,
            "carrier": f"P({atom_count})",
            "complement": "x xor ((1<<atom_count)-1)",
            "intersection": "x & y",
            "union": "x | y",
            "universal_top_observation": "x == ((1<<atom_count)-1)",
        }
        record = {
            "orientation": name,
            "realized_mixed_word_atoms": list(atoms),
            "atom_count": atom_count,
            "boolean_algebra_element_count_decimal": str(element_count),
            "initial_observation_class_count": 2 if atom_count else 1,
            "refinement_rounds_to_equality": 1 if atom_count > 1 else 0,
            "final_congruence_class_count_decimal": str(element_count),
            "compression_ratio": "1",
            "transition_law_sha256": sha(law),
            "section_count": len(sections),
            "distinct_section_count": len(set(sections.values())),
            "section_incidence_sha256": sha(
                [(s, a, sorted(z)) for (s, a), z in sorted(sections.items())]
            ),
            "proof_rule": (
                "x~y => x union complement(y)~top and "
                "y union complement(x)~top; top-observation preservation "
                "forces y subset x and x subset y"
            ),
        }
        orientation_records.append(record)
        baseline_data[name] = {
            "retained": retained,
            "opposite": opposite,
            "retained_pos": retained_pos,
            "opposite_pos": opposite_pos,
            "ap": ap,
            "bp": bp,
            "sections": sections,
            "atoms": atoms,
        }

    divergence_replays = []
    for test in diversity["simultaneous_six_bit_pattern_tests"]:
        if not test["joint_pattern_divergence"]:
            continue
        name = test["orientation"]
        data = baseline_data[name]
        variant = list(data["opposite"])
        variant[test["leaf_slot"]] = test["alternate_opposite_event_index"]
        vbp = pattern_vector(tuple(variant), data["opposite_pos"])
        vsections, vatoms = section_system(data["ap"], vbp)
        witness = None
        for key in sorted(data["sections"]):
            x = data["sections"][key]
            y = vsections[key]
            if x == y:
                continue
            # If y is not contained in x, context x is top on baseline only.
            # Otherwise context y is top on variant only.
            if not y.issubset(x):
                context = x
                baseline_out = True
                variant_out = False
            else:
                context = y
                baseline_out = False
                variant_out = True
            witness = {
                "shared_state_index": key[0],
                "retained_pattern": key[1],
                "baseline_section_atoms": sorted(x),
                "variant_section_atoms": sorted(y),
                "context_union_atoms": sorted(context),
                "baseline_universal_output": baseline_out,
                "variant_universal_output": variant_out,
                "context_sha256": sha(sorted(context)),
            }
            break
        divergence_replays.append(
            {
                "orientation": name,
                "leaf_slot": test["leaf_slot"],
                "canonical_opposite_event_index": test[
                    "canonical_opposite_event_index"
                ],
                "alternate_opposite_event_index": test[
                    "alternate_opposite_event_index"
                ],
                "pattern_vector_diverged": True,
                "section_system_diverged": witness is not None,
                "baseline_atom_count": len(data["atoms"]),
                "variant_atom_count": len(vatoms),
                "distinguishing_context": witness,
            }
        )

    distinguished = sum(
        x["section_system_diverged"] for x in divergence_replays
    )
    out = {
        "schema": SCHEMA,
        "schema_version": "1.0",
        "base_actual_event_payload_sha256": baseline["payload_sha256"],
        "witness_diversity_payload_sha256": diversity["payload_sha256"],
        "orientation_records": orientation_records,
        "divergent_substitution_count": len(divergence_replays),
        "divergences_distinguished_by_universal_boolean_context": distinguished,
        "divergence_replays": divergence_replays,
        "verdict": (
            "no congruence compression: universal-top observation plus "
            "complement and union forces equality"
        ),
        "stop_reason": "no compression at the fixed six-generator Boolean algebra",
        "evidence_class": "Executable verified bounded evidence + hand proved congruence lemma",
        "scope": (
            "The two canonical fixed six-generator quotients and the 14 "
            "single-slot exact-root divergences. This does not cover other "
            "generators, simultaneous substitutions, arbitrary-depth mixed "
            "closure, associative transport, OML closure, sigma completion, "
            "MBRC, ODBC, or Phi."
        ),
        "verification_independence": (
            "Fresh exact pattern and section reconstruction; shares the "
            "full-cycle grammar constructor and stored leaf selections with "
            "the prior audits. Transition tables are symbolic Boolean laws, "
            "not enumerated P(Z) tables."
        ),
        "command": (
            "python3 notes/open_questions/verification/"
            "adjacent_section_congruence_minimization.py --verify"
        ),
        "pattern_cache_entries": len(pcache),
    }
    out["producer_sha256"] = hashlib.sha256(open(__file__, "rb").read()).hexdigest()
    out["payload_sha256"] = sha(out)
    return out, time.perf_counter() - started


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    out, seconds = payload()
    path = os.path.join(HERE, "adjacent_section_congruence_minimization.json")
    if args.emit:
        with open(path, "w") as f:
            json.dump(out, f, sort_keys=True, indent=2)
            f.write("\n")
    else:
        assert json.load(open(path)) == out
    print(
        json.dumps(
            {
                "status": "PASS",
                "payload_sha256": out["payload_sha256"],
                "verdict": out["verdict"],
                "distinguished": out[
                    "divergences_distinguished_by_universal_boolean_context"
                ],
                "runtime_seconds": round(seconds, 3),
            },
            sort_keys=True,
        )
    )
