#!/usr/bin/env python3
"""Full-old-signature eligibility gate for the actual Neg-023 K=0x8a transplant.

The adjacent carrier is never materialized.  Weighted MDD traversal counts the
seven-coordinate physical points by the fourteen labelled ARR words.  The
complete pulled-old-cylinder signature is represented by the two old-copy
four-tuples.  This representation is complete because each old copy contains
all four embedded conditional-cell event families and those predicates separate
the 224 cell point states.  Hence the pair of full-old signatures recovers the
seven-coordinate adjacent point exactly.

This is an eligibility result for a physical subset with the transported K
empty/full/proper profile orientation.  It does not assert that this subset is
generated by, or can be adjoined to, the full-old mixed closure.
"""
import argparse
import collections
import hashlib
import itertools
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
PILOT = HERE / "arr_cyl_critical_sublattice_pilot.py"
ELIGIBILITY = HERE / "arr_k8a_transplant_eligibility.py"
ELIGIBILITY_RECEIPT = HERE / "arr_k8a_transplant_eligibility.json"
FACTOR_RECEIPT = HERE / "adjacent_full_cycle_union_factor_checkpoint.json"
RECEIPT = HERE / "arr_k8a_full_old_signature_gate.json"


def digest(value):
    return hashlib.sha256(json.dumps(
        value, sort_keys=True, separators=(",", ":")
    ).encode()).hexdigest()


def recover():
    """Run the banked producer in memory and expose its exact ARR objects."""
    source = PILOT.read_text()
    needle = "    source=json.load(open(SOURCE_RECEIPT));ar_source=json.load(open(AR_RECEIPT))"
    assert source.count(needle) == 1
    expose = (
        "    globals()['_FULL_SIGNATURE_GATE']={'bank':bank,'arr':arr,"
        "'atom_words':atom_words,'right_family':right_f,'K':K}\n"
    )
    source = source.replace(needle, expose + needle)
    namespace = {"__file__": str(PILOT), "__name__": "_arr_full_signature_gate"}
    exec(compile(source, str(PILOT), "exec"), namespace)
    namespace["payload"]()
    return namespace["_FULL_SIGNATURE_GATE"]


def weighted_patterns(engine, roots, fixed_pos, fixed_index, domains):
    """Count assignments by simultaneous root truth word with one variable fixed."""
    cache = {}

    def domain_size(v):
        return 1 if v == fixed_pos else len(domains[v])

    def go(rs, next_variable):
        key = (rs, next_variable)
        if key in cache:
            return cache[key]
        live = [engine.nodes[r][0] for r in rs if r > 1]
        if not live:
            multiplier = 1
            for v in range(next_variable, len(domains)):
                multiplier *= domain_size(v)
            word = sum((r & 1) << k for k, r in enumerate(rs))
            ans = collections.Counter({word: multiplier})
        else:
            variable = min(live)
            skipped = 1
            for v in range(next_variable, variable):
                skipped *= domain_size(v)
            choices = (fixed_index,) if variable == fixed_pos else range(len(domains[variable]))
            ans = collections.Counter()
            for choice in choices:
                nxt = tuple(
                    engine.nodes[r][1][choice]
                    if r > 1 and engine.nodes[r][0] == variable else r
                    for r in rs
                )
                ans.update(go(nxt, variable + 1))
            if skipped != 1:
                ans = collections.Counter({word: count * skipped
                                           for word, count in ans.items()})
        cache[key] = ans
        return ans

    return go(tuple(roots), 0)


def quotient_atoms(data):
    groups = {}
    for word_index, word in enumerate(data["atom_words"]):
        signature = tuple(int(bool(event & (1 << word_index)))
                          for event in sorted(data["right_family"]))
        groups.setdefault(signature, []).append((word_index, tuple(word)))
    atoms = sorted(groups.values(), key=lambda group: group[0])
    word_to_atom = {word_index: atom for atom, group in enumerate(atoms)
                    for word_index, _ in group}
    return atoms, word_to_atom


def payload():
    data = recover()
    bank, arr = data["bank"], data["arr"]
    events, macros = bank["all_events"], bank["macros"]
    engines, states = bank["engines"], bank["states"]
    roots = {event: root for root, event in bank["root_to_event"].items()}
    assert len(events) == 18676 and len(states) == 224

    # The four embedded cell event families separate cell state labels.  This
    # is the executable premise of the hand completeness proof.
    import full_grid_terminal_split_one_cell_quotient as one
    local = sorted(one.local_event_predicates(states))
    cell_signatures = [tuple(int(bool(event & (1 << state))) for event in local)
                       for state in range(len(states))]
    assert len(set(cell_signatures)) == len(states)

    occ = [[[] for _ in states] for _ in range(4)]
    for macro, (_, domains) in enumerate(macros):
        for position in range(4):
            for index, state in enumerate(domains[position]):
                occ[position][state].append((macro, index))

    retained = tuple(arr["retained"])
    opposite = tuple(arr["opposite"])
    K = tuple(data["K"])
    left_indices = retained + K
    right_indices = opposite + K
    assert len(left_indices) == len(right_indices) == 10

    # Count exact old-copy point signatures by the ten-bit labelled patterns.
    left_counts = [collections.Counter() for _ in states]
    right_counts = [collections.Counter() for _ in states]
    for shared_state in range(len(states)):
        for macro, index in occ[arr["pos"]][shared_state]:
            domains = macros[macro][1]
            rs = [roots[events[event]][macro] for event in left_indices]
            left_counts[shared_state].update(weighted_patterns(
                engines[macro], rs, arr["pos"], index, domains
            ))
        for macro, index in occ[arr["oppos"]][shared_state]:
            domains = macros[macro][1]
            rs = [roots[events[event]][macro] for event in right_indices]
            right_counts[shared_state].update(weighted_patterns(
                engines[macro], rs, arr["oppos"], index, domains
            ))

    atoms, word_to_atom = quotient_atoms(data)
    word_counts = collections.Counter()
    for shared_state in range(len(states)):
        for left_word, left_count in left_counts[shared_state].items():
            a, lk = left_word & 63, left_word >> 6
            for right_word, right_count in right_counts[shared_state].items():
                b, rk = right_word & 63, right_word >> 6
                u = (arr["F"] >> (a | (b << 6))) & 1
                word_counts[(lk, rk, u)] += left_count * right_count

    assert set(word_counts) == set(data["atom_words"]), {
        "missing": sorted(set(data["atom_words"]) - set(word_counts)),
        "extra": sorted(set(word_counts) - set(data["atom_words"])),
    }
    total = sum(word_counts.values())
    factor = json.loads(FACTOR_RECEIPT.read_text())
    assert total == factor["global_carrier_points"] == 211897540016

    eligibility = json.loads(ELIGIBILITY_RECEIPT.read_text())
    iso = eligibility["pointed_isomorphisms"][0]
    transported = {row["actual_atom"]: row for row in iso["transported_atoms"]}
    atom_rows = []
    for atom, labelled_words in enumerate(atoms):
        rows = []
        for word_index, word in labelled_words:
            count = word_counts[word]
            rows.append({
                "word_index": word_index,
                "word": list(word),
                "complete_full_old_signature_count": count,
            })
        count = sum(row["complete_full_old_signature_count"] for row in rows)
        orientation = transported[atom]["generic_k_membership"]
        atom_rows.append({
            "actual_atom": atom,
            "generic_atom": transported[atom]["generic_atom"],
            "transported_k_membership": orientation,
            "labelled_word_count": len(rows),
            "labelled_words": rows,
            "complete_full_old_signature_count": count,
            "proper_split_physically_possible": orientation != "proper" or count >= 2,
        })

    crossed = [row for row in atom_rows if row["transported_k_membership"] == "proper"]
    assert [row["actual_atom"] for row in crossed] == [0, 3, 4]
    simultaneous = all(row["complete_full_old_signature_count"] >= 2 for row in crossed)
    # A deterministic witness subset: the least complete signature in each
    # crossed atom, all signatures in full atoms, none in empty atoms.  We do
    # not serialize the enormous seven-tuples; existence and uniqueness of the
    # lexicographic least tuple follow from the finite nonempty counted class.
    # The exact selector count is a product of (2^n-2) terms with enormous n.
    # Constructing that integer would itself be an accidental heavy workload;
    # positivity is equivalent to the already audited n>=2 conditions.

    source_receipt = json.loads(ELIGIBILITY_RECEIPT.read_text())
    result = {
        "schema": "arr-k8a-full-old-signature-gate-v1",
        "schema_version": "1.0",
        "source_eligibility_payload_sha256": source_receipt["payload_sha256"],
        "old_events_per_copy": len(events),
        "cell_states": len(states),
        "cell_event_predicates": len(local),
        "cell_state_membership_signatures_distinct": len(set(cell_signatures)),
        "adjacent_carrier_complete_signature_count": total,
        "realized_labelled_word_count": len(word_counts),
        "profile_atoms": atom_rows,
        "crossed_actual_atoms": [row["actual_atom"] for row in crossed],
        "all_crossed_atoms_have_at_least_two_complete_signatures": simultaneous,
        "one_physical_selector_with_transported_orientation_exists": simultaneous,
        "selector_witness_rule": (
            "Take every complete full-old signature in transported-full atoms, "
            "none in transported-empty atoms, and the lexicographically least "
            "complete signature in each transported-proper atom."
        ),
        "signature_completeness_theorem": (
            "Each full old copy contains all four embedded conditional-cell "
            "cylinder families. Their 56 cell predicates separate the 224 cell "
            "states, so the full-old cylinder membership signature recovers "
            "each of the four coordinate state labels. The pair of old-copy "
            "signatures therefore recovers the adjacent seven-coordinate point "
            "(the shared coordinate occurs in both tuples). Thus the weighted "
            "MDD point count is exactly the count of complete labelled full-old "
            "signatures, not merely a coarse word multiplicity."
        ),
        "evidence_class": "Executable verified — exhaustive finite scope",
        "hand_claim": "Signature completeness, conditional on the executable separation and embedded-cylinder premises.",
        "verification_independence": (
            "One deterministic implementation reusing the banked ARR producer; "
            "the total is independently anchored to the prior union-factor receipt."
        ),
        "scope": (
            "Exact weighted-MDD census of all 211,897,540,016 physical points by "
            "the fourteen actual ARR labelled words, refined by the complete "
            "membership signatures of both full old cylinder copies. It proves "
            "existence of a physical subset having the transported K empty/full/"
            "proper orientation. It does not prove that subset is in the generated "
            "event family, that adjoining it preserves either old copy, or any "
            "closure, lattice, OML, centre, state, sigma, ODBC, or Phi claim."
        ),
        "hostile_self_review": [
            "The completeness proof uses the presence of all four embedded cell cylinder families; it is not a theorem for an arbitrary 18,676-event representation.",
            "A complete signature is a physical point here because the cell predicates separate coordinate labels. This does not make its singleton an event.",
            "The deterministic selector is only a subset candidate. Generated-event membership is precisely the next unresolved gate.",
            "The producer shares the ARR construction and MDD implementation with its source; only the aggregate carrier count is externally cross-checked.",
        ],
        "next_gate": (
            "Represent the deterministic three-crossing selector as a compact MDD "
            "and adjoin it to both complete old cylinder copies plus Neg-023; audit "
            "the first mixed cut or bounded closure without materializing the carrier."
        ),
        "producer_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "command": "PYTHONHASHSEED=0 python3 notes/open_questions/verification/arr_k8a_full_old_signature_gate.py --verify",
    }
    # Avoid serializing the astronomical number of selector subsets.  Its
    # positivity is certified separately by the count>=2 checks above.
    assert simultaneous
    result["payload_sha256"] = digest(result)
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    result = payload()
    if args.emit:
        RECEIPT.write_text(json.dumps(result, sort_keys=True, indent=2) + "\n")
    if args.verify or not args.emit:
        assert json.loads(RECEIPT.read_text()) == result
    print(json.dumps({
        "status": "PASS",
        "payload_sha256": result["payload_sha256"],
        "complete_signatures": result["adjacent_carrier_complete_signature_count"],
        "simultaneous_selector": result["one_physical_selector_with_transported_orientation_exists"],
    }, sort_keys=True))


if __name__ == "__main__":
    main()
