#!/usr/bin/env python3
"""Exact census for the stripped grouped-output bipartite coordinate core.

For m hub bits q_a and n private bits r_i, take the union of the Boolean
edge algebras generated by each pair (q_a,r_i), represented on 2^(m+n)
truth assignments.  Close inside that carrier under complement and disjoint
union, then audit the resulting concrete orthocomplemented event family.

The stored cases are K_2,2, K_2,3 and K_3,2.  This is a coordinate-only
control: it contains no conditional-cell enforcement gadgets and makes no
finite-to-infinite claim.
"""
import argparse, hashlib, json, os
from itertools import combinations, product

HERE = os.path.dirname(os.path.abspath(__file__))
SCHEMA = "bipartite-coordinate-core-v1"
CASES = ((2, 2), (2, 3), (3, 2))

def carrier(m, n):
    return list(product((0, 1), repeat=m+n))

def mask(points, pred):
    return sum(1 << j for j, p in enumerate(points) if pred(p))

def raw_family(m, n, points):
    out = {0, (1 << len(points))-1}
    for a in range(m):
        for i in range(n):
            for allowed in range(16):
                out.add(mask(points, lambda p, a=a, i=i, allowed=allowed:
                             bool(allowed & (1 << (2*p[a]+p[m+i])))))
    return out

def close(raw, full):
    ev = set(raw); rounds=[]
    while True:
        new={full ^ x for x in ev}-ev; snap=sorted(ev)
        for j,x in enumerate(snap):
            for y in snap[j+1:]:
                if not x & y and x|y not in ev: new.add(x|y)
        rounds.append(len(new))
        if not new: return sorted(ev), rounds
        ev |= new

def extrema(ev, x, y):
    ub=[z for z in ev if x|z==z and y|z==z]
    mu=[z for z in ub if not any(w!=z and w|z==z for w in ub)]
    lb=[z for z in ev if z|x==x and z|y==y]
    ml=[z for z in lb if not any(w!=z and z|w==w for w in lb)]
    return mu,ml

def bronk(adj):
    ans=[]
    def go(r,p,x):
        if not p and not x: ans.append(tuple(sorted(r))); return
        pivot=max(p|x,key=lambda u:len(p&adj[u])) if p|x else None
        for v in list(p-(adj[pivot] if pivot is not None else set())):
            go(r|{v},p&adj[v],x&adj[v]); p.remove(v); x.add(v)
    go(set(),set(adj),set()); return ans

def audit(m,n):
    pts=carrier(m,n); full=(1<<len(pts))-1
    raw=raw_family(m,n,pts); ev,rounds=close(raw,full); idx={x:j for j,x in enumerate(ev)}
    joins={}; meets={}; failures=[]
    for j,x in enumerate(ev):
        for y in ev[j:]:
            mu,ml=extrema(ev,x,y)
            if len(mu)!=1 or len(ml)!=1: failures.append((x,y,len(mu),len(ml)))
            else: joins[x,y]=joins[y,x]=mu[0]; meets[x,y]=meets[y,x]=ml[0]
    lattice=not failures
    oml=False
    # Set-Boolean compatibility is meaningful before latticehood: x,y generate
    # a Boolean subalgebra precisely when all four truth cells are events.
    def setcomm(x,y):
        return all(z in idx for z in (x&y,x&(full^y),(full^x)&y,(full^x)&(full^y)))
    centre=[x for x in ev if all(setcomm(x,y) for y in ev)]
    adj={x:{y for y in ev if y!=x and setcomm(x,y)} for x in ev}
    blocks=bronk(adj)
    if lattice:
        oml=all(joins[meets[y,full^x],x]==y for x in ev for y in ev if x|y==y)
        def comm(x,y):
            return joins[meets[x,y],meets[x,full^y]]==x
    # A genuine joint reconstruction for two coordinates means all 16 events
    # of their Boolean pair algebra occur, equivalently all four joint atoms.
    recon={}
    names=[("q",a,a) for a in range(m)]+[("r",i,m+i) for i in range(n)]
    for (ta,ia,ca),(tb,ib,cb) in combinations(names,2):
        atoms=[mask(pts,lambda p,ca=ca,cb=cb,u=u,v=v:p[ca]==u and p[cb]==v)
               for u,v in product((0,1),repeat=2)]
        recon[f"{ta}{ia}-{tb}{ib}"]=all(z in idx for z in atoms)
    hist={}
    for x in ev:
        support=0
        for c in range(m+n):
            # dependence: flip c while fixing all other coordinates
            if any(bool(x&(1<<j)) != bool(x&(1<<(j^(1<<(m+n-1-c))))) for j in range(len(pts))):
                support+=1
        hist[str(support)]=hist.get(str(support),0)+1
    ff=None
    if failures:
        x,y,_,_=failures[0]; mu,ml=extrema(ev,x,y)
        deps=lambda z:[("q"+str(c) if c<m else "r"+str(c-m)) for c in range(m+n)
                       if any(bool(z&(1<<j)) != bool(z&(1<<(j^(1<<(m+n-1-c))))) for j in range(len(pts)))]
        ff={"x_hex":hex(x),"y_hex":hex(y),"x_support":deps(x),"y_support":deps(y),
            "minimal_upper_bounds_hex":[hex(z) for z in mu],
            "minimal_upper_bound_supports":[deps(z) for z in mu],
            "maximal_lower_bounds_hex":[hex(z) for z in ml]}
    payload={"schema":SCHEMA,"m":m,"n":n,"points":len(pts),"raw_events":len(raw),
             "completed_events":len(ev),"closure_rounds":rounds,"support_histogram":hist,
             "lattice":lattice,"orthomodular":oml,"centre_size":len(centre),
             "maximal_blocks":len(blocks),"maximal_block_size_histogram":{},
             "pairwise_joint_reconstruction":recon,
             "maximal_blocks_and_centre_semantics":"set-Boolean compatibility (four truth cells present)",
             "first_lattice_failure":ff}
    for b in blocks:
        payload["maximal_block_size_histogram"][str(len(b))]=payload["maximal_block_size_histogram"].get(str(len(b)),0)+1
    return payload

def path(m,n): return os.path.join(HERE,f"bipartite_coordinate_core_k{m}_{n}.json")
def canonical(p): return json.dumps(p,sort_keys=True,indent=2)+"\n"
def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--emit",action="store_true"); args=ap.parse_args()
    for m,n in CASES:
        p=audit(m,n); p["payload_sha256"]=hashlib.sha256(canonical(p).encode()).hexdigest()
        if args.emit: open(path(m,n),"w").write(canonical(p))
        else:
            got=json.load(open(path(m,n))); assert got==p,(m,n)
        print(f"K_{{{m},{n}}}: {p['raw_events']} -> {p['completed_events']}, lattice={p['lattice']}, blocks={p['maximal_blocks']}")
if __name__=="__main__": main()
