#!/usr/bin/env python3
"""Campaign-14 finite gate: incompatible-H4 conditional cell — audit + deterministic receipts.

Target: notes/open_questions/oml_attack/oml_puncture_normality_and_incompatible_transport.md §8.
Constructs finite pasted posets from block presentations (optionally with
subalgebra identifications), then checks EXHAUSTIVELY (no OMP->OML promotion,
no Loop-Lemma appeal): latticehood, ortholattice axioms, orthomodular law,
two-valued-state additivity, order-determination, concreteness, MO3 (H_4)
activation control, centre, maximal blocks, gate projection shape, escape,
and no-representing-event.

Designs audited (one receipt each):
  1. cell            — the 24-atom, 12-block gate cell (passes; receipt embeds
                       the exhaustive state table, so no separate table file)
  2. paste_A         — two copies sharing the MAXIMAL 4-atom block E, disjoint
                       activation triples
  3. paste_B         — two copies sharing the maximal block E AND the
                       activation triple
  4. refuted_single_mediator — one mediator atom cohabiting both difference
                       atoms of E (3-loop): latticehood FAILS
  5. refuted_reused_n1       — cascade 2 reusing n1 (4-loop): latticehood FAILS
  6. shared_q_two_cascades   — two full cells sharing ONLY the NONMAXIMAL
                       four-element subalgebra {0,q,q',1} generated by q
                       (q identified across two distinct maximal 4-atom blocks)
  7. shared_q_shared_mediators_refuted — same identification but economizing:
                       one mediator pair serving both coordinate blocks
  8. refuted_bare_subalgebra_paste — minimal core of the shared-q failure:
                       just TWO 4-atom blocks identified along {0,q,q',1};
                       already not a lattice (join(e00,f10) has two
                       incomparable minimal upper bounds e01' and f11')

Usage (exact commands, from this directory):
  python3 incompatible_h4_conditional_cell_audit.py --emit    # regenerate receipts
  python3 incompatible_h4_conditional_cell_audit.py --verify  # recompute + compare (default)

Verify mode recomputes every payload from scratch and compares it field-for-field
against the stored receipt, and re-checks each receipt's payload_sha256.
Exit code 0 iff every receipt matches. stdlib only, deterministic
(independent of PYTHONHASHSEED).
"""
import hashlib
import json
import os
import sys
from itertools import combinations

SCHEMA = "oml-finite-cell-receipt"
SCHEMA_VERSION = "1.0"
EMIT_DATE = "2026-07-14"
GENERATOR = "incompatible_h4_conditional_cell_audit.py"
COMMAND = "python3 incompatible_h4_conditional_cell_audit.py --verify"
HERE = os.path.dirname(os.path.abspath(__file__))

ZERO = ('zero',)
ONE = ('one',)


def ekey(e):
    """Canonical deterministic string key for an element."""
    if e == ZERO:
        return "0"
    if e == ONE:
        return "1"
    k, x = e
    if k == 'a':
        return "a:" + x
    if k == 'c':
        return "c:" + x
    return "m:" + "+".join(sorted(x))


class Logic:
    """Pasted poset from a block presentation.

    blocks: list of atom lists (each block = maximal Boolean subalgebra).
    ident: element-level identifications {element: canonical_element}, used to
           paste two 4-atom blocks along the nonmaximal subalgebra {0,q,q',1}.
    couplings: list of (atomset1, atomset2) whose charge-sums must agree in
           every two-valued state (the state-side shadow of ident).
    Order = transitive closure of block-internal Boolean orders. Everything
    downstream is checked exhaustively; nothing is assumed from Greechie theory.
    """

    def __init__(self, name, blocks, ident=None, couplings=None):
        self.name = name
        self.blocks = [tuple(b) for b in blocks]
        self.ident = ident or {}
        self.couplings = [(tuple(s1), tuple(s2)) for s1, s2 in (couplings or [])]
        self.atoms = sorted({a for b in blocks for a in b})
        for B, C in combinations(self.blocks, 2):
            assert len(set(B) & set(C)) <= 1, ("blocks share >1 atom", B, C)
        els = {ZERO, ONE}
        self.block_elems = {}
        self.mid_block = {}
        for bi, B in enumerate(self.blocks):
            n = len(B)
            pairs = []
            for k in range(n + 1):
                for S in combinations(B, k):
                    S = frozenset(S)
                    if k == 0:
                        e = ZERO
                    elif k == n:
                        e = ONE
                    elif k == 1:
                        e = ('a', min(S))
                    elif k == n - 1:
                        e = ('c', min(set(B) - S))
                    else:
                        e = ('m', S)
                        self.mid_block.setdefault(S, bi)
                    e = self.ident.get(e, e)
                    pairs.append((S, e))
            self.block_elems[bi] = pairs
            for S, e in pairs:
                els.add(e)
        self.elements = sorted(els, key=ekey)
        self.n = len(self.elements)
        self.idx = {e: i for i, e in enumerate(self.elements)}
        n = self.n
        le = [[False] * n for _ in range(n)]
        for i in range(n):
            le[i][i] = True
        z, o = self.idx[ZERO], self.idx[ONE]
        for i in range(n):
            le[z][i] = True
            le[i][o] = True
        for bi in self.block_elems:
            ps = self.block_elems[bi]
            for S, e in ps:
                for T, f in ps:
                    if S <= T:
                        le[self.idx[e]][self.idx[f]] = True
        changed = True
        while changed:
            changed = False
            for k in range(n):
                lk = le[k]
                for i in range(n):
                    if le[i][k]:
                        li = le[i]
                        for j in range(n):
                            if lk[j] and not li[j]:
                                li[j] = True
                                changed = True
        self.le = le
        for i in range(n):
            for j in range(n):
                if i != j:
                    assert not (le[i][j] and le[j][i]), \
                        ("antisymmetry", ekey(self.elements[i]), ekey(self.elements[j]))

    def comp(self, e):
        if e == ZERO:
            return ONE
        if e == ONE:
            return ZERO
        k, x = e
        if k == 'a':
            return ('c', x)
        if k == 'c':
            return ('a', x)
        bi = self.mid_block[x]
        f = ('m', frozenset(self.blocks[bi]) - x)
        return self.ident.get(f, f)

    def build_tables(self):
        """Exact latticehood filter: unique glb/lub for every pair, else record
        the FIRST failed pair (deterministic: elements sorted by ekey)."""
        n, le = self.n, self.le
        self.meet = [[None] * n for _ in range(n)]
        self.join = [[None] * n for _ in range(n)]
        self.lattice_ok, self.lattice_fail = True, None
        for i in range(n):
            for j in range(i, n):
                lows = [k for k in range(n) if le[k][i] and le[k][j]]
                tops = [k for k in lows if all(le[t][k] for t in lows)]
                if len(tops) != 1:
                    self.lattice_ok = False
                    self.lattice_fail = {"kind": "meet", "x": ekey(self.elements[i]),
                                         "y": ekey(self.elements[j])}
                    return
                self.meet[i][j] = self.meet[j][i] = tops[0]
                ups = [k for k in range(n) if le[i][k] and le[j][k]]
                bots = [k for k in ups if all(le[k][t] for t in ups)]
                if len(bots) != 1:
                    self.lattice_ok = False
                    self.lattice_fail = {"kind": "join", "x": ekey(self.elements[i]),
                                         "y": ekey(self.elements[j])}
                    return
                self.join[i][j] = self.join[j][i] = bots[0]

    def check_ortholattice(self):
        n, le = self.n, self.le
        cidx = [self.idx[self.comp(e)] for e in self.elements]
        self.cidx = cidx
        for i in range(n):
            assert cidx[cidx[i]] == i
            for j in range(n):
                if le[i][j]:
                    assert le[cidx[j]][cidx[i]], ("antitone", i, j)
            assert self.meet[i][cidx[i]] == self.idx[ZERO]
            assert self.join[i][cidx[i]] == self.idx[ONE]
        for i in range(n):
            for j in range(n):
                if le[i][j]:
                    if self.join[i][self.meet[cidx[i]][j]] != j:
                        return False, {"x": ekey(self.elements[i]), "y": ekey(self.elements[j])}
        return True, None

    # Two-valued states = exactly-one-charged-atom-per-block assignments that
    # respect the couplings. (Hand lemma: additivity on a block forces charge
    # sum 1; atom values determine the state; identified elements force the
    # coupling equations. Additivity is nevertheless re-checked exhaustively.)
    def all_states(self):
        blocks = self.blocks
        val = {}
        out = []

        def coupling_ok():
            for s1, s2 in self.couplings:
                if sum(val[a] for a in s1) != sum(val[a] for a in s2):
                    return False
            return True

        def dfs(bi):
            if bi == len(blocks):
                if coupling_ok():
                    out.append(dict(val))
                return
            B = blocks[bi]
            ones = [a for a in B if val.get(a) == 1]
            if len(ones) > 1:
                return
            cands = ones if ones else [a for a in B if val.get(a) is None]
            for c in cands:
                touched = []
                ok = True
                if val.get(c) is None:
                    val[c] = 1
                    touched.append(c)
                for a in B:
                    if a == c:
                        continue
                    if val.get(a) == 1:
                        ok = False
                        break
                    if val.get(a) is None:
                        val[a] = 0
                        touched.append(a)
                if ok:
                    dfs(bi + 1)
                for a in touched:
                    del val[a]

        dfs(0)
        return out

    def sval(self, sol, e):
        if e == ZERO:
            return 0
        if e == ONE:
            return 1
        k, x = e
        if k == 'a':
            return sol[x]
        if k == 'c':
            return 1 - sol[x]
        v = sum(sol[a] for a in x)
        assert v <= 1
        return v

def audit_payload(name, blocks, triples, q_specs, shared_structure=None,
                  ident=None, couplings=None, include_state_table=False,
                  relations_hook=None):
    """Compute the full deterministic audit payload for one design.

    triples: list of activation triples (atom names).
    q_specs: dict label -> ('m', frozenset) designated coordinate events.
    relations_hook(L, states) -> dict of design-specific relation summaries.
    """
    L = Logic(name, blocks, ident=ident, couplings=couplings)
    payload = {
        "design": name,
        "shared_structure": shared_structure,
        "construction": {
            "atoms": L.atoms,
            "blocks": [sorted(b) for b in L.blocks],
            "identifications": sorted([ekey(k), ekey(v)] for k, v in (ident or {}).items()),
            "couplings": [[sorted(s1), sorted(s2)] for s1, s2 in (couplings or [])],
            "designated": {
                "activation_triples": [list(t) for t in triples],
                **{lab: ekey(e) for lab, e in sorted(q_specs.items())},
            },
        },
        "counts": {"atoms": len(L.atoms), "blocks": len(L.blocks), "elements": L.n},
    }
    L.build_tables()
    payload["audit"] = {"lattice_ok": L.lattice_ok,
                        "first_failed_lattice_pair": L.lattice_fail}
    if not L.lattice_ok:
        return payload
    om_ok, om_wit = L.check_ortholattice()
    payload["audit"]["ortholattice_ok"] = True
    payload["audit"]["orthomodular_ok"] = om_ok
    payload["audit"]["orthomodular_witness"] = om_wit
    if not om_ok:
        return payload

    states = L.all_states()
    ns = len(states)
    payload["counts"]["two_valued_states"] = ns
    full = (1 << ns) - 1
    supp = []
    for e in L.elements:
        m = 0
        for si, s in enumerate(states):
            if L.sval(s, e):
                m |= (1 << si)
        supp.append(m)
    add_ok = True
    for i in range(L.n):
        for j in range(L.n):
            if L.le[i][L.cidx[j]]:
                if supp[L.join[i][j]] != (supp[i] | supp[j]) or (supp[i] & supp[j]):
                    add_ok = False
    odet_ok = all(L.le[i][j] == ((supp[i] | supp[j]) == supp[j])
                  for i in range(L.n) for j in range(L.n))
    inj_ok = len(set(supp)) == L.n
    payload["audit"]["state_additivity_ok"] = add_ok
    payload["audit"]["order_determination_ok"] = odet_ok
    payload["audit"]["support_map_injective_ok"] = inj_ok

    def commutes(i, j):
        return L.join[L.meet[i][j]][L.meet[i][L.cidx[j]]] == i
    payload["audit"]["centre"] = sorted(
        ekey(L.elements[i]) for i in range(L.n)
        if all(commutes(i, j) for j in range(L.n)))

    coh = {a: set() for a in L.atoms}
    for B in L.blocks:
        for x, y in combinations(B, 2):
            coh[x].add(y)
            coh[y].add(x)
    cliques = []

    def bk(R, P, X):
        if not P and not X:
            cliques.append(sorted(R))
            return
        for v in sorted(P):
            bk(R | {v}, P & coh[v], X & coh[v])
            P = P - {v}
            X = X | {v}
    bk(set(), set(L.atoms), set())
    payload["audit"]["maximal_blocks"] = sorted(cliques)
    payload["audit"]["maximal_blocks_equal_declared"] = \
        sorted(cliques) == sorted(sorted(b) for b in L.blocks)

    mo3 = {}
    for trip in triples:
        A = [('a', a) for a in trip]
        gen = {L.idx[e] for e in [ZERO, ONE] + A + [L.comp(e) for e in A]}
        while True:
            new = set(gen)
            for i in gen:
                new.add(L.cidx[i])
                for j in gen:
                    new.add(L.meet[i][j])
                    new.add(L.join[i][j])
            if new == gen:
                break
            gen = new
        rel_ok = all(L.meet[L.idx[x]][L.idx[y]] == L.idx[ZERO]
                     and L.join[L.idx[x]][L.idx[y]] == L.idx[ONE]
                     for x, y in combinations(A, 2))
        mo3[",".join(trip)] = {"generated_subOML_size": len(gen),
                               "mo3_relations_ok": rel_ok,
                               "is_H4_horizontal_sum": len(gen) == 8 and rel_ok}
    payload["audit"]["h4_controls"] = mo3

    esc, norep = {}, {}
    for trip in triples:
        cyl = supp[L.idx[('a', trip[0])]] & supp[L.idx[('a', trip[1])]] \
            & supp[L.idx[('a', trip[2])]]
        key = ",".join(trip)
        esc[key] = all(supp[i] & (full & ~cyl)
                       for i in range(L.n) if L.elements[i] != ZERO)
        norep[key] = (cyl != 0) and all(supp[i] != cyl for i in range(L.n))
    payload["audit"]["escape_every_nonzero_event_charged_off_111"] = esc
    payload["audit"]["no_event_represents_111_cylinder"] = norep

    projections = {}
    for trip in triples:
        for qlab in sorted(q_specs):
            if qlab.startswith("q"):
                continue
            qe, re_ = q_specs["q"], q_specs[qlab]
            fibers = {}
            for s in states:
                bits = "".join(str(L.sval(s, ('a', a))) for a in trip) \
                    + str(L.sval(s, qe)) + str(L.sval(s, re_))
                fibers[bits] = fibers.get(bits, 0) + 1
            pk = ",".join(trip) + "|q," + qlab
            projections[pk] = {
                "fiber_counts": {k: fibers[k] for k in sorted(fibers)},
                "contains_11100": fibers.get("11100", 0) > 0,
                "contains_11111": fibers.get("11111", 0) > 0,
                "excludes_11101": fibers.get("11101", 0) == 0,
                "excludes_11110": fibers.get("11110", 0) == 0,
                "off_111_all_four_qr_profiles": all(
                    fibers.get("%d%d%d%d%d" % (x, y, z, u, v), 0) > 0
                    for x in (0, 1) for y in (0, 1) for z in (0, 1)
                    if (x, y, z) != (1, 1, 1) for u in (0, 1) for v in (0, 1)),
            }
    payload["projections"] = projections

    if relations_hook:
        payload["relations"] = relations_hook(L, states)
    if include_state_table:
        payload["state_table"] = {
            "atom_order": L.atoms,
            "rows": sorted("".join(str(s[a]) for a in L.atoms) for s in states),
        }
    return payload

# ---------------------------------------------------------------- designs

def cell_blocks(sfx="", acts=("a1", "a2", "a3"), E=("e11", "e10", "e01", "e00"),
                own_E=True):
    """The gate cell: AND-arm (a1,a2 -> w1), two mediator chains (w1,a3 -> t1,t2),
    difference-killers t1-e10, t2-e01, coordinate block E.
    q = e11 v e10, r = e11 v e01; on activation 111 the cascade forces
    e10 = e01 = 0, so the state projection keeps 11100/11111 and drops
    11101/11110 with no event supported inside the cylinder."""
    a1, a2, a3 = acts

    def s(x):
        return x + sfx
    B = [
        [a1, s("u1"), s("p11")], [a2, s("v1"), s("p12")],
        [s("u1"), s("v1"), s("w1")],
        [a3, s("n1"), s("p15")], [s("w1"), s("m1"), s("p14")],
        [s("m1"), s("n1"), s("t1")],
        [a3, s("n2"), s("p25")], [s("w1"), s("m2"), s("p24")],
        [s("m2"), s("n2"), s("t2")],
        [s("t1"), E[1], s("s1")], [s("t2"), E[2], s("s2")],
    ]
    if own_E:
        B.append(list(E))
    return B


E1 = ("e11", "e10", "e01", "e00")
E2 = ("f11", "f10", "f01", "f00")
Q = ('m', frozenset({"e11", "e10"}))
R = ('m', frozenset({"e11", "e01"}))
R2 = ('m', frozenset({"f11", "f01"}))
IDENT_Q = {('m', frozenset({"f11", "f10"})): Q,
           ('m', frozenset({"f01", "f00"})): ('m', frozenset({"e01", "e00"}))}
COUPLE_Q = [(("e11", "e10"), ("f11", "f10"))]


def joint_hook(triple_a, triple_b):
    def hook(L, states):
        fib = [s for s in states
               if all(s[a] for a in triple_a) and all(s[b] for b in triple_b)]
        return {"joint_111_111": {
            "triples": [list(triple_a), list(triple_b)],
            "fiber_size": len(fib),
            "qr_values": sorted({(L.sval(s, Q), L.sval(s, R)) for s in fib}),
        }}
    return hook


def sharedq_hook(L, states):
    fib = [s for s in states if s["a1"] and s["a2"] and s["a3"]]
    coupling = all(s["e11"] + s["e10"] == s["f11"] + s["f10"] for s in states)
    return {
        "fiber_111_q_r1_r2_values": sorted(
            {(L.sval(s, Q), L.sval(s, R), L.sval(s, R2)) for s in fib}),
        "fiber_111_size": len(fib),
        "coupling_q_consistent_in_all_states": coupling,
    }


def build_designs():
    designs = []
    designs.append(("receipt_cell_incompatible_h4_conditional.json", dict(
        name="cell", blocks=cell_blocks(), triples=[("a1", "a2", "a3")],
        q_specs={"q": Q, "r": R}, include_state_table=True,
        shared_structure=None)))
    designs.append(("receipt_paste_A_shared_maximal_block_E.json", dict(
        name="paste_A",
        blocks=cell_blocks() + cell_blocks(sfx="B", acts=("b1", "b2", "b3"),
                                           own_E=False),
        triples=[("a1", "a2", "a3"), ("b1", "b2", "b3")],
        q_specs={"q": Q, "r": R},
        shared_structure="shared MAXIMAL block E (4-atom coordinate block); "
                         "disjoint activation triples",
        relations_hook=joint_hook(("a1", "a2", "a3"), ("b1", "b2", "b3")))))
    designs.append(("receipt_paste_B_shared_E_and_activation.json", dict(
        name="paste_B",
        blocks=cell_blocks() + cell_blocks(sfx="B", own_E=False),
        triples=[("a1", "a2", "a3")],
        q_specs={"q": Q, "r": R},
        shared_structure="shared MAXIMAL block E AND shared activation triple "
                         "(redundant enforcement copy)")))
    designs.append(("receipt_refuted_single_mediator.json", dict(
        name="refuted_single_mediator",
        blocks=[list(E1), ["t", "e10", "s1"], ["t", "e01", "s2"]],
        triples=[], q_specs={},
        shared_structure="one mediator atom cohabits both difference atoms "
                         "of E (3-loop)")))
    designs.append(("receipt_refuted_reused_n1.json", dict(
        name="refuted_reused_n1",
        blocks=[["a1", "u1", "p11"], ["a2", "v1", "p12"], ["u1", "v1", "w1"],
                ["a3", "n1", "p15"], ["w1", "m1", "p14"], ["m1", "n1", "t1"],
                ["w1", "m2", "p24"], ["m2", "n1", "t2"],
                ["t1", "e10", "s1"], ["t2", "e01", "s2"], list(E1)],
        triples=[], q_specs={},
        shared_structure="cascade 2 reuses n1 (4-loop)")))
    designs.append(("receipt_shared_q_nonmaximal_subalgebra.json", dict(
        name="shared_q_two_cascades",
        blocks=cell_blocks() + cell_blocks(sfx="B", E=E2, own_E=False) + [list(E2)],
        triples=[("a1", "a2", "a3")],
        q_specs={"q": Q, "r1": R, "r2": R2},
        ident=IDENT_Q, couplings=COUPLE_Q,
        shared_structure="shared NONMAXIMAL four-element subalgebra {0,q,q',1} "
                         "generated by q; q is a rank-2 element of TWO distinct "
                         "maximal 4-atom blocks E1, E2 (contrast: pastes A/B "
                         "share the maximal block E itself); shared activation "
                         "triple; each copy keeps its own mediator cascade",
        relations_hook=sharedq_hook)))
    designs.append(("receipt_shared_q_shared_mediators_refuted.json", dict(
        name="shared_q_shared_mediators",
        blocks=cell_blocks() + [["t1", "f10", "s1f"], ["t2", "f01", "s2f"],
                                list(E2)],
        triples=[], q_specs={},
        ident=IDENT_Q, couplings=COUPLE_Q,
        shared_structure="shared nonmaximal subalgebra {0,q,q',1} generated by "
                         "q, but ONE mediator pair (t1,t2) serving both "
                         "coordinate blocks")))
    designs.append(("receipt_refuted_bare_subalgebra_paste.json", dict(
        name="refuted_bare_subalgebra_paste",
        blocks=[list(E1), list(E2)],
        triples=[], q_specs={},
        ident=IDENT_Q, couplings=COUPLE_Q,
        shared_structure="MINIMAL CORE: two 4-atom Boolean blocks pasted along "
                         "the nonmaximal four-element subalgebra {0,q,q',1} "
                         "alone (no cell attached); shows the shared-q "
                         "latticehood failure is intrinsic to the subalgebra "
                         "paste, not to the mediator cascades")))
    return designs


# ---------------------------------------------------------------- receipts

def canonical(payload):
    return json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()


def compute_all():
    with open(os.path.abspath(__file__), "rb") as f:
        vsha = hashlib.sha256(f.read()).hexdigest()
    out = []
    for fname, kw in build_designs():
        p = audit_payload(**kw)
        p["verifier_sha256"] = vsha
        out.append((fname, p))
    return out


def emit():
    for fname, payload in compute_all():
        receipt = {
            "schema": SCHEMA,
            "schema_version": SCHEMA_VERSION,
            "generator": GENERATOR,
            "command": COMMAND,
            "emitted": EMIT_DATE,
            "payload_sha256": hashlib.sha256(canonical(payload)).hexdigest(),
            "payload": payload,
        }
        path = os.path.join(HERE, fname)
        with open(path, "w") as f:
            json.dump(receipt, f, indent=1, sort_keys=True)
            f.write("\n")
        print("wrote", fname, "payload_sha256=%s..." % receipt["payload_sha256"][:16])


def verify():
    ok = True
    for fname, payload in compute_all():
        path = os.path.join(HERE, fname)
        if not os.path.exists(path):
            print("MISSING ", fname)
            ok = False
            continue
        with open(path) as f:
            receipt = json.load(f)
        stored = receipt.get("payload")
        sha_stored = receipt.get("payload_sha256")
        sha_of_stored = hashlib.sha256(canonical(stored)).hexdigest()
        recomputed = json.loads(canonical(payload).decode())
        if sha_of_stored != sha_stored:
            print("CORRUPT ", fname, "(stored payload does not match its hash)")
            ok = False
        elif recomputed != stored:
            diff = [k for k in set(recomputed) | set(stored)
                    if recomputed.get(k) != stored.get(k)]
            print("MISMATCH", fname, "fields:", sorted(diff))
            ok = False
        else:
            print("MATCH   ", fname, "payload_sha256=%s..." % sha_stored[:16])
    print("VERIFY:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "--verify"
    if mode == "--emit":
        emit()
    elif mode == "--verify":
        sys.exit(verify())
    else:
        print(__doc__)
        sys.exit(2)
