"""Exhaustive single-window coarse-protocol search, |N| <= 6, k <= 3 contexts.

Question (design session, 2026-07-06): is Family I (elementary chains) plus
Family II (clique + odd-hole facets of the cross-context cell-exclusivity
graph) COMPLETE for coherent-unrealisable models at this scale, or does a
third mechanism (ELSE) exist?

Design decisions implemented (as handed off):
 1. Scope: outcomes n in 3..6, k in {2,3} contexts, each context a partition
    of N with >= 2 cells, protocols deduplicated up to S_N via lex-minimality
    of the (sorted) partition tuple over all permutations (early-abort test).
    Single-window coarse search; V = N (the abstract search realizes any
    quotiented variety as its own protocol on some N).
 2. Test objects: the coherence polytope C = {q >= 0 : per-context sums = 1,
    per-pair block-mass equalities} versus R = conv{phi(omega) : omega in N},
    phi(omega)_c = 1[omega in c]. R = C iff no separation; separation tested
    by (i) R's affine-hull equations against C's equality rowspace (linear
    algebra — C's affine hull is exactly {Eq = f} since the uniform-measure
    point is strictly positive), (ii) exact LPs maximizing each R-facet
    functional over C.
 3. Verdicts rational-certified both ways: ALL LPs are exact (Fraction
    simplex, Bland's rule); witnesses re-verified by direct substitution; no
    floating point anywhere.
 4. Families over V = N: Family I = all elementary chains (m >= 1 cells from
    distinct contexts, target = cell of an unused context or the empty
    target), kept iff pointwise-valid on N. Family II = clique inequalities
    (maximal cliques) and odd-hole inequalities (chordless induced odd cycles,
    length >= 5) of the cell-disjointness graph on all cells. ELSE iff some
    point of C satisfies every family member yet lies outside R. Separately,
    each R-facet violated by C is classified by membership in the cone
    generated by {families, C-equalities (+/-), coordinate nonnegativity}
    (an exact LP feasibility) — "in-cone" vs "exotic" is recorded
    independently of the F-subset-R verdict, as demanded.
 5. Calibration targets (must be rediscovered unprompted): the 3-outcome
    example (Family I / exclusivity), the RCD (Family I chain through a third
    context), and the minimal Family-II protocol (5 vs 6 outcomes — open
    datum this run settles).

Prediction ledger (logged BEFORE the run, design session):
  P1: ELSE is empty at n <= 6.
  P2: minimal Family-II protocol plausibly at 5-6 outcomes with k = 3
      (two C5-cells per context max; triangle-free forces k >= 3).
  P3: first ELSE entries expected at 7-8 outcomes (odd-antihole facets),
      out of scope here.

Usage: python3 commensurability_harness.py <n> [<k>]   (runs one (n,k) slice,
appends JSON-lines to commensurability_atlas_n<k>.jsonl and prints a summary)
"""
import sys
import json
from fractions import Fraction
from itertools import combinations, permutations, product

# ----------------------------------------------------------------------
# Exact simplex (maximize c.x st A_eq x = b_eq, A_ub x <= b_ub, x >= 0)
# ----------------------------------------------------------------------

def simplex_max(c, A_eq, b_eq, A_ub, b_ub):
    """Exact rational simplex (Bland). Maximize c.x st A_eq x = b_eq,
    A_ub x <= b_ub, x >= 0. Returns (status, value, x)."""
    F = Fraction
    n = len(c)
    nub = len(A_ub)
    rows, rhs = [], []
    for a, b in zip(A_eq, b_eq):
        rows.append([F(x) for x in a] + [F(0)] * nub)
        rhs.append(F(b))
    for i, (a, b) in enumerate(zip(A_ub, b_ub)):
        r = [F(x) for x in a] + [F(0)] * nub
        r[n + i] = F(1)
        rows.append(r)
        rhs.append(F(b))
    nv = n + nub
    m = len(rows)
    for i in range(m):
        if rhs[i] < 0:
            rows[i] = [-x for x in rows[i]]
            rhs[i] = -rhs[i]
    ncols = nv + m
    T = [rows[i] + [F(1) if j == i else F(0) for j in range(m)] + [rhs[i]]
         for i in range(m)]
    basis = [nv + i for i in range(m)]

    def pivot(r, col, obj):
        p = T[r][col]
        T[r] = [x / p for x in T[r]]
        for i in range(m):
            if i != r and T[i][col] != 0:
                f0 = T[i][col]
                T[i] = [a - f0 * b for a, b in zip(T[i], T[r])]
        if obj is not None and obj[col] != 0:
            f0 = obj[col]
            for j in range(ncols + 1):
                obj[j] -= f0 * T[r][j]
        basis[r] = col

    def optimize(obj, allowed_cols):
        while True:
            col = -1
            for j in range(allowed_cols):
                if obj[j] > 0:
                    col = j
                    break
            if col == -1:
                return True
            r, best = -1, None
            for i in range(m):
                if T[i][col] > 0:
                    ratio = T[i][-1] / T[i][col]
                    if best is None or ratio < best or \
                       (ratio == best and basis[i] < basis[r]):
                        best, r = ratio, i
            if r == -1:
                return False
            pivot(r, col, obj)

    # Phase 1: minimize sum of artificials (maximize its negative).
    obj1 = [F(0)] * (ncols + 1)
    for i in range(m):
        for j in range(ncols + 1):
            obj1[j] += T[i][j]
    for j in range(nv, ncols):
        obj1[j] = F(0)
    optimize(obj1, nv)          # phase 1 is bounded; unbounded impossible
    if obj1[-1] != 0:
        return ('infeasible', None, None)
    # drive remaining artificials out where possible
    for i in range(m):
        if basis[i] >= nv:
            col = next((j for j in range(nv) if T[i][j] != 0), None)
            if col is not None:
                pivot(i, col, obj1)
    # Phase 2
    cvec = [F(x) for x in c] + [F(0)] * nub + [F(0)] * m
    obj2 = list(cvec) + [F(0)]
    for i in range(m):
        b = basis[i]
        if b < ncols and obj2[b] != 0:
            f0 = obj2[b]
            for j in range(ncols + 1):
                obj2[j] -= f0 * T[i][j]
    if not optimize(obj2, nv):
        return ('unbounded', None, None)
    x = [F(0)] * ncols
    for i in range(m):
        if basis[i] < ncols:
            x[basis[i]] = T[i][-1]
    val = sum(cv * xv for cv, xv in zip(cvec[:nv], x[:nv]))
    return ('optimal', val, x[:n])

# ----------------------------------------------------------------------
# Linear algebra over Fractions
# ----------------------------------------------------------------------

def rref(mat):
    """Reduced row echelon form; returns (rref_rows, pivot_cols)."""
    M = [list(map(Fraction, row)) for row in mat]
    rows, cols = len(M), (len(M[0]) if M else 0)
    piv_cols, r = [], 0
    for c in range(cols):
        pr = next((i for i in range(r, rows) if M[i][c] != 0), None)
        if pr is None:
            continue
        M[r], M[pr] = M[pr], M[r]
        M[r] = [x / M[r][c] for x in M[r]]
        for i in range(rows):
            if i != r and M[i][c] != 0:
                f = M[i][c]
                M[i] = [a - f * b for a, b in zip(M[i], M[r])]
        piv_cols.append(c)
        r += 1
        if r == rows:
            break
    return M[:r], piv_cols

def in_rowspace(rref_rows, piv_cols, vec):
    """Is vec in the rowspace given by an rref basis (augmented consistent)?"""
    v = list(map(Fraction, vec))
    for row, pc in zip(rref_rows, piv_cols):
        if v[pc] != 0:
            f = v[pc]
            v = [a - f * b for a, b in zip(v, row)]
    return all(x == 0 for x in v)

# ----------------------------------------------------------------------
# Protocol machinery
# ----------------------------------------------------------------------

def set_partitions(n):
    """All partitions of {0..n-1} with >= 2 cells, as tuples of frozensets."""
    def rec(elems):
        if not elems:
            yield []
            return
        first, rest = elems[0], elems[1:]
        for sub in rec(rest):
            for i in range(len(sub)):
                yield sub[:i] + [sub[i] | {first}] + sub[i + 1:]
            yield sub + [{first}]
    out = []
    for p in rec(list(range(n))):
        if len(p) >= 2:
            out.append(tuple(sorted((frozenset(c) for c in p),
                                    key=lambda s: sorted(s))))
    return sorted(out, key=lambda p: [sorted(c) for c in p])

def canon_key(partition):
    return tuple(tuple(sorted(c)) for c in partition)

def apply_perm(partition, perm):
    cells = [frozenset(perm[x] for x in c) for c in partition]
    return tuple(sorted(cells, key=lambda s: sorted(s)))

def canonical_protocols(n, k):
    """Lex-minimal representatives of S_n-orbits of k-subsets of partitions."""
    parts = set_partitions(n)
    pid = {canon_key(p): i for i, p in enumerate(parts)}
    perms = list(permutations(range(n)))
    # precompute permutation action on partition ids
    action = []
    for perm in perms:
        action.append([pid[canon_key(apply_perm(p, perm))] for p in parts])
    out = []
    for combo in combinations(range(len(parts)), k):
        key = combo  # sorted tuple of ids
        minimal = True
        for act in action:
            mapped = tuple(sorted(act[i] for i in combo))
            if mapped < key:
                minimal = False
                break
        if minimal:
            out.append([parts[i] for i in combo])
    return out

def build_protocol(n, contexts):
    """Cells, equality system (E, f), R-vertices, uniform point."""
    cells = []          # list of frozensets
    ctx_of = []         # context index per cell
    for ci, p in enumerate(contexts):
        for c in p:
            cells.append(c)
            ctx_of.append(ci)
    d = len(cells)
    E, f = [], []
    # per-context normalization
    for ci in range(len(contexts)):
        row = [Fraction(1) if ctx_of[j] == ci else Fraction(0) for j in range(d)]
        E.append(row)
        f.append(Fraction(1))
    # pairwise block-mass equalities (blocks = components of cell-intersection graph)
    for a, b in combinations(range(len(contexts)), 2):
        ia = [j for j in range(d) if ctx_of[j] == a]
        ib = [j for j in range(d) if ctx_of[j] == b]
        # union-find over ia+ib by nonempty intersection
        parent = {j: j for j in ia + ib}
        def find(x):
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x
        for j1 in ia:
            for j2 in ib:
                if cells[j1] & cells[j2]:
                    r1, r2 = find(j1), find(j2)
                    if r1 != r2:
                        parent[r1] = r2
        blocks = {}
        for j in ia + ib:
            blocks.setdefault(find(j), []).append(j)
        for blk in blocks.values():
            row = [Fraction(0)] * d
            for j in blk:
                row[j] = Fraction(1) if ctx_of[j] == a else Fraction(-1)
            if any(x != 0 for x in row):
                E.append(row)
                f.append(Fraction(0))
    # R vertices
    verts = []
    for w in range(n):
        verts.append([Fraction(1) if w in cells[j] else Fraction(0)
                      for j in range(d)])
    return cells, ctx_of, E, f, verts

# ----------------------------------------------------------------------
# Families over V = N
# ----------------------------------------------------------------------

def family_I(n, cells, ctx_of, k):
    """Elementary chains, pointwise-valid on N.
    Inequality: sum q(c_t) - q(T) <= m-1 (T=None: sum <= m-1)."""
    d = len(cells)
    ineqs = set()
    by_ctx = {}
    for j in range(d):
        by_ctx.setdefault(ctx_of[j], []).append(j)
    ctxs = sorted(by_ctx)
    for m in range(1, k + 1):
        for chosen_ctxs in combinations(ctxs, m):
            for combo in product(*[by_ctx[c] for c in chosen_ctxs]):
                rest = [j for j in range(d) if ctx_of[j] not in chosen_ctxs]
                for T in [None] + rest:
                    ok = True
                    for w in range(n):
                        lhs = sum(1 for j in combo if w in cells[j])
                        rhs = (m - 1) + (1 if (T is not None and w in cells[T]) else 0)
                        if lhs > rhs:
                            ok = False
                            break
                    if ok:
                        a = [Fraction(0)] * d
                        for j in combo:
                            a[j] += 1
                        if T is not None:
                            a[T] -= 1
                        ineqs.add((tuple(a), Fraction(m - 1)))
    return [(list(a), b) for a, b in ineqs]

def family_II(n, cells, ctx_of):
    """Clique + odd-hole inequalities of the cell-disjointness graph."""
    d = len(cells)
    adj = [[bool(i != j and not (cells[i] & cells[j])) for j in range(d)]
           for i in range(d)]
    ineqs = set()
    # maximal cliques (Bron-Kerbosch)
    cliques = []
    def bk(R, P, X):
        if not P and not X:
            cliques.append(R)
            return
        for v in list(P):
            bk(R | {v}, {u for u in P if adj[v][u]}, {u for u in X if adj[v][u]})
            P = P - {v}
            X = X | {v}
    bk(set(), set(range(d)), set())
    for Q in cliques:
        if len(Q) >= 2:
            a = [Fraction(1) if j in Q else Fraction(0) for j in range(d)]
            ineqs.add((tuple(a), Fraction(1)))
    # odd holes: chordless induced cycles of odd length >= 5
    cliq = [(list(a), b) for a, b in ineqs]
    holes = set()
    for L in range(5, d + 1, 2):
        for S in combinations(range(d), L):
            deg = [sum(1 for j in S if adj[i][j]) for i in S]
            if any(dg != 2 for dg in deg):
                continue
            # connected 2-regular = single cycle
            seen = {S[0]}
            frontier = [S[0]]
            while frontier:
                v = frontier.pop()
                for u in S:
                    if adj[v][u] and u not in seen:
                        seen.add(u)
                        frontier.append(u)
            if len(seen) == L:
                a = [Fraction(1) if j in S else Fraction(0) for j in range(d)]
                holes.add((tuple(a), Fraction((L - 1) // 2)))
    return cliq, [(list(a), b) for a, b in holes]

# ----------------------------------------------------------------------
# R geometry: affine hull equations + facets (exact)
# ----------------------------------------------------------------------

def r_hull_and_facets(verts):
    """Returns (hull_eqs, facets): hull_eqs = list of (u, u.v0) with u
    orthogonal to the hull directions; facets = list of (a, b) ambient lifts,
    valid a.v <= b on all verts with equality on a facet."""
    d = len(verts[0])
    v0 = verts[0]
    diffs = [[v[j] - v0[j] for j in range(d)] for v in verts[1:]]
    B, pivots = rref(diffs) if diffs else ([], [])
    r = len(B)  # dim of R
    # hull equations: null space of span(diffs): vectors u with u.diff = 0.
    # compute basis of orthogonal complement via rref of B as rows -> free vars
    hull_eqs = []
    piv = set(pivots)
    for free in range(d):
        if free in piv:
            continue
        u = [Fraction(0)] * d
        u[free] = Fraction(1)
        for row, pc in zip(B, pivots):
            u[pc] = -row[free]
        rhs = sum(u[j] * v0[j] for j in range(d))
        hull_eqs.append((u, rhs))
    # coordinates of vertices in hull basis: y_i solves via pivot columns of B
    coords = []
    for v in verts:
        w = [v[j] - v0[j] for j in range(d)]
        y = [Fraction(0)] * r
        # since B is rref of diffs (row space), solve w = y . B  (w in rowspace)
        ww = list(w)
        for i, pc in enumerate(pivots):
            y[i] = ww[pc]
            if y[i] != 0:
                ww = [a - y[i] * b for a, b in zip(ww, B[i])]
        coords.append(y)
    # facets of conv(coords) in R^r by brute force over vertex subsets
    facets = []
    if r == 0:
        return hull_eqs, facets
    seen = set()
    for S in combinations(range(len(coords)), r):
        pts = [coords[i] for i in S]
        # hyperplane through pts: solve for (g, h): g.p = h; fix scale via rref
        M = [pts[i] + [Fraction(1)] for i in range(r)]  # g.p - h = 0 -> [p,1].[g,-h]=0
        R2, piv2 = rref(M)
        if len(R2) < r:
            continue  # affinely dependent
        # null vector of M (r x (r+1)): one free var
        pivset = set(piv2)
        free = next(c for c in range(r + 1) if c not in pivset)
        gh = [Fraction(0)] * (r + 1)
        gh[free] = Fraction(1)
        for row, pc in zip(R2, piv2):
            gh[pc] = -row[free]
        g, h = gh[:r], -gh[r]
        vals = [sum(gi * yi for gi, yi in zip(g, y)) for y in coords]
        for sgn in (1, -1):
            gg = [sgn * x for x in g]
            hh = sgn * h
            vv = [sgn * x for x in vals]
            # supporting from this side: all vertices weakly below, some strictly
            if max(vv) == hh and any(x < hh for x in vv):
                # lift to ambient: a.q = g . y(q), y_i(q) recovered via pivots:
                # y_i = (q - v0)[pivot col path]; from coords computation:
                # y_i = (q - v0)[pivots[i]] adjusted by earlier rows -> build map
                a_amb = [Fraction(0)] * d
                # y as affine functions: replicate the coords loop symbolically
                # w = q - v0 ; iterate: y_i = w[pc_i]; w -= y_i * B[i]
                # => y_i = linear in q. Build incrementally with matrices.
                W = [[Fraction(1) if jj == ii else Fraction(0) for jj in range(d)]
                     for ii in range(d)]  # rows: w_j as functions of q (minus v0 handled via const)
                consts = [-v0[ii] for ii in range(d)]
                ycoef = []
                yconst = []
                for i2, pc in enumerate(pivots):
                    yc = list(W[pc])
                    y0c = consts[pc]
                    ycoef.append(yc)
                    yconst.append(y0c)
                    for jj in range(d):
                        if B[i2][jj] != 0:
                            W[jj] = [wa - B[i2][jj] * ya for wa, ya in zip(W[jj], yc)]
                            consts[jj] -= B[i2][jj] * y0c
                bb = hh
                for gi, yc, y0c in zip(gg, ycoef, yconst):
                    for jj in range(d):
                        a_amb[jj] += gi * yc[jj]
                    bb -= gi * y0c
                key = (tuple(a_amb), bb)
                if key not in seen:
                    seen.add(key)
                    facets.append((a_amb, bb))
    return hull_eqs, facets

# ----------------------------------------------------------------------
# Per-protocol analysis
# ----------------------------------------------------------------------

def analyze(n, k, contexts):
    cells, ctx_of, E, f, verts = build_protocol(n, contexts)
    d = len(cells)
    # rowspace of [E | f]
    aug = [row + [rhs] for row, rhs in zip(E, f)]
    Rr, Rp = rref(aug)
    hull_eqs, facets = r_hull_and_facets(verts)

    def max_over(c_obj, extra_ub):
        st, val, x = simplex_max(c_obj, E, f,
                                 [a for a, _ in extra_ub], [b for _, b in extra_ub])
        assert st == 'optimal', st
        return val, x

    # ---- separation test: C vs R ----
    sep_witness, sep_facet = None, None
    for u, rhs in hull_eqs:
        if in_rowspace(Rr, Rp, list(u) + [rhs]):
            continue        # C's own equalities force this hull equation
        val, x = max_over(list(u), [])
        if val != rhs:
            sep_witness, sep_facet = x, ('hull', u, rhs)
            break
        val2, x2 = max_over([-ui for ui in u], [])
        if -val2 != rhs:
            sep_witness, sep_facet = x2, ('hull', u, rhs)
            break
    if sep_witness is None:
        for a, b in facets:
            val, x = max_over(a, [])
            if val > b:
                sep_witness, sep_facet = x, ('facet', a, b)
                break
    if sep_witness is None:
        return {'verdict': 'R_EQUALS_C'}

    # ---- families ----
    F1 = family_I(n, cells, ctx_of, k)
    F2c, F2h = family_II(n, cells, ctx_of)
    F2 = F2c + F2h

    def subset_R(extra):
        """Is C cut by `extra` inside R? Returns (True, None) or (False, witness, facet)."""
        for u, rhs in hull_eqs:
            val, x = max_over(u, extra)
            if val > rhs:
                return False, x, ('hull+', u, rhs)
            val2, x2 = max_over([-ui for ui in u], extra)
            if -val2 < rhs:
                return False, x2, ('hull-', u, rhs)
        for a, b in facets:
            val, x = max_over(a, extra)
            if val > b:
                return False, x, ('facet', a, b)
        return True, None, None

    # Family 0 = R's affine-hull equations (integer pointwise syzygies),
    # imposable as inequality pairs.
    F0 = []
    for u, rhs in hull_eqs:
        F0.append((list(u), rhs))
        F0.append(([-t for t in u], -rhs))

    ok1, w1, fc1 = subset_R(F1)
    if ok1:
        verdict = 'FAMILY_I_COMPLETE'
        else_witness = None
    else:
        okc, wc, fcc = subset_R(F1 + F2c)
        if okc:
            verdict = 'NEED_CLIQUES_COMPLETE'
            else_witness = None
            ok12 = True
        else:
            ok12, w12, fc12 = subset_R(F1 + F2)
        if okc:
            pass
        elif ok12:
            verdict = 'NEED_ODDHOLES_COMPLETE'
            else_witness = None
        else:
            ok012, w012, fc012 = subset_R(F0 + F1 + F2)
            if ok012:
                verdict = 'NEED_SYZYGY_COMPLETE'
                else_witness = (w12, fc12)   # the syzygy-violating witness
            else:
                verdict = 'ELSE'
                else_witness = (w012, fc012)

    # ---- cone-membership of the separating R-facet (exotic vs in-cone) ----
    cone_flag = None
    if sep_facet is not None and sep_facet[0] == 'facet':
        a, b = sep_facet[1], sep_facet[2]
        fams = F1 + F2
        nf, ne = len(fams), len(Rr)
        # a = sum l_i fam_a_i + sum m_j Erow_j - nu ; b >= sum l_i fam_b_i + sum m_j f_j
        # variables: l >= 0 (nf), m free = mp - mn (2*ne), nu >= 0 (d), s >= 0 slack for b
        nv = nf + 2 * ne + d + 1
        Aeq, beq = [], []
        Erows = [row[:-1] for row in Rr]
        frhs = [row[-1] for row in Rr]
        for j in range(d):
            row = [Fraction(0)] * nv
            for i2, (fa, fb) in enumerate(fams):
                row[i2] = fa[j]
            for j2 in range(ne):
                row[nf + j2] = Erows[j2][j]
                row[nf + ne + j2] = -Erows[j2][j]
            row[nf + 2 * ne + j] = Fraction(-1)
            Aeq.append(row)
            beq.append(a[j])
        row = [Fraction(0)] * nv
        for i2, (fa, fb) in enumerate(fams):
            row[i2] = fb
        for j2 in range(ne):
            row[nf + j2] = frhs[j2]
            row[nf + ne + j2] = -frhs[j2]
        row[nf + 2 * ne + d] = Fraction(1)   # slack: sum + s = b  => sum <= b
        Aeq.append(row)
        beq.append(b)
        st, _, _ = simplex_max([Fraction(0)] * nv, Aeq, beq, [], [])
        cone_flag = 'in-cone' if st == 'optimal' else 'exotic'

    return {'verdict': verdict,
            'n': n, 'k': k,
            'contexts': [[sorted(c) for c in p] for p in contexts],
            'n_family_I': len(F1), 'n_family_II': len(F2),
            'sep_facet_cone': cone_flag,
            'else_witness': (None if else_witness is None else
                             [str(x) for x in else_witness[0]])}

# ----------------------------------------------------------------------

def main():
    n = int(sys.argv[1])
    ks = [int(sys.argv[2])] if len(sys.argv) > 2 else [2, 3]
    for k in ks:
        prots = canonical_protocols(n, k)
        tally = {}
        interesting = []
        out = open(f"commensurability_atlas_n{n}k{k}.jsonl", "w")
        for contexts in prots:
            res = analyze(n, k, contexts)
            v = res['verdict']
            tally[v] = tally.get(v, 0) + 1
            if v != 'R_EQUALS_C':
                out.write(json.dumps(res) + "\n")
                if v != 'FAMILY_I_COMPLETE':
                    interesting.append(res)
        out.close()
        print(f"n={n} k={k}: {len(prots)} canonical protocols; tally: {tally}")
        for r in interesting:
            print(f"  {r['verdict']}: contexts={r['contexts']}"
                  f" (|FI|={r['n_family_I']}, |FII|={r['n_family_II']},"
                  f" cone={r['sep_facet_cone']})")

if __name__ == '__main__':
    main()
