/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Patrick S. Mahon
-/
import Mathlib.MeasureTheory.Measure.AddContent
import Mathlib.MeasureTheory.OuterMeasure.OfAddContent
import Mathlib.MeasureTheory.MeasurableSpace.Basic
import Mathlib.Order.Filter.Cofinite
import Mathlib.Order.Hom.WithTopBot
import QuerySystem.QuerySystem

/-!
# Discriminability Foundations: SP1 Resolution

This file formalises the resolution of Stopping Point 1 (SP1) of the Observable
Dynamics Program: the question of whether the σ-algebra can be derived from
finitely-additive coherence conditions on a query system.

## Main results

* `finCofinMSpace`: The finite-cofinite measurable space on a countably infinite type.
* `fcContent`: The finitely-additive content on the finite-cofinite algebra assigning
  0 to finite sets and 1 to cofinite sets.
* `counterexampleQS`: A sequentially upper-directed query system with compatible
  finitely-additive contents that fails σ-additive extension. (Refutes the original
  witnessing conjecture — C1 of the tetralemma.)
* `QuerySystem.CompatibleContents`: Compatible family of finitely-additive contents.
* `QuerySystem.CollectivelyExhaustive`: The valuation-layer condition characterising
  coherent query systems.
* `sp1_extension`: Collectively exhaustive + compatible → σ-additive extension at
  every level.
* `sp1_necessity`: σ-additive extension → collectively exhaustive.
* `sp1_iff`: The equivalence — collective exhaustion is the exact characterisation
  of σ-additive extensibility.

## Architecture

The key separation is between two independent layers:
- **Index layer**: preorder, refinement maps, sequential upper-directedness.
- **Valuation layer**: contents, compatibility, collective exhaustion.

The counterexample shows these layers are independent: index-layer conditions cannot
force valuation-layer properties. The SP1 theorem gives the exact valuation-layer
characterisation.

## References

* `papers/discriminability_foundations/sp1_resolution_sketch.md`
* `papers/discriminability_foundations/discriminability_foundations_body.tex` §5
-/

open MeasureTheory Set
open scoped ENNReal

-- Use classical decidability throughout to avoid `Decidable` synthesis failures
open Classical in section

/-!
## Part I: The finite-cofinite algebra and the counterexample

We construct a sequentially upper-directed query system with compatible finitely-additive
contents that fails σ-additive extension. This refutes the original witnessing conjecture.
-/

section FinCofin

/-- The finite-cofinite measurable space on a type: measurable sets are those that are
    finite or have finite complement. This is the Boolean algebra generated by singletons. -/
def finCofinMSpace (α : Type*) : MeasurableSpace α :=
  MeasurableSpace.generateFrom {s : Set α | s.Finite ∨ sᶜ.Finite}

/-- The finite-cofinite collection is the collection used to generate `finCofinMSpace`. -/
def finCofinSets (α : Type*) : Set (Set α) := {s : Set α | s.Finite ∨ sᶜ.Finite}

/-- The finite-cofinite collection is a set semiring when the type is infinite. -/
lemma finCofinSets_isSetSemiring (α : Type*) [Infinite α] :
    IsSetSemiring (finCofinSets α) := by
  constructor
  · exact Or.inl finite_empty
  · intro s hs t ht
    simp only [finCofinSets, Set.mem_setOf_eq] at *
    cases hs with
    | inl hs => exact Or.inl (hs.subset inter_subset_left)
    | inr hs =>
      cases ht with
      | inl ht => exact Or.inl (ht.subset inter_subset_right)
      | inr ht => exact Or.inr (compl_inter s t ▸ hs.union ht)
  · intro s hs t ht
    simp only [finCofinSets, Set.mem_setOf_eq] at *
    have hdiff : (s \ t).Finite ∨ (s \ t)ᶜ.Finite := by
      cases hs with
      | inl hs => exact Or.inl (hs.subset diff_subset)
      | inr hs =>
        cases ht with
        | inl ht => exact Or.inr (by rw [compl_diff]; exact ht.union hs)
        | inr ht => exact Or.inl (ht.subset (diff_subset_compl s t))
    exact ⟨{s \ t},
      by simp only [Finset.coe_singleton, Set.singleton_subset_iff]; exact hdiff,
      by simp [Set.pairwiseDisjoint_singleton],
      by simp⟩

/-- The finitely-additive content on the finite-cofinite algebra:
    assigns 0 to finite sets and 1 to cofinite sets.

    On an infinite type, finite and cofinite are mutually exclusive, so this is
    well-defined. Finite additivity holds: disjoint sets in the algebra can only
    be (finite, finite) or (finite, cofinite) pairs — never (cofinite, cofinite). -/
noncomputable def fcContent (α : Type*) [Infinite α] :
    AddContent ℝ≥0∞ (finCofinSets α) where
  toFun s := if sᶜ.Finite then 1 else 0
  empty' := by
    simp only [compl_empty]
    rw [if_neg Set.infinite_univ.not_finite]
  sUnion' I hI_ss hI_dis hI_mem := by
    classical
    simp only [finCofinSets, Set.mem_setOf_eq] at hI_mem hI_ss
    -- Key auxiliary: on an infinite type, finite and cofinite are exclusive.
    have fin_imp_cof_inf : ∀ s : Set α, s.Finite → ¬sᶜ.Finite := by
      intro s hs hsc
      exact Set.infinite_univ.not_finite (Set.union_compl_self s ▸ hs.union hsc)
    -- Key auxiliary: two distinct disjoint cofinite sets cannot coexist on an infinite type.
    have no_two_cof : ∀ u ∈ I, ∀ v ∈ I, u ≠ v →
        ¬((u : Set α)ᶜ.Finite ∧ (v : Set α)ᶜ.Finite) := by
      intro u hu v hv huv ⟨huc, hvc⟩
      have hdisj : Disjoint u v :=
        hI_dis (Finset.mem_coe.mpr hu) (Finset.mem_coe.mpr hv) (by simpa using huv)
      rw [Set.disjoint_iff_inter_eq_empty] at hdisj
      exact Set.infinite_univ.not_finite
        (show (Set.univ : Set α).Finite by
          rw [show (Set.univ : Set α) = uᶜ ∪ vᶜ from by
                simp [← Set.compl_inter, hdisj]]
          exact huc.union hvc)
    rcases hI_mem with hfin | hcofin
    · -- Union is finite → every member is finite → all toFun values are 0
      -- Since u ⊆ ⋃₀ ↑I and ⋃₀ ↑I is finite, u is finite, so uᶜ is infinite.
      have hall_not_cof : ∀ u ∈ I, ¬(u : Set α)ᶜ.Finite :=
        fun u hu => fin_imp_cof_inf u (hfin.subset
          (Set.subset_sUnion_of_mem (Finset.mem_coe.mpr hu)))
      -- ⋃₀ ↑I is finite, so (⋃₀ ↑I)ᶜ is infinite
      have hunion_not_cof : ¬(⋃₀ ↑I)ᶜ.Finite := fin_imp_cof_inf _ hfin
      rw [if_neg hunion_not_cof]
      exact (Finset.sum_eq_zero (fun u hu => if_neg (hall_not_cof u hu))).symm
    · -- Union is cofinite → exactly one member is cofinite → sum = 1
      -- Step 1: At least one member is cofinite.
      -- If all were finite, ⋃₀ ↑I = ⋃ of finitely many finite sets = finite,
      -- but its complement is finite (hcofin), so univ would be finite. Contradiction.
      have hex_cof : ∃ w ∈ I, (w : Set α)ᶜ.Finite := by
        by_contra hall_fin
        push_neg at hall_fin
        -- All members of I are finite, so ⋃₀ ↑I is a finite union of finite sets = finite
        have hunion_fin : (⋃₀ (I : Set (Set α))).Finite :=
          Set.Finite.sUnion (Finset.finite_toSet I)
            (fun u hu => (hI_ss hu).resolve_right (hall_fin u (Finset.mem_coe.mp hu)))
        exact fin_imp_cof_inf _ hunion_fin hcofin
      -- Step 2: Exactly one member is cofinite (by no_two_cof).
      obtain ⟨w, hw, hwc⟩ := hex_cof
      have huniq : ∀ u ∈ I, (u : Set α)ᶜ.Finite → u = w := by
        intro u hu huc
        by_contra huneq
        exact no_two_cof u hu w hw huneq ⟨huc, hwc⟩
      -- Step 3: Rewrite the sum using sum_eq_single.
      rw [if_pos hcofin]
      rw [Finset.sum_eq_single w
        (by intro u hu huw
            simp only [if_neg (fun huc => no_two_cof u hu w hw huw ⟨huc, hwc⟩)])
        (by intro hw'; exact absurd hw (hw'))]
      simp [hwc]

end FinCofin

/-!
## Part II: The counterexample query system

Index: WithTop ℕ (= ℕ ∪ {⊤}), sequentially upper-directed.
All outcome spaces: ℚ with the finite-cofinite algebra.
All refinement maps: identity.
All contents: fcContent ℚ.
This satisfies CompatibleContents but fails σ-additive extension.
-/

section Counterexample

/-- The counterexample query system. Index set is WithTop ℕ so that every sequence
    has an upper bound (⊤ is always an upper bound). -/
noncomputable def counterexampleQS : QuerySystem where
  ι := WithTop ℕ
  q _ := { Outcome := ℚ, instMeas := finCofinMSpace ℚ }
  le i j := i ≤ j
  π _ := { π := id, measurable_π := @measurable_id ℚ (finCofinMSpace ℚ) }
  le_refl _ := le_refl _
  le_trans h1 h2 := le_trans h1 h2
  π_refl _ := rfl
  π_trans _ _ := rfl

/-- The counterexample is sequentially upper-directed: ⊤ is a universal upper bound
    in WithTop ℕ. -/
lemma counterexampleQS_seqUpperDir :
    counterexampleQS.SequentiallyUpperDirected := by
  intro u
  exact ⟨(⊤ : WithTop ℕ), fun n => le_top⟩

/-- The key failure: the decreasing sequence E_n = ℚ \ {q_1,...,q_n}
    has empty intersection but each E_n is cofinite, so fcContent(E_n) = 1 for all n.
    No witnessing query exists anywhere in the counterexample system.

    We prove this indirectly: the complement sets F_n = {q 0, ..., q n} are finite
    (content 0) and their union is all of ℚ (content 1). σ-subadditivity would force
    1 ≤ ∑' n, 0 = 0, a contradiction.

    TODO (Layer 0): Complete once fcContent.sUnion' is proved. -/
lemma fcContent_not_sigmaSubadditive :
    ¬ (fcContent ℚ).IsSigmaSubadditive := by
  intro h
  obtain ⟨q, hq_surj⟩ := exists_surjective_nat ℚ
  -- F n = {q 0, ..., q n}: finite sets whose union is ℚ
  let F : ℕ → Set ℚ := fun n => {x | ∃ k ≤ n, x = q k}
  have hF_mem : ∀ n, F n ∈ finCofinSets ℚ := by
    intro n
    apply Or.inl
    -- F n = image of Iic n under q, which is finite
    apply Set.Finite.subset (Set.finite_Iic n |>.image q)
    intro x ⟨k, hk, hxk⟩
    exact ⟨k, Set.mem_Iic.mpr hk, hxk.symm⟩
  have hUnion_eq : (⋃ n, F n) = Set.univ := by
    ext x
    simp only [Set.mem_iUnion, Set.mem_univ, iff_true, F]
    obtain ⟨n, hn⟩ := hq_surj x
    exact ⟨n, n, le_refl n, hn.symm⟩
  have hUnion_mem : (⋃ n, F n) ∈ finCofinSets ℚ := by
    rw [hUnion_eq]; exact Or.inr (by simp)
  -- Each F n is finite (we proved this in hF_mem), so fcContent ℚ (F n) = 0
  have hF_val : ∀ n, fcContent ℚ (F n) = 0 := by
    intro n
    show (if (F n)ᶜ.Finite then (1 : ℝ≥0∞) else 0) = 0
    have hFn_fin : (F n).Finite := (hF_mem n).elim id (fun hFnc =>
      Set.Finite.subset (Set.finite_Iic n |>.image q) (fun x hx => by
        simp only [F, Set.mem_setOf_eq] at hx
        obtain ⟨k, hk, hxk⟩ := hx
        exact ⟨k, Set.mem_Iic.mpr hk, hxk.symm⟩))
    exact if_neg (fun hFnc =>
      Set.infinite_univ.not_finite (Set.union_compl_self (F n) ▸ hFn_fin.union hFnc))
  -- The union is univ, which has empty complement: fcContent ℚ univ = 1
  have hUnion_val : fcContent ℚ (⋃ n, F n) = 1 := by
    rw [hUnion_eq]
    show (if (Set.univ : Set ℚ)ᶜ.Finite then (1 : ℝ≥0∞) else 0) = 1
    simp [Set.compl_univ]
  -- σ-subadditivity gives 1 ≤ ∑' n, 0 = 0: contradiction
  have hineq := h hF_mem hUnion_mem
  rw [hUnion_val] at hineq
  simp [hF_val] at hineq

end Counterexample

end -- close Classical section

/-!
## Part III: Compatible contents, normalization, and collective exhaustion
-/

namespace QuerySystem

variable (S : QuerySystem.{u, v})

/-- A compatible family of finitely-additive contents.

    This is the finitely-additive analogue of `CompatibleMarginals`. Each ℓ_Q is
    an `AddContent` (not a `Measure`), and compatibility says the content of any
    event at a coarser level equals the content of its preimage at any finer level. -/
def CompatibleContents
    (ν : ∀ i : S.ι, AddContent ℝ≥0∞ {s : Set (S.q i).Outcome | MeasurableSet s}) : Prop :=
  ∀ {i j : S.ι} (hij : S.le i j)
    (A : Set (S.q i).Outcome) (hA : MeasurableSet A),
    ν i A = ν j ((S.π hij).π ⁻¹' A)

/-- Collectively exhaustive: the valuation-layer condition characterising coherent
    query systems.

    For every level Q and every decreasing sequence of measurable events shrinking to
    ∅, some finer level Q' witnesses the convergence: the content of the preimage
    sequence at Q' converges to 0. By compatibility this forces convergence at Q.

    This is the exact condition that distinguishes query systems modeling coherent
    worlds from those that do not. A system failing this contains an observer who
    assigns persistent mass to events that vanish everywhere in the refinement order. -/
def CollectivelyExhaustive
    (ν : ∀ i : S.ι, AddContent ℝ≥0∞ {s : Set (S.q i).Outcome | MeasurableSet s}) : Prop :=
  ∀ (i : S.ι)
    (E : ℕ → Set (S.q i).Outcome)
    (_ : ∀ n, MeasurableSet (E n))
    (_ : ∀ n, E (n + 1) ⊆ E n)
    (_ : ⋂ n, E n = ∅),
    ∃ j : S.ι, ∃ hij : S.le i j,
      Filter.Tendsto
        (fun n => ν j ((S.π hij).π ⁻¹' E n))
        Filter.atTop (nhds 0)

/-- A normalized compatible family of finitely-additive contents: the correct domain
    for the SP1 theorem.

    Bundles three conditions that must travel together:
    - `ν`: a finitely-additive content at each level
    - `compat`: compatibility under refinement maps
    - `norm`: each content assigns total mass 1 to the full outcome space

    Normalization is not an assumption smuggled in to force σ-additivity — the
    counterexample (`fcContent`) is normalized and fails σ-additivity. Normalization
    correctly scopes the theorem to probability-valued contents, which is the domain
    of de Finetti's original question. It provides the finiteness condition
    (`ν i Set.univ ≠ ∞`) needed for the `sp1_necessity` direction. -/
structure NormalizedCompatibleContents (S : QuerySystem.{u, v}) where
  /-- The family of contents, one per level. -/
  ν      : ∀ i : S.ι, AddContent ℝ≥0∞ {s : Set (S.q i).Outcome | MeasurableSet s}
  /-- Compatibility: coarser content equals pullback of finer content. -/
  compat : S.CompatibleContents ν
  /-- Normalization: each content is a probability content. -/
  norm   : ∀ i : S.ι, ν i Set.univ = 1

/-- The collection of all measurable sets forms a set ring. -/
lemma isSetRing_measurableSets (α : Type*) [MeasurableSpace α] :
    IsSetRing {s : Set α | MeasurableSet s} := by
  constructor
  · exact MeasurableSet.empty
  · intro s t hs ht; exact hs.union ht
  · intro s t hs ht; exact hs.diff ht

/-- Every event has finite content in a normalized family. This is the finiteness
    condition needed for the σ-additivity argument.

    Proof: ν i A ≤ ν i univ = 1 < ∞ by monotonicity of AddContent on a set semiring. -/
lemma NormalizedCompatibleContents.ne_top
    (P : S.NormalizedCompatibleContents)
    (i : S.ι) (A : Set (S.q i).Outcome) (hA : MeasurableSet A) :
    P.ν i A ≠ ∞ := by
  have hring := isSetRing_measurableSets (S.q i).Outcome
  have hle : P.ν i A ≤ P.ν i Set.univ :=
    addContent_mono hring.isSetSemiring hA MeasurableSet.univ (Set.subset_univ _)
  rw [P.norm i] at hle
  exact ne_top_of_le_ne_top (by norm_num) hle

/-!
## Part IV: The SP1 theorem
-/

/-- **(SP1 → Extension)** For a normalized compatible family, collective exhaustion
    implies σ-additive extension at every level.

    Proof:
    1. Fix level i and a decreasing sequence E_n ↘ ∅ in the measurable sets.
    2. Collective exhaustion gives j ≥ i with ν j (π⁻¹(E_n)) → 0.
    3. Compatibility: ν i (E_n) = ν j (π⁻¹(E_n)) → 0.
    4. So ν i is continuous at ∅ (= `IsSigmaSubadditive` on the σ-algebra).
    5. By `AddContent.measure` (Carathéodory), ν i extends to a σ-additive measure
       on the full σ-algebra generated by the measurable sets.

    The key Mathlib dependency is `addContent_iUnion_eq_sum_of_tendsto_zero`, which
    converts continuity at ∅ into σ-additivity, combined with `AddContent.measure`
    for the Carathéodory extension step. -/
theorem sp1_extension
    (P : S.NormalizedCompatibleContents)
    (exhaust : S.CollectivelyExhaustive P.ν)
    (i : S.ι) :
    ∃ μ : Measure (S.q i).Outcome,
      ∀ (A : Set (S.q i).Outcome), MeasurableSet A → μ A = P.ν i A := by
  -- Step 1: derive continuity at ∅ for ν i from collective exhaustion + compatibility.
  -- For any antitone E_n ↘ ∅: collective exhaustion gives j and ν j (π⁻¹ E_n) → 0;
  -- compatibility gives ν i E_n = ν j (π⁻¹ E_n) → 0.
  have hcont : ∀ (E : ℕ → Set (S.q i).Outcome),
      (∀ n, MeasurableSet (E n)) → (∀ n, E (n+1) ⊆ E n) → (⋂ n, E n = ∅) →
      Filter.Tendsto (fun n => P.ν i (E n)) Filter.atTop (nhds 0) := by
    intro E hE_meas hE_anti hE_empty
    obtain ⟨j, hij, htend⟩ := exhaust i E hE_meas hE_anti hE_empty
    have hcompat : ∀ n, P.ν i (E n) = P.ν j ((S.π hij).π ⁻¹' E n) :=
      fun n => P.compat hij (E n) (hE_meas n)
    simp_rw [hcompat]
    exact htend
  -- Step 2: continuity at ∅ + normalization → IsSigmaSubadditive.
  -- We apply addContent_iUnion_eq_sum_of_tendsto_zero (IsSetRing, ne_top, continuity at ∅)
  -- to get σ-additivity, then isSigmaSubadditive_of_addContent_iUnion_eq_tsum.
  have hring : IsSetRing {s : Set (S.q i).Outcome | MeasurableSet s} :=
    isSetRing_measurableSets _
  have hne_top : ∀ s ∈ ({s : Set (S.q i).Outcome | MeasurableSet s}), P.ν i s ≠ ∞ :=
    fun s hs => NormalizedCompatibleContents.ne_top S P i s hs
  have hsubadd : (P.ν i).IsSigmaSubadditive :=
    isSigmaSubadditive_of_addContent_iUnion_eq_tsum hring
      (addContent_iUnion_eq_sum_of_tendsto_zero hring (P.ν i) hne_top
        (fun E hE_mem hE_anti hE_empty =>
          hcont E hE_mem (fun n => hE_anti (Nat.le_succ n)) hE_empty))
  -- Step 3: Carathéodory extension via AddContent.measure.
  -- generateFrom_measurableSet: generateFrom {s | MeasurableSet s} = instMeas
  have hC_gen : (S.q i).instMeas = MeasurableSpace.generateFrom
      {s : Set (S.q i).Outcome | MeasurableSet s} :=
    (MeasurableSpace.generateFrom_measurableSet (α := (S.q i).Outcome)).symm
  exact ⟨(P.ν i).measure hring.isSetSemiring hC_gen.le hsubadd,
         fun A hA => AddContent.measure_eq (P.ν i) hring.isSetSemiring hC_gen hsubadd hA⟩

/-- **(Extension → SP1)** For a normalized compatible family, σ-additive extension
    at every level implies collective exhaustion.

    Proof: given a σ-additive extension μ_i at level i and E_n ↘ ∅, the measure
    continuity theorem `tendsto_measure_iInter_atTop` gives μ_i (E_n) → μ_i ∅ = 0.
    Since μ_i agrees with ν i on measurable sets, ν i (E_n) → 0. Take j = i. -/
theorem sp1_necessity
    (P : S.NormalizedCompatibleContents)
    (hext : ∀ i : S.ι, ∃ μ : Measure (S.q i).Outcome,
        ∀ (A : Set (S.q i).Outcome), MeasurableSet A → μ A = P.ν i A)
    (i : S.ι)
    (E : ℕ → Set (S.q i).Outcome)
    (hE_meas : ∀ n, MeasurableSet (E n))
    (hE_anti : ∀ n, E (n + 1) ⊆ E n)
    (hE_empty : ⋂ n, E n = ∅) :
    Filter.Tendsto
      (fun n => P.ν i (E n))
      Filter.atTop (nhds 0) := by
  obtain ⟨μ, hμ⟩ := hext i
  -- Rewrite ν i (E n) = μ (E n) using the extension agreement
  simp_rw [← hμ _ (hE_meas _)]
  -- The sequence E is antitone as a function ℕ → Set
  have hE_antitone : Antitone E := by
    intro m n hmn
    induction hmn with
    | refl => exact fun x hx => hx
    | @step k _ ih => exact fun x hx => ih (hE_anti k hx)
  -- Apply measure continuity from above: μ (E n) → μ (⋂ n, E n) = μ ∅ = 0
  -- Requires ∃ n, μ (E n) ≠ ∞, which follows from normalization via P.ne_top
  have hfin : ∃ n, μ (E n) ≠ ∞ :=
    ⟨0, by rw [hμ _ (hE_meas 0)]; exact NormalizedCompatibleContents.ne_top S P i (E 0) (hE_meas 0)⟩
  have htend := tendsto_measure_iInter_atTop
    (s := E) (μ := μ)
    (hs := fun n => (hE_meas n).nullMeasurableSet)
    (hm := hE_antitone)
    (hf := hfin)
  rw [hE_empty, measure_empty] at htend
  exact htend

/-- **(SP1 Equivalence)** For a normalized compatible family, collective exhaustion
    is equivalent to σ-additive extensibility at every level.

    This is the formal content of the SP1 resolution and tetralemma dissolution:
    collective exhaustion is neither derivable from index-layer conditions (C1 false,
    shown by `fcContent_not_sigmaSubadditive`) nor a raw axiom (C2, unsatisfying) —
    it is the exact valuation-layer characterisation of σ-additive extensibility.
    The question "does index-layer coherence force σ-additivity?" was malformed;
    the correct question is "what valuation-layer condition characterises
    extensibility?", and the answer is collective exhaustion. -/
theorem sp1_iff
    (P : S.NormalizedCompatibleContents) :
    S.CollectivelyExhaustive P.ν ↔
    ∀ i : S.ι, ∃ μ : Measure (S.q i).Outcome,
      ∀ (A : Set (S.q i).Outcome), MeasurableSet A → μ A = P.ν i A :=
  ⟨fun h i => S.sp1_extension P h i,
   fun hext i E hE_meas hE_anti hE_empty =>
    ⟨i, S.le_refl i, by
      have hπ_id : (S.π (S.le_refl i)).π = id := S.π_refl i
      simp only [hπ_id, Set.preimage_id]
      exact S.sp1_necessity P hext i E hE_meas hE_anti hE_empty⟩⟩

end QuerySystem
