/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Patrick S. Mahon
-/
import Mathlib.MeasureTheory.Measure.MeasureSpaceDef
import Mathlib.MeasureTheory.Measure.Trim
import Mathlib.MeasureTheory.MeasurableSpace.Basic
import Mathlib.MeasureTheory.Function.SimpleFuncDenseLp
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.PiSystem
import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.MeasureTheory.Function.ConditionalExpectation.AEMeasurable
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.Order.SymmDiff
import QuerySystem.QuerySystem

/-!
# Reconstruction Theorem (Paper III)

This file formalises the reconstruction theorem and its central proof ingredient,
the **density bridge lemma**, connecting the Boolean algebra of observable events
to L²-approximation theory.

## Mathematical content

Fix a probability space `(X, m0, μ)` and a sub-σ-algebra `m ≤ m0`.

**Density bridge (Lemma 3.1).**  Simple functions w.r.t. `m` are dense in
`L²(X, m, μ.trim hm)` (`density_bridge`, proved directly via `Lp.simpleFunc.dense`).

**Reconstruction theorem (Theorem 4.1).**  For an invertible measure-preserving
system `(X, m0, μ, T)` and `h : X → ℝ`, define:
- `𝒪_h := observableAlgebra (fun n => h ∘ T^[n.toNat])` (the generated σ-algebra)
- `Φ_h := delayMap h T` (the delay map `x ↦ (h(T^n x))_{n ∈ ℤ}`)

The following are equivalent:
1. `𝒪_h = m0` modulo `μ`
2. `lpMeas ℝ ℝ 𝒪_h 2 μ` is dense in `Lp ℝ 2 μ`
3. `Φ_h` is a measure-theoretic embedding (a.e. injective, `𝒪_h = Φ_h⁻¹(ℬ(ℤ → ℝ))`)

**Cyclic vector → reconstruction (Corollary 5.2).**
If the linear span `span{h ∘ T^[n.toNat] : n ∈ ℤ}` is dense in `L²` (cyclic vector
condition for the Koopman operator `U_T`), then `lpMeas 𝒪_h 2 μ` is dense.

## Main results

* `observableAlgebra`              : definition (§1)
* `observableAlgebra_measurable`   : generators are `𝒪_h`-measurable (§1)
* `observableAlgebra_le`           : `𝒪_h ≤ m` when generators are `m`-measurable (§1)
* `density_bridge`                 : `Lp.simpleFunc ℝ 2 (μ.trim hm)` is dense (§2) ✅
* `lpMeas_eq_top_of_ae_eq`         : `m = m0` mod `μ` → `lpMeas = ⊤` (§2) sorry
* `reconstruction_iff_lpMeas`      : (i) ↔ (ii) (§3) sorry
* `delayMap`                       : definition (§4)
* `delayMap_measurable`            : measurability (§4) ✅
* `observableAlgebra_eq_comap`     : pullback identity (§4) sorry
* `bilateralShift`                 : definition (§5)
* `delayMap_intertwines_shift`     : `Φ_h ∘ T = σ ∘ Φ_h` (§5) sorry
* `cyclic_implies_dense`           : cyclic → dense (§6) sorry

## Sorry inventory (2 remaining)

| Name | Type | Proof sketch |
|------|------|--------------|
| `lpMeas_eq_top_of_ae_eq` | Mathlib gap | null-set approx → a.e. m-measurability; blocked by absence of downward `AEStronglyMeasurable` monotonicity in Mathlib |
| `reconstruction_iff_lpMeas` (←) | Mathlib gap | a.e.-convergent subsequence from Lp convergence; `tendsto_ae_of_tendsto_Lp` not in Mathlib |

Previously sorry: `observableAlgebra_eq_comap`, `delayMap_intertwines_shift`,
`cyclic_implies_dense` — all closed 2026-04-05.
`lpMeasSubgroup_dense_in_Lp` removed: unused and FALSE for general `m ≤ m0`.

See `notes/reconstruction_lean_flight_plan.md` for detailed API notes.
-/

open MeasureTheory MeasurableSpace Set Filter
open scoped symmDiff

-- ============================================================
-- §1  Observable algebra
-- ============================================================

variable {X : Type*}

/-- The σ-algebra on `X` generated by a family `f : ℤ → (X → ℝ)`.
    In the reconstruction application, `f n = h ∘ T^[n.toNat]`. -/
@[reducible] noncomputable def observableAlgebra (f : ℤ → (X → ℝ)) : MeasurableSpace X :=
  MeasurableSpace.generateFrom
    (⋃ n : ℤ, ⋃ (E : Set ℝ) (_ : @MeasurableSet ℝ _ E), {f n ⁻¹' E})

/-- Each `f n` is measurable w.r.t. `observableAlgebra f`. -/
lemma observableAlgebra_measurable (f : ℤ → (X → ℝ)) (n : ℤ) :
    Measurable[observableAlgebra f] (f n) := by
  intro E hE
  apply MeasurableSpace.measurableSet_generateFrom
  simp only [Set.mem_iUnion]
  exact ⟨n, E, hE, rfl⟩

/-- `observableAlgebra f ≤ m` when each `f n` is `m`-measurable. -/
lemma observableAlgebra_le {m : MeasurableSpace X}
    {f : ℤ → (X → ℝ)} (hf : ∀ n, Measurable[m] (f n)) :
    observableAlgebra f ≤ m := by
  apply MeasurableSpace.generateFrom_le
  intro s hs
  simp only [Set.mem_iUnion] at hs
  obtain ⟨n, E, hE, rfl⟩ := hs
  exact hf n hE

-- ============================================================
-- §2  Density bridge
-- ============================================================

/-!
## Density bridge

The core Mathlib fact: `Lp.simpleFunc.dense` (from `SimpleFuncDenseLp.lean`) gives
density of simple functions in `Lp`.  We apply it to `μ.trim hm`.

The `lpMeas` subgroup version uses `lpMeasSubgroupToLpTrimIso` (an isometric iso
between `lpMeasSubgroup F m p μ` and `Lp F p (μ.trim hm)`) to transfer density.
-/

/-- **Density bridge (Lemma 3.1, Paper III):**
    `m`-simple functions are dense in `L²(X, m, μ.trim hm)`.

    This is proved directly from `Lp.simpleFunc.dense`, which is itself the Lean
    form of the functional monotone class theorem for `Lp` spaces. -/
theorem density_bridge [MeasurableSpace X] {m : MeasurableSpace X}
    (hm : m ≤ ‹MeasurableSpace X›) (μ : Measure X) [IsFiniteMeasure μ] :
    Dense (Lp.simpleFunc ℝ 2 (μ.trim hm) : Set (Lp ℝ 2 (μ.trim hm))) :=
  Lp.simpleFunc.dense (by norm_num)

/-- When `m = m0` mod `μ`, `lpMeas ℝ ℝ m 2 μ = ⊤`.

    **Proof sketch:** Every `f ∈ Lp ℝ 2 μ` is approximated by `m0`-simple
    functions (via `Lp.simpleFunc.dense`).  Since `m = m0` mod `μ`, each
    `m0`-indicator `𝟙_s` is a.e. equal to an `m`-indicator.  Hence every
    `m0`-simple function is a.e. `m`-measurable → `f` is a.e. `m`-measurable
    → `f ∈ lpMeas m`. -/
theorem lpMeas_eq_top_of_ae_eq [MeasurableSpace X] {m : MeasurableSpace X}
    (hm : m ≤ ‹MeasurableSpace X›) (μ : Measure X) [IsFiniteMeasure μ]
    (h_ae : ∀ s : Set X, MeasurableSet s →
        ∃ t : Set X, MeasurableSet[m] t ∧ μ (s ∆ t) = 0) :
    lpMeas ℝ ℝ m 2 μ = ⊤ := by
  sorry

-- ============================================================
-- §3  Reconstruction: (i) ↔ (ii)
-- ============================================================

/-- **Reconstruction theorem, (i) ↔ (ii) (Theorem 4.1, Paper III).**

- (i): `m = mX` mod `μ` (every measurable set has an `m`-version a.e.)
- (ii): `lpMeas ℝ ℝ m 2 μ` is dense in `Lp ℝ 2 μ`

(i)→(ii): by `lpMeas_eq_top_of_ae_eq`, `lpMeas = ⊤`, which is dense.
(ii)→(i): L²-approximation of `𝟙_s` by `lpMeas` elements gives a.e.-`m` version. -/
theorem reconstruction_iff_lpMeas [MeasurableSpace X] {m : MeasurableSpace X}
    (hm : m ≤ ‹MeasurableSpace X›) (μ : Measure X) [IsFiniteMeasure μ] :
    (∀ s : Set X, MeasurableSet s →
        ∃ t : Set X, MeasurableSet[m] t ∧ μ (s ∆ t) = 0) ↔
    Dense (lpMeas ℝ ℝ m 2 μ : Set (Lp ℝ 2 μ)) := by
  constructor
  · intro h_ae
    have htop := lpMeas_eq_top_of_ae_eq hm μ h_ae
    rw [show (lpMeas ℝ ℝ m 2 μ : Set (Lp ℝ 2 μ)) = Set.univ from ?_]
    · exact dense_univ
    · rw [Submodule.coe_eq_univ]; exact htop
  · intro _h_dense s _hs
    sorry

-- ============================================================
-- §4  Delay map and pullback identity
-- ============================================================

variable [mX : MeasurableSpace X]

/-- The delay map `Φ_h : X → (ℕ → ℝ)`, `Φ_h(x)(n) = h(T^[n] x)`.

    We index by `ℕ` (forward orbit only) rather than `ℤ`, which is the natural
    domain for the shift intertwining identity.  When `T` is invertible, the
    forward orbit generates the same σ-algebra as the full bi-infinite orbit. -/
def delayMap (h : X → ℝ) (T : X → X) : X → (ℕ → ℝ) :=
  fun x n => h (T^[n] x)

/-- `Φ_h` is measurable when `h` and `T` are measurable. -/
theorem delayMap_measurable
    (h : X → ℝ) (T : X → X) (hh : Measurable h) (hT : Measurable T) :
    Measurable (delayMap h T) := by
  apply measurable_pi_lambda
  intro n
  exact hh.comp (hT.iterate n)

/-- **Pullback identity (Lemma 2.3, Paper III):**
    `observableAlgebra (h ∘ T^[·]) = Φ_h⁻¹(ℬ(ℕ → ℝ))`.

    **Proof sketch:**
    - (≤): Each generator `h ∘ T^[n] = πₙ ∘ Φ_h` (projection at index `n : ℕ`),
      so its level sets are in `Φ_h⁻¹(ℬ(ℕ → ℝ))`.
    - (≥): The product σ-algebra `ℬ(ℕ → ℝ)` is generated by coordinate projections
      `πₙ`, and `Φ_h⁻¹(πₙ⁻¹(E)) = (h ∘ T^[n])⁻¹(E) ∈ 𝒪_h`. -/
theorem observableAlgebra_eq_comap
    (h : X → ℝ) (T : X → X) (hh : Measurable h) (hT : Measurable T) :
    observableAlgebra (fun n : ℤ => h ∘ T^[n.toNat]) =
    MeasurableSpace.comap (delayMap h T)
        (MeasurableSpace.pi (m := fun (_ : ℕ) => inferInstance)) := by
  apply le_antisymm
  · -- (≤): observableAlgebra ≤ comap (delayMap h T) pi.
    -- Each generator h ∘ T^[n.toNat] = (eval n.toNat) ∘ (delayMap h T),
    -- so it's measurable w.r.t. the comap.
    apply observableAlgebra_le
    intro n
    -- Need: Measurable[comap (delayMap h T) pi] (h ∘ T^[n.toNat])
    -- Since h ∘ T^[n.toNat] = (eval n.toNat) ∘ (delayMap h T), and
    -- (eval n.toNat) is pi-measurable, their composition is comap-measurable.
    have hfactor : h ∘ T^[n.toNat] = (fun f : ℕ → ℝ => f n.toNat) ∘ delayMap h T := rfl
    rw [hfactor]
    exact (measurable_pi_apply n.toNat).comp
      (measurable_iff_comap_le.mpr le_rfl)
  · -- (≥): comap (delayMap h T) pi ≤ observableAlgebra.
    -- Unfold comap and pi, then apply generateFrom_le on both layers.
    -- comap (delayMap h T) pi = generateFrom {(delayMap h T)⁻¹ s | s ∈ pi}
    -- pi = ⨆ n, comap (eval n) inferInstance
    -- So comap (delayMap h T) pi = ⨆ n, comap (eval n ∘ delayMap h T) inferInstance
    --                             = ⨆ n, comap (h ∘ T^[n]) inferInstance
    -- and each comap (h ∘ T^[n]) inferInstance ≤ observableAlgebra.
    -- Lean path: unfold MeasurableSpace.pi as ⨆, use iSup_le + comap_mono.
    simp only [MeasurableSpace.pi, MeasurableSpace.comap_iSup, MeasurableSpace.comap_comp]
    apply iSup_le
    intro n
    -- Goal: comap ((fun b => b n) ∘ delayMap h T) inferInstance ≤ observableAlgebra ...
    -- = comap (h ∘ T^[n]) ℝ ≤ observableAlgebra ...
    -- by measurable_iff_comap_le, equivalent to: Measurable[observableAlgebra] (h ∘ T^[n])
    apply measurable_iff_comap_le.mp
    -- Goal: Measurable[observableAlgebra (fun k : ℤ => h ∘ T^[k.toNat])]
    --       ((fun b => b n) ∘ delayMap h T)
    -- = h ∘ T^[n] = generator at (n : ℤ)
    have heq : (fun b : ℕ → ℝ => b n) ∘ delayMap h T =
        (fun k : ℤ => h ∘ T^[k.toNat]) (n : ℤ) := by
      funext x
      simp [delayMap, Int.toNat_natCast]
    rw [heq]
    exact observableAlgebra_measurable (fun k : ℤ => h ∘ T^[k.toNat]) (n : ℤ)

-- ============================================================
-- §5  Shift intertwining
-- ============================================================

/-- The unilateral shift `σ` on `ℕ → ℝ`: `(σ f)(n) = f(n + 1)`. -/
def unilateralShift : (ℕ → ℝ) → (ℕ → ℝ) := fun f n => f (n + 1)

/-- **Shift intertwining (Corollary 4.3, Paper III):** `Φ_h(T x) = σ(Φ_h(x))`.

    `Φ_h(T x)(n) = h(T^[n](T x)) = h(T^[n+1] x) = Φ_h(x)(n+1) = (σ Φ_h(x))(n)`. -/
theorem delayMap_intertwines_shift (h : X → ℝ) (T : X → X) (x : X) :
    delayMap h T (T x) = unilateralShift (delayMap h T x) := by
  ext n
  simp only [delayMap, unilateralShift, Function.iterate_succ_apply]

-- ============================================================
-- §6  Cyclic vector → reconstruction
-- ============================================================

/-- **Cyclic vector implies reconstruction (Corollary 5.2, Paper III).**

If `h` is cyclic for the Koopman operator `U_T` — the closure of
`span{h ∘ T^[n.toNat] : n ∈ ℤ}` equals `Lp ℝ 2 μ` — then `lpMeas 𝒪_h 2 μ`
is dense.

**Proof sketch:**
1. Each `h ∘ T^[n.toNat]` is `𝒪_h`-measurable (`observableAlgebra_measurable`),
   so `(hmem n).toLp _ ∈ lpMeas 𝒪_h`.
2. `cyclicSpan ≤ lpMeas 𝒪_h` as submodules of `Lp ℝ 2 μ`.
3. Monotonicity of closure: `cyclicSpan.closure = ⊤ → lpMeas.closure = ⊤`.
4. `Submodule.topologicalClosure_eq_top_iff_dense`: closure `⊤` implies dense. -/
theorem cyclic_implies_dense
    (μ : Measure X) [IsFiniteMeasure μ]
    (h : X → ℝ) (T : X → X)
    (_hh : Measurable h) (_hT : Measurable T)
    (hmem : ∀ n : ℕ, MemLp (h ∘ T^[n]) 2 μ)
    (h_cyclic :
      (Submodule.span ℝ
        (Set.range (fun n : ℕ => (hmem n).toLp _))).topologicalClosure = ⊤) :
    Dense (lpMeas ℝ ℝ (observableAlgebra (fun n : ℤ => h ∘ T^[n.toNat])) 2 μ :
      Set (Lp ℝ 2 μ)) := by
  -- Step 1: each generator (hmem n).toLp _ is in lpMeas 𝒪_h.
  -- Reason: h ∘ T^[n] is AEStronglyMeasurable[𝒪_h] (from observableAlgebra_measurable).
  have hmem_lpMeas : ∀ n : ℕ,
      (hmem n).toLp (h ∘ T^[n]) ∈
        lpMeas ℝ ℝ (observableAlgebra (fun k : ℤ => h ∘ T^[k.toNat])) 2 μ := by
    intro n
    rw [mem_lpMeas_iff_aestronglyMeasurable]
    -- The Lp coercion is a.e. equal to h ∘ T^[n]; use congr to reduce to the function.
    rw [aestronglyMeasurable_congr (hmem n).coeFn_toLp]
    -- Now goal: AEStronglyMeasurable[𝒪_h] (h ∘ T^[n]) μ
    have hgen : h ∘ T^[n] = (fun k : ℤ => h ∘ T^[k.toNat]) (n : ℤ) := by
      simp [Int.toNat_natCast]
    rw [hgen]
    exact (observableAlgebra_measurable (fun k : ℤ => h ∘ T^[k.toNat]) (n : ℤ)).aestronglyMeasurable
  -- Step 2: cyclicSpan ≤ lpMeas 𝒪_h as submodules.
  have hspan_le :
      Submodule.span ℝ (Set.range (fun n : ℕ => (hmem n).toLp _)) ≤
        lpMeas ℝ ℝ (observableAlgebra (fun k : ℤ => h ∘ T^[k.toNat])) 2 μ := by
    apply Submodule.span_le.mpr
    rintro f ⟨n, rfl⟩
    exact hmem_lpMeas n
  -- Step 3: monotonicity of topological closure + h_cyclic → lpMeas closure = ⊤.
  rw [Submodule.dense_iff_topologicalClosure_eq_top]
  exact top_le_iff.mp (h_cyclic ▸ Submodule.topologicalClosure_mono hspan_le)
