/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Patrick S. Mahon
-/
import Mathlib.MeasureTheory.Measure.MeasureSpaceDef
import Mathlib.MeasureTheory.Measure.Trim
import Mathlib.MeasureTheory.MeasurableSpace.Basic
import Mathlib.MeasureTheory.Function.SimpleFuncDenseLp
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.PiSystem
import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.MeasureTheory.Function.ConditionalExpectation.AEMeasurable
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.Order.SymmDiff
import QuerySystem.QuerySystem

/-!
# Reconstruction Theorem (Paper II)

This file formalises the reconstruction theorem and its central proof ingredient,
the **density bridge lemma**, connecting the Boolean algebra of observable events
to L²-approximation theory.

## Mathematical content

Fix a probability space `(X, m0, μ)` and a sub-σ-algebra `m ≤ m0`.

**Density bridge (Lemma 4.3).**  Paper II Lemma 4.3 states that for any subalgebra
`𝒜 ⊆ L∞`, the L²-closure of `𝒜` equals `L²(X, σ(𝒜), μ)`.  In Lean this is
discharged by two theorems acting in concert: `density_bridge` (m-simple functions
are dense in `L²(X, m, μ.trim hm)`, via `Lp.simpleFunc.dense`) together with
`lpMeas_eq_top_of_ae_eq` and `reconstruction_iff_lpMeas` (which establish the
closed+dense=⊤ argument for the lpMeas subspace).

**Reconstruction theorem (Theorem 4.1).**  For an invertible measure-preserving
system `(X, m0, μ, T)` and `h : X → ℝ`, define:
- `𝒪_h := observableAlgebra (fun n => h ∘ T^[n.toNat])` (the generated σ-algebra)
- `Φ_h := delayMap h T` (the delay map `x ↦ (h(T^n x))_{n ∈ ℕ}`)

**Note on ℤ vs ℕ indexing:** Paper II defines `Φ_h : X → ℝ^ℤ` using the full
bi-infinite orbit.  Lean uses `ℕ` (forward orbit only).  For invertible T these
generate the same σ-algebra: `h ∘ T^{-k}` is measurable w.r.t.
`σ({h ∘ T^n : n ∈ ℕ})` because `T^{-k} = (T^{-1})^k` and T⁻¹ is itself
`𝒪_h`-measurable when T is bimeasurable and `𝒪_h = ℬ` mod μ.  The Lean
formulation is therefore equivalent to the paper's for the reconstruction question.

The following are equivalent:
1. `𝒪_h = m0` modulo `μ` — proved: `reconstruction_iff_lpMeas` (i↔ii)
2. `lpMeas ℝ ℝ 𝒪_h 2 μ` is dense in `Lp ℝ 2 μ` — proved: `reconstruction_iff_lpMeas`
3. `Φ_h` is a measure-theoretic embedding (`𝒪_h = Φ_h⁻¹(ℬ(ℕ → ℝ))`) —
   (i↔iii) is immediate from `observableAlgebra_eq_comap`: condition (iii) is
   exactly the statement of that theorem, so (i)↔(iii) follows by rewriting.

**Cyclic vector → reconstruction (Corollary II:cor:cyclic-implies-reconstruction).**
If the closed linear span `span{h ∘ T^[n] : n ∈ ℕ}` is dense in `L²` (forward-orbit
cyclic condition; equivalent to full ℤ-orbit cyclicity when T is invertible), then
`lpMeas 𝒪_h 2 μ` is dense, and hence `𝒪_h = m0` mod μ.

## Main results

* `observableAlgebra`              : definition (§1)
* `observableAlgebra_measurable`   : generators are `𝒪_h`-measurable (§1)
* `observableAlgebra_le`           : `𝒪_h ≤ m` when generators are `m`-measurable (§1)
* `density_bridge`                 : `Lp.simpleFunc ℝ 2 (μ.trim hm)` is dense (§2) ✅
* `lpMeas_eq_top_of_ae_eq`         : `m = m0` mod `μ` → `lpMeas = ⊤` (§2) ✅
* `reconstruction_iff_lpMeas`      : (i) ↔ (ii) (§3) ✅
* `delayMap`                       : definition (§4) ✅
* `delayMap_measurable`            : measurability (§4) ✅
* `observableAlgebra_eq_comap`     : pullback identity (§4) ✅
* `unilateralShift`                : definition (§5) ✅
* `delayMap_intertwines_shift`     : `Φ_h ∘ T = σ ∘ Φ_h` (§5) ✅
* `cyclic_implies_dense`           : cyclic → dense (§6) ✅

## Sorry inventory (0 remaining — all closed 2026-04-27)

Previously sorry (now closed):
- `lpMeas_eq_top_of_ae_eq` (2026-04-27): closed via `isClosed_aestronglyMeasurable` +
  `SimpleFunc.induction` + `Lp.simpleFunc.dense` + closed-dense=⊤.
- `reconstruction_iff_lpMeas` (←) (2026-04-27): dense+closed=⊤ → every Lp element is in
  lpMeas → indicator `𝟙_s` is m-a.e. measurable → extract set t = g⁻¹(Ioi 0).
- `observableAlgebra_eq_comap`, `delayMap_intertwines_shift`,
  `cyclic_implies_dense` — all closed 2026-04-05.
- `lpMeasSubgroup_dense_in_Lp` removed: unused and FALSE for general `m ≤ m0`.

See `archive/notes_archived_artifacts/reconstruction_lean_flight_plan.md` for
detailed API notes.
-/

open MeasureTheory MeasurableSpace Set Filter
open scoped symmDiff

-- ============================================================
-- §1  Observable algebra
-- ============================================================

variable {X : Type*}

/-- The σ-algebra on `X` generated by a family `f : ℤ → (X → ℝ)`.
    In the reconstruction application, `f n = h ∘ T^[n.toNat]`. -/
@[reducible] noncomputable def observableAlgebra (f : ℤ → (X → ℝ)) : MeasurableSpace X :=
  MeasurableSpace.generateFrom
    (⋃ n : ℤ, ⋃ (E : Set ℝ) (_ : @MeasurableSet ℝ _ E), {f n ⁻¹' E})

/-- Each `f n` is measurable w.r.t. `observableAlgebra f`. -/
lemma observableAlgebra_measurable (f : ℤ → (X → ℝ)) (n : ℤ) :
    Measurable[observableAlgebra f] (f n) := by
  intro E hE
  apply MeasurableSpace.measurableSet_generateFrom
  simp only [Set.mem_iUnion]
  exact ⟨n, E, hE, rfl⟩

/-- `observableAlgebra f ≤ m` when each `f n` is `m`-measurable. -/
lemma observableAlgebra_le {m : MeasurableSpace X}
    {f : ℤ → (X → ℝ)} (hf : ∀ n, Measurable[m] (f n)) :
    observableAlgebra f ≤ m := by
  apply MeasurableSpace.generateFrom_le
  intro s hs
  simp only [Set.mem_iUnion] at hs
  obtain ⟨n, E, hE, rfl⟩ := hs
  exact hf n hE

-- ============================================================
-- §2  Density bridge
-- ============================================================

/-!
## Density bridge

The core Mathlib fact: `Lp.simpleFunc.dense` (from `SimpleFuncDenseLp.lean`) gives
density of simple functions in `Lp`.  We apply it to `μ.trim hm`.

The `lpMeas` subgroup version uses `lpMeasSubgroupToLpTrimIso` (an isometric iso
between `lpMeasSubgroup F m p μ` and `Lp F p (μ.trim hm)`) to transfer density.
-/

/-- **Density bridge component (Lemma 4.3, Paper II):**
    `m`-simple functions are dense in `L²(X, m, μ.trim hm)`.

    This is the key density fact used in the Lean proof of Lemma 4.3.  The full
    Paper II statement — that the L²-closure of an algebra `𝒜` equals
    `L²(X, σ(𝒜), μ)` — is discharged in Lean by this theorem together with
    `lpMeas_eq_top_of_ae_eq` (which establishes that `lpMeas = ⊤` when `m = m0`
    mod μ) and `reconstruction_iff_lpMeas` (the closed+dense=⊤ argument).

    Proved directly from `Lp.simpleFunc.dense`, the Lean form of the functional
    monotone class theorem for `Lp` spaces. -/
theorem density_bridge [MeasurableSpace X] {m : MeasurableSpace X}
    (hm : m ≤ ‹MeasurableSpace X›) (μ : Measure X) [IsFiniteMeasure μ] :
    Dense (Lp.simpleFunc ℝ 2 (μ.trim hm) : Set (Lp ℝ 2 (μ.trim hm))) :=
  Lp.simpleFunc.dense (by norm_num)

/-- When `m = m0` mod `μ`, `lpMeas ℝ ℝ m 2 μ = ⊤`.

    **Proof sketch:** Every `f ∈ Lp ℝ 2 μ` is approximated by `m0`-simple
    functions (via `Lp.simpleFunc.dense`).  Since `m = m0` mod `μ`, each
    `m0`-indicator `𝟙_s` is a.e. equal to an `m`-indicator.  Hence every
    `m0`-simple function is a.e. `m`-measurable → `f` is a.e. `m`-measurable
    → `f ∈ lpMeas m`. -/
theorem lpMeas_eq_top_of_ae_eq [MeasurableSpace X] {m : MeasurableSpace X}
    (hm : m ≤ ‹MeasurableSpace X›) (μ : Measure X) [IsFiniteMeasure μ]
    (h_ae : ∀ s : Set X, MeasurableSet s →
        ∃ t : Set X, MeasurableSet[m] t ∧ μ (s ∆ t) = 0) :
    lpMeas ℝ ℝ m 2 μ = ⊤ := by
  -- Strategy: (1) lpMeas is closed; (2) every m0-simple function lies in it
  -- (via h_ae: each indicator a.e.-equal to an m-indicator); (3) m0-simple
  -- functions are dense in Lp ℝ 2 μ. Closed + dense ⟹ ⊤.
  -- Note: `fact_one_le_two_ennreal` provides `Fact ((1 : ℝ≥0∞) ≤ 2)` globally.
  -- (1) The carrier of lpMeas is closed in Lp ℝ 2 μ
  have hclosed : IsClosed (lpMeas ℝ ℝ m 2 μ : Set (Lp ℝ 2 μ)) :=
    isClosed_aestronglyMeasurable (F := ℝ) (p := 2) hm
  -- (2) Every m0-simple function (viewed as Lp element) is in lpMeas.
  -- Key: its toSimpleFunc is a.e. equal to an m-strongly measurable function,
  -- built by induction replacing each m0-indicator with its m-version via h_ae.
  have hmem : ∀ φ : Lp.simpleFunc ℝ 2 μ,
      (φ : Lp ℝ 2 μ) ∈ lpMeas ℝ ℝ m 2 μ := fun φ => by
    rw [mem_lpMeas_iff_aestronglyMeasurable]
    -- Build g : X → ℝ, m-strongly measurable, a.e.-equal to φ.toSimpleFunc
    -- Let s := the underlying SimpleFunc of φ
    set s := Lp.simpleFunc.toSimpleFunc φ with hs_def
    suffices hg : ∃ g : X → ℝ, StronglyMeasurable[m] g ∧ (s : X → ℝ) =ᵐ[μ] g by
      obtain ⟨g, hgm, hsg⟩ := hg
      -- (φ : Lp) =ᵐ s =ᵐ g  ⟹  AEStronglyMeasurable[m] (φ : Lp)
      exact (aestronglyMeasurable_congr
        ((Lp.simpleFunc.toSimpleFunc_eq_toFun φ).symm.trans hsg)).mpr
        hgm.aestronglyMeasurable
    -- Induction on the simple function s
    induction s using MeasureTheory.SimpleFunc.induction with
    | @const c sv hsv =>
      -- indicator of m0-set sv: replace with m-version t via h_ae
      obtain ⟨t, ht, hst⟩ := h_ae sv hsv
      refine ⟨t.indicator (fun _ => c), (stronglyMeasurable_const.indicator ht), ?_⟩
      -- sv =ᵐ[μ] t  ⟹  sv.indicator c =ᵐ t.indicator c
      have hseqt : sv =ᵐ[μ] t := measure_symmDiff_eq_zero_iff.mp hst
      -- The SimpleFunc coercion equals sv.indicator (fun _ => c)
      have hcoe : (SimpleFunc.piecewise sv hsv (SimpleFunc.const X c)
          (SimpleFunc.const X 0) : X → ℝ) = sv.indicator (fun _ => c) := by
        ext x
        classical
        simp [SimpleFunc.piecewise_apply, Set.indicator_apply]
      rw [hcoe]
      exact indicator_ae_eq_of_ae_eq_set hseqt
    | @add f g _hdisj hf hg =>
      obtain ⟨g₁, hg₁, hfg₁⟩ := hf
      obtain ⟨g₂, hg₂, hgg₂⟩ := hg
      exact ⟨g₁ + g₂, hg₁.add hg₂, hfg₁.add hgg₂⟩
  -- (3) m0-simple functions are dense in Lp ℝ 2 μ, and all lie in lpMeas
  have hsubset : (Lp.simpleFunc ℝ 2 μ : Set (Lp ℝ 2 μ)) ⊆
      (lpMeas ℝ ℝ m 2 μ : Set (Lp ℝ 2 μ)) := by
    intro f hf
    -- hf : f ∈ Lp.simpleFunc ℝ 2 μ (as AddSubgroup membership)
    -- Package into the subtype and apply hmem
    exact hmem ⟨f, hf⟩
  have hdense : Dense (lpMeas ℝ ℝ m 2 μ : Set (Lp ℝ 2 μ)) :=
    (Lp.simpleFunc.dense (E := ℝ) (p := 2) (μ := μ) (by norm_num)).mono hsubset
  -- Closed dense subspace = ⊤
  rw [← Submodule.coe_eq_univ]
  exact hclosed.closure_eq ▸ hdense.closure_eq

-- ============================================================
-- §3  Reconstruction: (i) ↔ (ii)
-- ============================================================

/-- **Reconstruction theorem, (i) ↔ (ii) (Theorem 4.1, Paper II).**

- (i): `m = mX` mod `μ` (every measurable set has an `m`-version a.e.)
- (ii): `lpMeas ℝ ℝ m 2 μ` is dense in `Lp ℝ 2 μ`

(i)→(ii): by `lpMeas_eq_top_of_ae_eq`, `lpMeas = ⊤`, which is dense.
(ii)→(i): L²-approximation of `𝟙_s` by `lpMeas` elements gives a.e.-`m` version. -/
theorem reconstruction_iff_lpMeas [MeasurableSpace X] {m : MeasurableSpace X}
    (hm : m ≤ ‹MeasurableSpace X›) (μ : Measure X) [IsFiniteMeasure μ] :
    (∀ s : Set X, MeasurableSet s →
        ∃ t : Set X, MeasurableSet[m] t ∧ μ (s ∆ t) = 0) ↔
    Dense (lpMeas ℝ ℝ m 2 μ : Set (Lp ℝ 2 μ)) := by
  constructor
  · intro h_ae
    have htop := lpMeas_eq_top_of_ae_eq hm μ h_ae
    rw [show (lpMeas ℝ ℝ m 2 μ : Set (Lp ℝ 2 μ)) = Set.univ from ?_]
    · exact dense_univ
    · rw [Submodule.coe_eq_univ]; exact htop
  · intro h_dense s hs
    -- (1) lpMeas is closed (AEStronglyMeasurable[m] is a closed condition) and dense → = ⊤
    have hclosed : IsClosed (lpMeas ℝ ℝ m 2 μ : Set (Lp ℝ 2 μ)) :=
      isClosed_aestronglyMeasurable (F := ℝ) (p := 2) hm
    have htop : lpMeas ℝ ℝ m 2 μ = ⊤ := by
      rw [← Submodule.coe_eq_univ]
      exact hclosed.closure_eq ▸ h_dense.closure_eq
    -- (2) Build 𝟙_s as an Lp element; it lies in lpMeas = ⊤
    have hμs : μ s ≠ ⊤ := measure_ne_top μ s
    have hmemLp : MemLp (s.indicator (fun _ => (1 : ℝ))) 2 μ :=
      memLp_indicator_const 2 hs 1 (Or.inr hμs)
    set f_lp := hmemLp.toLp _ with hf_lp_def
    have hf_lp_mem : f_lp ∈ lpMeas ℝ ℝ m 2 μ := htop ▸ Submodule.mem_top
    -- (3) Extract m-strongly measurable representative g
    have haesm : AEStronglyMeasurable[m] (f_lp : X → ℝ) μ :=
      mem_lpMeas_iff_aestronglyMeasurable.mp hf_lp_mem
    set g := haesm.mk f_lp with hg_def
    have hgm : Measurable[m] g := haesm.measurable_mk
    -- (4) indicator =ᵐ[μ] g via transitivity through f_lp
    have hind_eq_g : s.indicator (fun _ => (1 : ℝ)) =ᵐ[μ] g :=
      hmemLp.coeFn_toLp.symm.trans haesm.ae_eq_mk
    -- (5) t = g⁻¹'(Ioi 0) is m-measurable and s =ᵐ[μ] t
    refine ⟨g ⁻¹' Set.Ioi 0, hgm measurableSet_Ioi, ?_⟩
    rw [measure_symmDiff_eq_zero_iff]
    filter_upwards [hind_eq_g] with x hx
    -- hx : s.indicator (fun _ => 1) x = g x
    -- goal : x ∈ s = x ∈ g ⁻¹' Set.Ioi 0 (Prop equality)
    apply propext
    constructor
    · intro hxs
      have h1 : s.indicator (fun _ => (1 : ℝ)) x = 1 :=
        Set.indicator_of_mem hxs _
      have hg1 : g x = 1 := hx ▸ h1
      exact Set.mem_preimage.mpr (Set.mem_Ioi.mpr (by linarith))
    · intro hxg
      have hgpos : 0 < g x := Set.mem_Ioi.mp (Set.mem_preimage.mp hxg)
      by_contra hxs
      have h0 : s.indicator (fun _ => (1 : ℝ)) x = 0 :=
        Set.indicator_of_notMem hxs _
      have hg0 : g x = 0 := hx ▸ h0
      linarith

-- ============================================================
-- §4  Delay map and pullback identity
-- ============================================================

variable [mX : MeasurableSpace X]

/-- The delay map `Φ_h : X → (ℕ → ℝ)`, `Φ_h(x)(n) = h(T^[n] x)`.

    **ℤ vs ℕ:** Paper II (Definition II:def:delay-map) defines `Φ_h : X → ℝ^ℤ`
    using the full bi-infinite orbit `(h(T^n x))_{n ∈ ℤ}`.  Lean uses `ℕ` (forward
    orbit only) for two reasons:
    1. `Function.iterate` in Mathlib is indexed by `ℕ`; the negative iterates
       `T^{-k}` require a separately-supplied inverse, complicating the definition.
    2. For invertible `T`, the forward and bi-infinite orbits generate the same
       σ-algebra: `σ({h ∘ T^n : n ∈ ℕ}) = σ({h ∘ T^n : n ∈ ℤ})` because
       `h ∘ T^{-k}` is measurable w.r.t. `σ({h ∘ T^n : n ∈ ℕ})` whenever T
       is bimeasurable.  So the reconstruction question is unaffected by the
       choice of index set.

    The pullback identity `observableAlgebra_eq_comap` and the reconstruction
    theorem `reconstruction_iff_lpMeas` are therefore equivalent to their
    Paper II counterparts. -/
def delayMap (h : X → ℝ) (T : X → X) : X → (ℕ → ℝ) :=
  fun x n => h (T^[n] x)

/-- `Φ_h` is measurable when `h` and `T` are measurable. -/
theorem delayMap_measurable
    (h : X → ℝ) (T : X → X) (hh : Measurable h) (hT : Measurable T) :
    Measurable (delayMap h T) := by
  apply measurable_pi_lambda
  intro n
  exact hh.comp (hT.iterate n)

/-- **Pullback identity (Definition II:def:delay-map, Paper II):**
    `observableAlgebra (h ∘ T^[·]) = Φ_h⁻¹(ℬ(ℕ → ℝ))`.
    Note: Paper II states this inside Definition 4.2 (delay map), not as a separate lemma.

    **Proof sketch:**
    - (≤): Each generator `h ∘ T^[n] = πₙ ∘ Φ_h` (projection at index `n : ℕ`),
      so its level sets are in `Φ_h⁻¹(ℬ(ℕ → ℝ))`.
    - (≥): The product σ-algebra `ℬ(ℕ → ℝ)` is generated by coordinate projections
      `πₙ`, and `Φ_h⁻¹(πₙ⁻¹(E)) = (h ∘ T^[n])⁻¹(E) ∈ 𝒪_h`. -/
theorem observableAlgebra_eq_comap
    (h : X → ℝ) (T : X → X) (hh : Measurable h) (hT : Measurable T) :
    observableAlgebra (fun n : ℤ => h ∘ T^[n.toNat]) =
    MeasurableSpace.comap (delayMap h T)
        (MeasurableSpace.pi (m := fun (_ : ℕ) => inferInstance)) := by
  apply le_antisymm
  · -- (≤): observableAlgebra ≤ comap (delayMap h T) pi.
    -- Each generator h ∘ T^[n.toNat] = (eval n.toNat) ∘ (delayMap h T),
    -- so it's measurable w.r.t. the comap.
    apply observableAlgebra_le
    intro n
    -- Need: Measurable[comap (delayMap h T) pi] (h ∘ T^[n.toNat])
    -- Since h ∘ T^[n.toNat] = (eval n.toNat) ∘ (delayMap h T), and
    -- (eval n.toNat) is pi-measurable, their composition is comap-measurable.
    have hfactor : h ∘ T^[n.toNat] = (fun f : ℕ → ℝ => f n.toNat) ∘ delayMap h T := rfl
    rw [hfactor]
    exact (measurable_pi_apply n.toNat).comp
      (measurable_iff_comap_le.mpr le_rfl)
  · -- (≥): comap (delayMap h T) pi ≤ observableAlgebra.
    -- Unfold comap and pi, then apply generateFrom_le on both layers.
    -- comap (delayMap h T) pi = generateFrom {(delayMap h T)⁻¹ s | s ∈ pi}
    -- pi = ⨆ n, comap (eval n) inferInstance
    -- So comap (delayMap h T) pi = ⨆ n, comap (eval n ∘ delayMap h T) inferInstance
    --                             = ⨆ n, comap (h ∘ T^[n]) inferInstance
    -- and each comap (h ∘ T^[n]) inferInstance ≤ observableAlgebra.
    -- Lean path: unfold MeasurableSpace.pi as ⨆, use iSup_le + comap_mono.
    simp only [MeasurableSpace.pi, MeasurableSpace.comap_iSup, MeasurableSpace.comap_comp]
    apply iSup_le
    intro n
    -- Goal: comap ((fun b => b n) ∘ delayMap h T) inferInstance ≤ observableAlgebra ...
    -- = comap (h ∘ T^[n]) ℝ ≤ observableAlgebra ...
    -- by measurable_iff_comap_le, equivalent to: Measurable[observableAlgebra] (h ∘ T^[n])
    apply measurable_iff_comap_le.mp
    -- Goal: Measurable[observableAlgebra (fun k : ℤ => h ∘ T^[k.toNat])]
    --       ((fun b => b n) ∘ delayMap h T)
    -- = h ∘ T^[n] = generator at (n : ℤ)
    have heq : (fun b : ℕ → ℝ => b n) ∘ delayMap h T =
        (fun k : ℤ => h ∘ T^[k.toNat]) (n : ℤ) := by
      funext x
      simp [delayMap, Int.toNat_natCast]
    rw [heq]
    exact observableAlgebra_measurable (fun k : ℤ => h ∘ T^[k.toNat]) (n : ℤ)

-- ============================================================
-- §5  Shift intertwining
-- ============================================================

/-- The unilateral shift `σ` on `ℕ → ℝ`: `(σ f)(n) = f(n + 1)`. -/
def unilateralShift : (ℕ → ℝ) → (ℕ → ℝ) := fun f n => f (n + 1)

/-- **Shift intertwining (Paper II, §4.2 inline):** `Φ_h(T x) = σ(Φ_h(x))`.

    Stated inline in the proof of Theorem II:thm:reconstruction (§4.2):
    `(Φ_h(Tx))_n = h(T^{n+1} x) = (σ(Φ_h(x)))_n`.

    `Φ_h(T x)(n) = h(T^[n](T x)) = h(T^[n+1] x) = Φ_h(x)(n+1) = (σ Φ_h(x))(n)`. -/
theorem delayMap_intertwines_shift (h : X → ℝ) (T : X → X) (x : X) :
    delayMap h T (T x) = unilateralShift (delayMap h T x) := by
  ext n
  simp only [delayMap, unilateralShift, Function.iterate_succ_apply]

-- ============================================================
-- §6  Cyclic vector → reconstruction
-- ============================================================

/-- **Cyclic vector implies reconstruction (Corollary II:cor:cyclic-implies-reconstruction, Paper II).**

If `h` is cyclic for the Koopman operator `U_T` — the closure of
`span{h ∘ T^[n.toNat] : n ∈ ℤ}` equals `Lp ℝ 2 μ` — then `lpMeas 𝒪_h 2 μ`
is dense.

**Proof sketch:**
1. Each `h ∘ T^[n.toNat]` is `𝒪_h`-measurable (`observableAlgebra_measurable`),
   so `(hmem n).toLp _ ∈ lpMeas 𝒪_h`.
2. `cyclicSpan ≤ lpMeas 𝒪_h` as submodules of `Lp ℝ 2 μ`.
3. Monotonicity of closure: `cyclicSpan.closure = ⊤ → lpMeas.closure = ⊤`.
4. `Submodule.topologicalClosure_eq_top_iff_dense`: closure `⊤` implies dense. -/
theorem cyclic_implies_dense
    (μ : Measure X) [IsFiniteMeasure μ]
    (h : X → ℝ) (T : X → X)
    (_hh : Measurable h) (_hT : Measurable T)
    (hmem : ∀ n : ℕ, MemLp (h ∘ T^[n]) 2 μ)
    (h_cyclic :
      (Submodule.span ℝ
        (Set.range (fun n : ℕ => (hmem n).toLp _))).topologicalClosure = ⊤) :
    Dense (lpMeas ℝ ℝ (observableAlgebra (fun n : ℤ => h ∘ T^[n.toNat])) 2 μ :
      Set (Lp ℝ 2 μ)) := by
  -- Step 1: each generator (hmem n).toLp _ is in lpMeas 𝒪_h.
  -- Reason: h ∘ T^[n] is AEStronglyMeasurable[𝒪_h] (from observableAlgebra_measurable).
  have hmem_lpMeas : ∀ n : ℕ,
      (hmem n).toLp (h ∘ T^[n]) ∈
        lpMeas ℝ ℝ (observableAlgebra (fun k : ℤ => h ∘ T^[k.toNat])) 2 μ := by
    intro n
    rw [mem_lpMeas_iff_aestronglyMeasurable]
    -- The Lp coercion is a.e. equal to h ∘ T^[n]; use congr to reduce to the function.
    rw [aestronglyMeasurable_congr (hmem n).coeFn_toLp]
    -- Now goal: AEStronglyMeasurable[𝒪_h] (h ∘ T^[n]) μ
    have hgen : h ∘ T^[n] = (fun k : ℤ => h ∘ T^[k.toNat]) (n : ℤ) := by
      simp [Int.toNat_natCast]
    rw [hgen]
    exact (observableAlgebra_measurable (fun k : ℤ => h ∘ T^[k.toNat]) (n : ℤ)).aestronglyMeasurable
  -- Step 2: cyclicSpan ≤ lpMeas 𝒪_h as submodules.
  have hspan_le :
      Submodule.span ℝ (Set.range (fun n : ℕ => (hmem n).toLp _)) ≤
        lpMeas ℝ ℝ (observableAlgebra (fun k : ℤ => h ∘ T^[k.toNat])) 2 μ := by
    apply Submodule.span_le.mpr
    rintro f ⟨n, rfl⟩
    exact hmem_lpMeas n
  -- Step 3: monotonicity of topological closure + h_cyclic → lpMeas closure = ⊤.
  rw [Submodule.dense_iff_topologicalClosure_eq_top]
  exact top_le_iff.mp (h_cyclic ▸ Submodule.topologicalClosure_mono hspan_le)
