/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: [Your Name]
-/
import Mathlib.MeasureTheory.MeasurableSpace.Basic
import Mathlib.MeasureTheory.Measure.MeasureSpaceDef
import Mathlib.MeasureTheory.Measure.Map
import Mathlib.MeasureTheory.Measure.Typeclasses.Probability
import Mathlib.MeasureTheory.Constructions.Projective
import Mathlib.MeasureTheory.Constructions.ProjectiveFamilyContent
import Mathlib.MeasureTheory.Measure.Regular
import Mathlib.Topology.MetricSpace.Polish
import Mathlib.MeasureTheory.Constructions.Polish.Basic
import Mathlib.Topology.Algebra.Order.LiminfLimsup
import Mathlib.Topology.Category.TopCat.Limits.Konig
import Mathlib.CategoryTheory.Filtered.Basic
import QuerySystem.QuerySystem

/-!
# Topological Query Systems

This file enriches the measurable query-system framework with topology, targeting the
topological/projective-limit route to the observational extension theorem.

## Motivation

The measurable extension route (in `QuerySystem.lean`) is blocked at the σ-subadditivity
step: proving `cylGen_addContent_isSigmaSubadditive` requires a common lower bound for
countably infinite families of query indices, which `LowerDirected` alone does not provide.

The classical resolution (Kolmogorov extension theorem) requires topological regularity of
the factor spaces — typically that outcome spaces are Polish (separable completely metrizable)
and the marginals are Radon probability measures.  This file explores that route.

## Relation to Mathlib

Mathlib (`MeasureTheory.Constructions.Projective`) already defines:
- `IsProjectiveMeasureFamily`: compatible families indexed by finite sets
- `IsProjectiveLimit`: global measure recovering all finite-dimensional marginals
- `IsProjectiveLimit.unique`: uniqueness of the projective limit

The Kolmogorov extension theorem (existence) is **explicitly noted as not yet in Mathlib**
(`ProjectiveFamilyContent.lean`, line 27).  Our formulation here is a parallel development
for the query-system setting, designed to make the required hypotheses precise.

## Architecture

1. `TopologicalQuery` — outcome space with topology + Borel measurable structure
2. `TopologicalRefine` — continuous (hence measurable) refinement map
3. `TopologicalQuerySystem` — preordered family of topological queries with coherent maps
4. Projective-limit topology on `Omega`
5. Continuity and measurability of `eval i`
6. Comparison: `sigmaQ` vs Borel σ-field on `Omega`
7. Statement of the topological extension theorem

## Key Mathlib theorem identified

The closest existing theorem is:
  `MeasureTheory.IsProjectiveLimit.unique`
  (Mathlib.MeasureTheory.Constructions.Projective, line 151)

For existence, the required result is the Kolmogorov extension theorem under Polish/Radon
hypotheses, which is not yet in Mathlib.  The best available Mathlib infrastructure is:
  `projectiveFamilyContent` (ProjectiveFamilyContent.lean)
  `IsSetRing.addContent_of_union` (SetAlgebra)
These provide the additive content; σ-subadditivity under Polish hypotheses is the gap.

## Alignment note

This branch carries `PolishQuery` (Polish outcome space) + `RadonCompatibleMarginals` as
hypotheses not present in the current note.tex.  These are the correct classical conditions
for the Kolmogorov extension theorem.
-/

open MeasureTheory TopologicalSpace
open scoped ENNReal

universe u v

namespace QuerySystem

variable (S : QuerySystem.{u, v})

/-! ## Step 2: Topologically enriched query spaces -/

/-- A topological query is a query whose outcome space carries a topology compatible with
    its measurable structure (i.e., the measurable structure is the Borel σ-field).

    This enriches `Query` with topology.  The Borel compatibility `BorelSpace` asserts
    that the `MeasurableSpace` instance equals the one generated by the topology.

    **Polish queries** (outcome space is Polish: separable and completely metrizable) are
    the classical condition for the Kolmogorov extension theorem. -/
structure TopologicalQuery extends Query.{u} where
  /-- The topology on the outcome space. -/
  instTop : TopologicalSpace Outcome
  /-- The measurable structure is the Borel σ-field of the topology. -/
  borel : @BorelSpace Outcome instTop instMeas

attribute [instance] TopologicalQuery.instTop

/-- A Polish query: outcome space is Polish (separable, completely metrizable). -/
structure PolishQuery extends TopologicalQuery.{u} where
  /-- The outcome space is Polish. -/
  polish : @PolishSpace Outcome instTop

/-! ## Step 3: Topological refinement maps -/

/-- A topological refinement between topological queries: a map that is both continuous
    and measurable.

    Continuity implies measurability when the measurable structures are Borel
    (via `Continuous.measurable`), so `measurable_π` is redundant in that case.
    We include both for clarity and flexibility. -/
structure TopologicalRefine (q₁ q₂ : TopologicalQuery.{u}) extends Refine q₁.toQuery q₂.toQuery where
  /-- The map is continuous. -/
  continuous_π : @Continuous q₁.Outcome q₂.Outcome q₁.instTop q₂.instTop π

/-- A topological refinement is measurable (from continuity + Borel compatibility). -/
lemma TopologicalRefine.measurable {q₁ q₂ : TopologicalQuery.{u}}
    (r : TopologicalRefine q₁ q₂) : Measurable r.π := by
  haveI : OpensMeasurableSpace q₁.Outcome := @BorelSpace.opensMeasurable _ q₁.instTop _ q₁.borel
  haveI : BorelSpace q₂.Outcome := q₂.borel
  exact r.continuous_π.measurable

/-! ## Step 4: Topological query systems -/

/-- A topological query system: a preordered family of topological queries with coherent
    continuous refinement maps.

    This parallels `QuerySystem` but with topological structure on each factor space.
    The measurable core (Omega, eval, Cyl, sigmaQ) is inherited by forgetting topology. -/
structure TopologicalQuerySystem where
  /-- Index type. -/
  ι : Type v
  /-- Topological query at each index. -/
  q : ι → TopologicalQuery.{u}
  /-- Preorder on indices (coarse-to-fine). -/
  le : ι → ι → Prop
  /-- Topological refinement maps (fine-to-coarse / projective convention). -/
  π : ∀ {i j : ι}, le i j → TopologicalRefine (q j) (q i)

  le_refl  : ∀ i, le i i
  le_trans : ∀ {i j k}, le i j → le j k → le i k

  π_refl  : ∀ i, (π (le_refl i)).π = id
  π_trans : ∀ {i j k} (hij : le i j) (hjk : le j k),
      (π (le_trans hij hjk)).π = (π hij).π ∘ (π hjk).π

/-- Forget topology: a `TopologicalQuerySystem` gives a `QuerySystem`.

    The refinement map direction is preserved: `T.π hij : TopologicalRefine (q j) (q i)`
    forgets to `Refine (q j).toQuery (q i).toQuery`, matching the projective convention. -/
def TopologicalQuerySystem.toQuerySystem (T : TopologicalQuerySystem.{u, v}) : QuerySystem.{u, v} where
  ι        := T.ι
  q        := fun i => (T.q i).toQuery
  le       := T.le
  π        := fun hij => (T.π hij).toRefine
  le_refl  := T.le_refl
  le_trans := T.le_trans
  π_refl   := T.π_refl
  π_trans  := T.π_trans

/-! ## Step 5: Projective-limit topology on Omega -/

/-- Each outcome space of a `TopologicalQuerySystem`, accessed via the forgetful
    `toQuerySystem`, carries the topology from the original `TopologicalQuery`.
    This instance bridges the `T.toQuerySystem.q i` path to the `T.q i` path
    for instance synthesis. -/
instance TopologicalQuerySystem.instTopOutcome (T : TopologicalQuerySystem.{u, v}) (i : T.ι) :
    TopologicalSpace (T.toQuerySystem.q i).Outcome :=
  (T.q i).instTop

/-- The ambient product topology on `∀ i, (T.q i).Outcome`. -/
instance TopologicalQuerySystem.instTopProd (T : TopologicalQuerySystem.{u, v}) :
    TopologicalSpace (∀ i : T.ι, (T.q i).Outcome) :=
  Pi.topologicalSpace

/-- The projective-limit `Omega` with the subtype (induced) topology from the product. -/
instance TopologicalQuerySystem.instTopOmega (T : TopologicalQuerySystem.{u, v}) :
    TopologicalSpace T.toQuerySystem.Omega :=
  inferInstanceAs (TopologicalSpace { x : ∀ i, (T.q i).Outcome // _ })

/-! ## Step 6: Evaluation maps are continuous and measurable -/

/-- Evaluation at query `i` is continuous with respect to the projective-limit topology.

    **Proof:** `eval i` is the composition of the subtype coercion (continuous)
    with the `i`-th product projection (continuous). -/
theorem TopologicalQuerySystem.continuous_eval (T : TopologicalQuerySystem.{u, v}) (i : T.ι) :
    Continuous (T.toQuerySystem.eval i) := by
  -- T.toQuerySystem.q i = (T.q i).toQuery : Query, so the return type is
  -- T.toQuerySystem.Omega → (T.q i).toQuery.Outcome. The topology on this type is
  -- (T.q i).instTop, which is registered via T.instTopProd. We introduce it explicitly.
  -- instTopOutcome provides TopologicalSpace (T.toQuerySystem.q i).Outcome globally.
  unfold QuerySystem.eval
  exact (continuous_apply i).comp continuous_subtype_val

/-- Evaluation at query `i` is measurable with respect to `sigmaQ`.

    This follows from `measurable_eval` in the base `QuerySystem` module. -/
theorem TopologicalQuerySystem.measurable_eval' (T : TopologicalQuerySystem.{u, v}) (i : T.ι) :
    Measurable (T.toQuerySystem.eval i) :=
  T.toQuerySystem.measurable_eval i

/-! ## Step 7: Borel σ-field comparison -/

/-- The observable σ-field `sigmaQ` is contained in the Borel σ-field of the
    projective-limit topology on `Omega`.

    **Proof:** Since `eval i` is continuous (`continuous_eval`), it is Borel-measurable
    as a map `(Omega, Borel(Omega)) → (Outcome_i, Borel(Outcome_i))`.  Each generator
    `Cyl i A = eval i ⁻¹' A` of `sigmaQ` is therefore Borel-measurable in `Omega`
    whenever `A` is Borel-measurable in `Outcome_i` (which holds by the `BorelSpace`
    assumption on `TopologicalQuery`).

    **Note on the reverse inclusion:** `Borel(Omega) ≤ sigmaQ` would hold if `Omega`'s
    topology is itself generated by the evaluation maps (which is true here — the subtype
    of a product is generated by coordinate projections).  That direction is left as a
    future lemma; it would give `sigmaQ = Borel(Omega)` and confirm that the observable
    σ-field is exactly the Borel structure of the observational horizon. -/
lemma TopologicalQuerySystem.sigmaQ_le_borel (T : TopologicalQuerySystem.{u, v}) :
    T.toQuerySystem.sigmaQ ≤ @borel T.toQuerySystem.Omega T.instTopOmega := by
  -- It suffices to show each generator Cyl i A of sigmaQ is Borel-measurable in Omega.
  -- We show sigmaQ ≤ borel Omega by showing each generator Cyl i A is Borel-measurable.
  -- Cyl i A = eval i ⁻¹' A. Since eval i is continuous (continuous_eval), it is
  -- measurable from (Omega, borel Omega) to (Outcome_i, borel Outcome_i).
  -- A ∈ borel Outcome_i (= instMeas by BorelSpace), so Cyl i A is Borel-measurable in Omega.
  -- Strategy: show Cyl i A is measurable in borel Omega directly from continuity of eval i,
  -- using that borel is generated by open sets and preimages of opens are open.
  -- Equivalently: eval i is continuous, Borel(Omega) is the Borel σ-field of the topology,
  -- so eval i is (Borel, Borel)-measurable, and A is Borel in Outcome_i.
  -- Direct route: borel Omega = generateFrom (opens of Omega); eval i ⁻¹' A is measurable
  -- in any σ-field making eval i measurable, in particular in borel Omega.
  -- We use: (T.continuous_eval i) gives continuity; continuity → measurability when
  -- domain has OpensMeasurableSpace (= borel generated by opens ≤ measurable space).
  -- But borel Omega IS the Borel σ-field, so OpensMeasurableSpace holds for borel Omega.
  apply MeasurableSpace.generateFrom_le
  rintro E ⟨i, A, hA, rfl⟩
  -- E = Cyl i A = (eval i) ⁻¹' A.
  -- eval i is continuous, so by Continuous.borel_measurable it is measurable
  -- from (Omega, borel Omega) to ((T.q i).Outcome, borel (T.q i).Outcome).
  -- A ∈ instMeas = borel (T.q i).Outcome (by BorelSpace), so the preimage is Borel in Omega.
  have hmeas_eval : @Measurable T.toQuerySystem.Omega (T.q i).Outcome
      (borel T.toQuerySystem.Omega) (borel (T.q i).Outcome)
      (T.toQuerySystem.eval i) :=
    (T.continuous_eval i).borel_measurable
  -- A is in instMeas = borel(T.q i).Outcome by BorelSpace
  have hA_borel : @MeasurableSet (T.q i).Outcome (borel (T.q i).Outcome) A :=
    (T.q i).borel.measurable_eq ▸ hA
  exact hmeas_eval hA_borel

/-! ## Step 8: Topological observational extension theorem (skeleton) -/

/-- **Polish query system**: all outcome spaces are Polish.

    This is the classical Kolmogorov condition for the extension theorem to hold.
    A Polish space is separable and completely metrizable. -/
def TopologicalQuerySystem.IsPolish (T : TopologicalQuerySystem.{u, v}) : Prop :=
  ∀ i : T.ι, @PolishSpace (T.q i).Outcome (T.q i).instTop

/-- Compatible Radon probability marginals: the family `ν` is compatible with refinement,
    and each `ν i` is inner regular with respect to compact sets (Radon).

    **Design note:** This bundles compatibility + Radon regularity explicitly.  On Polish
    outcome spaces, inner regularity of probability measures is automatic
    (every Borel probability measure on a Polish space is Radon; this is a theorem in
    Mathlib under `MeasureTheory.Measure.innerRegular_of_polishSpace` or similar).
    We state it explicitly here as hypothesis data rather than deriving it, for two reasons:

    1. It keeps the extension theorem self-contained without requiring `IsPolish` as a
       separate hypothesis (one could have Radon measures on non-Polish spaces).
    2. It anticipates future refactoring: once the connection `IsPolish → Radon` is used
       directly in the proof, this bundled form can be replaced by `CompatibleMarginals`
       alone (with `IsPolish` supplying the Radon property automatically).

    **Current role:** explicit hypothesis data for `topological_observational_extension`.
    **Future role:** theorem consequence of `IsPolish + CompatibleMarginals`. -/
def TopologicalQuerySystem.RadonCompatibleMarginals
    (T : TopologicalQuerySystem.{u, v})
    (ν : ∀ i : T.ι, Measure ((T.q i).Outcome)) : Prop :=
  T.toQuerySystem.CompatibleMarginals ν ∧
  ∀ i : T.ι,
    letI := (T.q i).instTop
    letI := (T.q i).instMeas
    IsFiniteMeasure (ν i) ∧ Measure.InnerRegular (ν i)

/-- **Topological Observational Extension Theorem (skeleton).**

    Under the classical Kolmogorov hypotheses — lower-directedness, compatible Radon
    probability marginals, and Polish outcome spaces — there should exist a unique
    probability measure on `Omega` recovering all marginals.

    **Status:** Theorem skeleton; the existence proof requires the Kolmogorov extension
    theorem, which is **not yet in Mathlib** (explicitly noted in
    `Mathlib.MeasureTheory.Constructions.ProjectiveFamilyContent`, line 27).

    **What IS in Mathlib:**
    - `MeasureTheory.IsProjectiveLimit.unique` — uniqueness (Projective.lean:151)
    - `MeasureTheory.projectiveFamilyContent` — additive content on measurable cylinders
      (ProjectiveFamilyContent.lean:117)
    - `MeasureTheory.IsTightMeasureSet` — tightness (Tight.lean:55)
    - `MeasureTheory.isCompact_closure_of_isTightMeasureSet` — Prokhorov (Prokhorov.lean:497)

    **The precise remaining gap:**
    The σ-subadditivity of `projectiveFamilyContent` under Polish/Radon hypotheses is the
    missing step.  This corresponds exactly to the Kolmogorov extension theorem.  Once
    Mathlib formalizes it, this theorem should follow as a corollary after translating our
    `TopologicalQuerySystem` data into `IsProjectiveMeasureFamily` form.

    **Hypotheses vs. note.tex:**
    - `dir : LowerDirected` — present in note.tex
    - `compat + Radon` — `CompatibleMarginals` is present; Radon is extra
    - `IsPolish` — not present in note.tex; this is the topological alignment gap

    **Reduction path to Mathlib (once Kolmogorov is formalized):**
    1. From `T : TopologicalQuerySystem` with `dir` and Polish outcome spaces,
       construct `P_fin : ∀ J : Finset T.ι, Measure (∀ j : J, (T.q j).Outcome)` by
       compressing the compatible marginals to finite products.
    2. Verify `IsProjectiveMeasureFamily P_fin`.
    3. Apply the Kolmogorov extension theorem (once available in Mathlib) to get
       `P : Measure (∀ i, (T.q i).Outcome)` with `IsProjectiveLimit P P_fin`.
    4. Restrict `P` to `Omega ⊆ ∀ i, (T.q i).Outcome` (measure-theoretically,
       show `P Omegaᶜ = 0` using compatibility).
    5. The restricted measure has the required marginals by `IsProjectiveLimit`. -/
theorem topological_observational_extension
    (T : TopologicalQuerySystem.{u, v})
    [Nonempty T.ι]
    (dir : T.toQuerySystem.LowerDirected)
    (polish : T.IsPolish)
    (ν : ∀ i : T.ι, Measure ((T.q i).Outcome))
    (radon_compat : T.RadonCompatibleMarginals ν)
    [∀ i, IsProbabilityMeasure (ν i)] :
    ∃ P : Measure T.toQuerySystem.Omega,
      IsProbabilityMeasure P ∧
      ∀ i : T.ι, Measure.map (T.toQuerySystem.eval i) P = ν i := by
  -- Uniqueness would follow from observational_determination (already proved in the
  -- measurable core), since the projective-limit topology makes sigmaQ separating.
  -- Existence requires the Kolmogorov extension theorem (not yet in Mathlib).
  -- See reduction path in the docstring above.
  sorry

/-! ## SP3 positive companion: EvalSurjective from compact T2 + surjective refinements

The positive companion to the SP3 independence result. `EvalSurjective` is NOT provable
in the abstract `QuerySystem` framework from surjectivity of refinement maps alone — the
abstract inverse limit theorem requires compactness. Here we prove it in the compact T2
setting via a direct compactness argument using Tychonoff + closed fiber sets.

### Strategy

**Omega is compact:** `T.toQuerySystem.Omega` embeds as a closed subspace of
`∏ j, (T.q j).Outcome` (compact by Tychonoff). Each coherence condition
`x i = (π hij).π (x j)` is closed (T2 + continuity of π). So `Omega` is compact.

**EvalSurjective via fiber compactness:** For `y : (T.q i).Outcome`, the fiber
`{ ω : Omega | ω.1 i = y }` = `(eval i)⁻¹ {y}` is closed in compact `Omega`,
hence compact. We show it is nonempty using a finite intersection argument:
- For any finite set of constraints (levels `j₁, ..., jₙ`), we can find a partial
  section satisfying all of them and mapping to `y` at level `i`, using surjectivity
  of the refinement maps and upper-directedness to build a coherent assignment on
  any finite sub-index-set.
- This gives a directed family of nonempty compact closed sets; the intersection is
  nonempty, providing the required `ω`.

**Mathlib theorems used:**
- `Pi.compactSpace` / `Tychonoff` for product compactness
- `IsClosed.isCompact` for closed subsets of compact spaces
- `IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed`
  (Mathlib.Topology.Compactness.Compact) for the intersection argument
-/

/-! ### Omega is a closed subset of the product -/

/-- The `Omega` of a `TopologicalQuerySystem` is the intersection of closed sets
    in the product `∏ j, (T.q j).Outcome`, one for each coherence constraint. -/
theorem TopologicalQuerySystem.isClosed_omega
    (T : TopologicalQuerySystem.{u, v})
    [∀ i, T2Space (T.q i).Outcome] :
    IsClosed {x : ∀ j : T.ι, (T.q j).Outcome |
      ∀ {i j} (hij : T.le i j), x i = (T.π hij).π (x j)} := by
  -- Rewrite as an explicit iInter over the sigma type of all coherence constraints.
  -- Each constraint { x | x i = (π hij).π (x j) } is closed because it's the preimage
  -- of the diagonal under a continuous map into a T2 space.
  -- Rewrite as iInter over the subtype of all pairs (i, j) with T.le i j.
  -- Use isClosed_eq to close each constraint: {x | x i = (π hij).π (x j)} is closed
  -- because both sides are continuous functions into a T2 space.
  have heq : {x : ∀ j : T.ι, (T.q j).Outcome |
        ∀ {i j} (hij : T.le i j), x i = (T.π hij).π (x j)} =
      ⋂ (p : {p : T.ι × T.ι // T.le p.1 p.2}),
        {x | x p.1.1 = (T.π p.2).π (x p.1.2)} := by
    ext x
    simp only [Set.mem_setOf_eq, Set.mem_iInter, Subtype.forall, Prod.forall]
  rw [heq]
  apply isClosed_iInter
  intro ⟨⟨i, j⟩, hij⟩
  -- {x | x i = (π hij).π (x j)} is closed by isClosed_eq + continuity
  exact isClosed_eq (continuous_apply i) ((T.π hij).continuous_π.comp (continuous_apply j))

/-- `Omega` of a compact T2 `TopologicalQuerySystem` is compact. -/
theorem TopologicalQuerySystem.isCompact_omega
    (T : TopologicalQuerySystem.{u, v})
    [∀ i, CompactSpace (T.q i).Outcome]
    [∀ i, T2Space (T.q i).Outcome] :
    IsCompact {x : ∀ j : T.ι, (T.q j).Outcome |
      ∀ {i j} (hij : T.le i j), x i = (T.π hij).π (x j)} := by
  exact (T.isClosed_omega).isCompact

/-! ### EvalSurjective: the fiber is nonempty -/

/-- **SP3 Positive Companion (compact T2 case).**

    If a `TopologicalQuerySystem` has compact T2 outcome spaces, continuous surjective
    refinement maps, and is upper-directed, then `EvalSurjective` holds for the
    underlying `QuerySystem`.

    **Proof sketch:**
    For `y : (T.q i).Outcome`, the fiber `(eval i)⁻¹ {y}` is closed in the compact
    space `Omega`, hence compact. Nonemptiness follows from a finite intersection
    argument: any finite collection of levels `j₁, ..., jₙ` can be resolved to a
    common upper bound `k` (by iterated `UpperDirected`), and surjectivity of `π_{ik}`
    gives a preimage `x_k` of `y`; projecting down gives a partial assignment
    consistent with all `j₁, ..., jₙ`. The intersection of the resulting closed sets
    is nonempty.

    **Mathlib theorem used:**
    `TopCat.nonempty_limitCone_of_compact_t2_cofiltered_system`
    is the categorical form; we use the underlying compactness argument directly. -/
theorem TopologicalQuerySystem.evalSurjective_of_compact_t2
    (T : TopologicalQuerySystem.{u, v})
    (udir : T.toQuerySystem.UpperDirected)
    [hNE : Nonempty T.ι]
    [∀ i, Nonempty (T.q i).Outcome]
    [∀ i, CompactSpace (T.q i).Outcome]
    [∀ i, T2Space (T.q i).Outcome]
    (hπ_surj : ∀ {i j : T.ι} (hij : T.le i j), Function.Surjective (T.π hij).π) :
    T.toQuerySystem.EvalSurjective := by
  classical
  intro i y
  -- We work in the ambient product P := ∀ j, (T.q j).Outcome, which is compact by Tychonoff.
  -- For each s : Finset T.ι, define the partial-coherence set:
  --   C s = { x : P | x i = y  ∧
  --             ∀ a ∈ s, ∀ b ∈ s, ∀ (hab : T.le a b), x a = (T.π hab).π (x b) }
  -- Each C s is closed, nonempty, and the family is directed (C (s ∪ t) ⊆ C s, C t).
  -- By Cantor's intersection theorem, ⋂ s, C s is nonempty; any element is in Omega with value y.
  haveI : Nonempty (Finset T.ι) := ⟨∅⟩
  -- Lift T.toQuerySystem.UpperDirected to T.ι directly
  have udir' : ∀ a b : T.ι, ∃ k : T.ι, T.le a k ∧ T.le b k := udir
  -- The partial-coherence set at finite s
  let C : Finset T.ι → Set (∀ j : T.ι, (T.q j).Outcome) := fun s =>
    { x | x i = y ∧ ∀ a ∈ s, ∀ b ∈ s, ∀ (hab : T.le a b), x a = (T.π hab).π (x b) }
  -- Step 1: Each C s is closed.
  have hC_closed : ∀ s, IsClosed (C s) := by
    intro s
    have heq : C s = {x | x i = y} ∩
        ⋂ (p : {p : T.ι × T.ι // p.1 ∈ s ∧ p.2 ∈ s ∧ T.le p.1 p.2}),
          {x | x p.1.1 = (T.π p.2.2.2).π (x p.1.2)} := by
      ext x
      simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Set.mem_iInter, Subtype.forall,
        Prod.forall, C]
      constructor
      · rintro ⟨hxi, hcoh⟩
        exact ⟨hxi, fun a b ⟨ha, hb, hab⟩ => hcoh a ha b hb hab⟩
      · rintro ⟨hxi, hcoh⟩
        exact ⟨hxi, fun a ha b hb hab => hcoh a b ⟨ha, hb, hab⟩⟩
    rw [heq]
    apply IsClosed.inter
    · -- {x | x i = y} is closed: preimage of {y} under the i-th projection, which is closed in T2
      have : {x : ∀ j : T.ι, (T.q j).Outcome | x i = y} =
          (fun x : ∀ j : T.ι, (T.q j).Outcome => x i) ⁻¹' {y} := by
        ext; simp
      rw [this]
      exact IsClosed.preimage (continuous_apply i) (isClosed_singleton)
    · apply isClosed_iInter
      rintro ⟨⟨a, b⟩, -, -, hab⟩
      exact isClosed_eq (continuous_apply a) ((T.π hab).continuous_π.comp (continuous_apply b))
  -- Step 2: Each C s is nonempty.
  -- Find k above i and all of s, lift y to level k, project down everywhere.
  -- Coherence: if a, b ∈ s with T.le a b, T.le a k and T.le b k, so
  --   (T.π hab).π (x b) = (T.π (T.le_trans hab hbk)).π xk   [by π_trans]
  --                     = (T.π hak).π xk = x a               [proof irrelevance of Prop]
  have hC_nonempty : ∀ s, (C s).Nonempty := by
    intro s
    -- upperBound_finset needs Nonempty T.ι, which is hNE = hNE (at T.ι level)
    -- T.toQuerySystem.ι = T.ι, so hNE gives Nonempty T.toQuerySystem.ι
    haveI : Nonempty T.toQuerySystem.ι := hNE
    obtain ⟨k, hk⟩ := T.toQuerySystem.upperBound_finset udir (insert i s)
    -- hk : ∀ j ∈ insert i s, T.le j k
    have hik : T.le i k := hk i (Finset.mem_insert_self i s)
    obtain ⟨xk, hxk⟩ := hπ_surj hik y
    -- Use Classical decidability for the if-then-else on T.le j k
    classical
    refine ⟨fun j => if hjk : T.le j k then (T.π hjk).π xk else Classical.arbitrary _, ?_, ?_⟩
    · -- x i = y: the condition T.le i k holds (= hik), so x i = (T.π hik).π xk = y
      simp only [dif_pos hik]
      exact hxk
    · intro a ha b hb hab
      have hak : T.le a k := hk a (Finset.mem_insert_of_mem ha)
      have hbk : T.le b k := hk b (Finset.mem_insert_of_mem hb)
      simp only [dif_pos hak, dif_pos hbk]
      -- Goal: (T.π hak).π xk = (T.π hab).π ((T.π hbk).π xk)
      -- π_trans gives: (T.π (le_trans hab hbk)).π = (T.π hab).π ∘ (T.π hbk).π
      -- proof irrelevance: le_trans hab hbk = hak (both : T.le a k)
      -- (T.π hak).π xk = (T.π (le_trans hab hbk)).π xk    [proof irrelevance]
      --                = ((T.π hab).π ∘ (T.π hbk).π) xk   [by π_trans]
      --                = (T.π hab).π ((T.π hbk).π xk)
      have htrans := T.toQuerySystem.π_trans hab hbk
      -- htrans : (T.π (le_trans hab hbk)).π = (T.π hab).π ∘ (T.π hbk).π
      have hirrel : T.toQuerySystem.le_trans hab hbk = hak := proof_irrel _ _
      calc (T.π hak).π xk
          = (T.π (T.toQuerySystem.le_trans hab hbk)).π xk := by rw [hirrel]
        _ = ((T.π hab).π ∘ (T.π hbk).π) xk := congr_fun htrans xk
        _ = (T.π hab).π ((T.π hbk).π xk) := rfl
  -- Step 3: The family C is directed: C (s ∪ t) ⊆ C s and C t.
  have hC_directed : _root_.Directed (· ⊇ ·) C := by
    intro s t
    refine ⟨s ∪ t, ?_, ?_⟩
    · intro x ⟨hxi, hcoh⟩
      exact ⟨hxi, fun a ha b hb hab =>
        hcoh a (Finset.mem_union_left t ha) b (Finset.mem_union_left t hb) hab⟩
    · intro x ⟨hxi, hcoh⟩
      exact ⟨hxi, fun a ha b hb hab =>
        hcoh a (Finset.mem_union_right s ha) b (Finset.mem_union_right s hb) hab⟩
  -- Step 4: Cantor intersection theorem gives a point in ⋂ s, C s.
  obtain ⟨x, hx⟩ := IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed
    C hC_directed hC_nonempty (fun s => (hC_closed s).isCompact) hC_closed
  simp only [Set.mem_iInter] at hx
  -- Step 5: x i = y (from s = ∅) and full coherence (from s = {a, b}).
  have hxi : x i = y := (hx ∅).1
  have hxcoh : ∀ {a b : T.ι} (hab : T.le a b), x a = (T.π hab).π (x b) :=
    fun {a} {b} hab => (hx {a, b}).2 a (Finset.mem_insert_self a _) b
      (Finset.mem_insert.mpr (Or.inr (Finset.mem_singleton_self b))) hab
  exact ⟨⟨x, fun {a} {b} hab => hxcoh hab⟩, hxi⟩

end QuerySystem
