/-
Copyright (c) 2025. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: [Your Name]
-/
import Mathlib.MeasureTheory.MeasurableSpace.Basic
import Mathlib.MeasureTheory.Measure.MeasureSpaceDef
import Mathlib.MeasureTheory.Measure.Map
import Mathlib.MeasureTheory.Measure.Typeclasses.Probability
import Mathlib.MeasureTheory.Constructions.Projective
import Mathlib.MeasureTheory.Constructions.ProjectiveFamilyContent
import Mathlib.MeasureTheory.Measure.Regular
import Mathlib.Topology.MetricSpace.Polish
import Mathlib.MeasureTheory.Constructions.Polish.Basic
import Mathlib.Topology.Algebra.Order.LiminfLimsup
import QuerySystem.QuerySystem

/-!
# Topological Query Systems

This file enriches the measurable query-system framework with topology, targeting the
topological/projective-limit route to the observational extension theorem.

## Motivation

The measurable extension route (in `QuerySystem.lean`) is blocked at the σ-subadditivity
step: proving `cylGen_addContent_isSigmaSubadditive` requires a common lower bound for
countably infinite families of query indices, which `LowerDirected` alone does not provide.

The classical resolution (Kolmogorov extension theorem) requires topological regularity of
the factor spaces — typically that outcome spaces are Polish (separable completely metrizable)
and the marginals are Radon probability measures.  This file explores that route.

## Relation to Mathlib

Mathlib (`MeasureTheory.Constructions.Projective`) already defines:
- `IsProjectiveMeasureFamily`: compatible families indexed by finite sets
- `IsProjectiveLimit`: global measure recovering all finite-dimensional marginals
- `IsProjectiveLimit.unique`: uniqueness of the projective limit

The Kolmogorov extension theorem (existence) is **explicitly noted as not yet in Mathlib**
(`ProjectiveFamilyContent.lean`, line 27).  Our formulation here is a parallel development
for the query-system setting, designed to make the required hypotheses precise.

## Architecture

1. `TopologicalQuery` — outcome space with topology + Borel measurable structure
2. `TopologicalRefine` — continuous (hence measurable) refinement map
3. `TopologicalQuerySystem` — preordered family of topological queries with coherent maps
4. Projective-limit topology on `Omega`
5. Continuity and measurability of `eval i`
6. Comparison: `sigmaQ` vs Borel σ-field on `Omega`
7. Statement of the topological extension theorem

## Key Mathlib theorem identified

The closest existing theorem is:
  `MeasureTheory.IsProjectiveLimit.unique`
  (Mathlib.MeasureTheory.Constructions.Projective, line 151)

For existence, the required result is the Kolmogorov extension theorem under Polish/Radon
hypotheses, which is not yet in Mathlib.  The best available Mathlib infrastructure is:
  `projectiveFamilyContent` (ProjectiveFamilyContent.lean)
  `IsSetRing.addContent_of_union` (SetAlgebra)
These provide the additive content; σ-subadditivity under Polish hypotheses is the gap.

## Alignment note

This branch carries `PolishQuery` (Polish outcome space) + `RadonCompatibleMarginals` as
hypotheses not present in the current note.tex.  These are the correct classical conditions
for the Kolmogorov extension theorem.
-/

open MeasureTheory TopologicalSpace
open scoped ENNReal

universe u v

namespace QuerySystem

variable (S : QuerySystem.{u, v})

/-! ## Step 2: Topologically enriched query spaces -/

/-- A topological query is a query whose outcome space carries a topology compatible with
    its measurable structure (i.e., the measurable structure is the Borel σ-field).

    This enriches `Query` with topology.  The Borel compatibility `BorelSpace` asserts
    that the `MeasurableSpace` instance equals the one generated by the topology.

    **Polish queries** (outcome space is Polish: separable and completely metrizable) are
    the classical condition for the Kolmogorov extension theorem. -/
structure TopologicalQuery extends Query.{u} where
  /-- The topology on the outcome space. -/
  instTop : TopologicalSpace Outcome
  /-- The measurable structure is the Borel σ-field of the topology. -/
  borel : @BorelSpace Outcome instTop instMeas

attribute [instance] TopologicalQuery.instTop

/-- A Polish query: outcome space is Polish (separable, completely metrizable). -/
structure PolishQuery extends TopologicalQuery.{u} where
  /-- The outcome space is Polish. -/
  polish : @PolishSpace Outcome instTop

/-! ## Step 3: Topological refinement maps -/

/-- A topological refinement between topological queries: a map that is both continuous
    and measurable.

    Continuity implies measurability when the measurable structures are Borel
    (via `Continuous.measurable`), so `measurable_π` is redundant in that case.
    We include both for clarity and flexibility. -/
structure TopologicalRefine (q₁ q₂ : TopologicalQuery.{u}) extends Refine q₁.toQuery q₂.toQuery where
  /-- The map is continuous. -/
  continuous_π : @Continuous q₁.Outcome q₂.Outcome q₁.instTop q₂.instTop π

/-- A topological refinement is measurable (from continuity + Borel compatibility). -/
lemma TopologicalRefine.measurable {q₁ q₂ : TopologicalQuery.{u}}
    (r : TopologicalRefine q₁ q₂) : Measurable r.π :=
  r.continuous_π.measurable

/-! ## Step 4: Topological query systems -/

/-- A topological query system: a preordered family of topological queries with coherent
    continuous refinement maps.

    This parallels `QuerySystem` but with topological structure on each factor space.
    The measurable core (Omega, eval, Cyl, sigmaQ) is inherited by forgetting topology. -/
structure TopologicalQuerySystem where
  /-- Index type. -/
  ι : Type v
  /-- Topological query at each index. -/
  q : ι → TopologicalQuery.{u}
  /-- Preorder on indices (coarse-to-fine). -/
  le : ι → ι → Prop
  /-- Topological refinement maps (fine-to-coarse / projective convention). -/
  π : ∀ {i j : ι}, le i j → TopologicalRefine (q j) (q i)

  le_refl  : ∀ i, le i i
  le_trans : ∀ {i j k}, le i j → le j k → le i k

  π_refl  : ∀ i, (π (le_refl i)).π = id
  π_trans : ∀ {i j k} (hij : le i j) (hjk : le j k),
      (π (le_trans hij hjk)).π = (π hij).π ∘ (π hjk).π

/-- Forget topology: a `TopologicalQuerySystem` gives a `QuerySystem`.

    The refinement map direction is preserved: `T.π hij : TopologicalRefine (q j) (q i)`
    forgets to `Refine (q j).toQuery (q i).toQuery`, matching the projective convention. -/
def TopologicalQuerySystem.toQuerySystem (T : TopologicalQuerySystem.{u, v}) : QuerySystem.{u, v} where
  ι        := T.ι
  q        := fun i => (T.q i).toQuery
  le       := T.le
  π        := fun hij => (T.π hij).toRefine
  le_refl  := T.le_refl
  le_trans := T.le_trans
  π_refl   := T.π_refl
  π_trans  := T.π_trans

/-! ## Step 5: Projective-limit topology on Omega -/

/-- The ambient product topology on `∀ i, (T.q i).Outcome`. -/
instance TopologicalQuerySystem.instTopProd (T : TopologicalQuerySystem.{u, v}) :
    TopologicalSpace (∀ i : T.ι, (T.q i).Outcome) :=
  Pi.topologicalSpace

/-- The projective-limit `Omega` with the subtype (induced) topology from the product. -/
instance TopologicalQuerySystem.instTopOmega (T : TopologicalQuerySystem.{u, v}) :
    TopologicalSpace T.toQuerySystem.Omega :=
  inferInstanceAs (TopologicalSpace { x : ∀ i, (T.q i).Outcome // _ })

/-! ## Step 6: Evaluation maps are continuous and measurable -/

/-- Evaluation at query `i` is continuous with respect to the projective-limit topology.

    **Proof:** `eval i` is the composition of the subtype coercion (continuous)
    with the `i`-th product projection (continuous). -/
theorem TopologicalQuerySystem.continuous_eval (T : TopologicalQuerySystem.{u, v}) (i : T.ι) :
    Continuous (T.toQuerySystem.eval i) := by
  -- eval i = (fun ω => ω.1 i) = Pi.evalₓ i ∘ Subtype.val
  -- Subtype.val is continuous, Pi.eval is continuous
  exact (continuous_apply i).comp continuous_subtype_val

/-- Evaluation at query `i` is measurable with respect to `sigmaQ`.

    This follows from `measurable_eval` in the base `QuerySystem` module. -/
theorem TopologicalQuerySystem.measurable_eval' (T : TopologicalQuerySystem.{u, v}) (i : T.ι) :
    Measurable (T.toQuerySystem.eval i) :=
  T.toQuerySystem.measurable_eval i

/-! ## Step 7: Borel σ-field comparison -/

/-- The observable σ-field `sigmaQ` is contained in the Borel σ-field of the
    projective-limit topology on `Omega`.

    **Proof:** Since `eval i` is continuous (`continuous_eval`), it is Borel-measurable
    as a map `(Omega, Borel(Omega)) → (Outcome_i, Borel(Outcome_i))`.  Each generator
    `Cyl i A = eval i ⁻¹' A` of `sigmaQ` is therefore Borel-measurable in `Omega`
    whenever `A` is Borel-measurable in `Outcome_i` (which holds by the `BorelSpace`
    assumption on `TopologicalQuery`).

    **Note on the reverse inclusion:** `Borel(Omega) ≤ sigmaQ` would hold if `Omega`'s
    topology is itself generated by the evaluation maps (which is true here — the subtype
    of a product is generated by coordinate projections).  That direction is left as a
    future lemma; it would give `sigmaQ = Borel(Omega)` and confirm that the observable
    σ-field is exactly the Borel structure of the observational horizon. -/
lemma TopologicalQuerySystem.sigmaQ_le_borel (T : TopologicalQuerySystem.{u, v}) :
    T.toQuerySystem.sigmaQ ≤ @borel T.toQuerySystem.Omega T.instTopOmega := by
  -- It suffices to show each generator Cyl i A of sigmaQ is Borel-measurable in Omega.
  apply MeasurableSpace.generateFrom_le
  intro E ⟨i, A, hA, rfl⟩
  -- eval i is continuous, hence Borel-measurable (continuous → measurable on Borel spaces).
  -- A is measurable w.r.t. (T.q i).instMeas = Borel(Outcome_i) (by BorelSpace).
  -- Therefore Cyl i A = eval i ⁻¹' A is Borel-measurable in Omega.
  exact (T.continuous_eval i).measurable.measurableSet_preimage
    ((T.q i).borel.measurable_eq ▸ hA)

/-! ## Step 8: Topological observational extension theorem (skeleton) -/

/-- **Polish query system**: all outcome spaces are Polish.

    This is the classical Kolmogorov condition for the extension theorem to hold.
    A Polish space is separable and completely metrizable. -/
def TopologicalQuerySystem.IsPolish (T : TopologicalQuerySystem.{u, v}) : Prop :=
  ∀ i : T.ι, @PolishSpace (T.q i).Outcome (T.q i).instTop

/-- Compatible Radon probability marginals: the family `ν` is compatible with refinement,
    and each `ν i` is inner regular with respect to compact sets (Radon).

    **Design note:** This bundles compatibility + Radon regularity explicitly.  On Polish
    outcome spaces, inner regularity of probability measures is automatic
    (every Borel probability measure on a Polish space is Radon; this is a theorem in
    Mathlib under `MeasureTheory.Measure.innerRegular_of_polishSpace` or similar).
    We state it explicitly here as hypothesis data rather than deriving it, for two reasons:

    1. It keeps the extension theorem self-contained without requiring `IsPolish` as a
       separate hypothesis (one could have Radon measures on non-Polish spaces).
    2. It anticipates future refactoring: once the connection `IsPolish → Radon` is used
       directly in the proof, this bundled form can be replaced by `CompatibleMarginals`
       alone (with `IsPolish` supplying the Radon property automatically).

    **Current role:** explicit hypothesis data for `topological_observational_extension`.
    **Future role:** theorem consequence of `IsPolish + CompatibleMarginals`. -/
def TopologicalQuerySystem.RadonCompatibleMarginals
    (T : TopologicalQuerySystem.{u, v})
    (ν : ∀ i : T.ι, Measure ((T.q i).Outcome)) : Prop :=
  T.toQuerySystem.CompatibleMarginals ν ∧
  ∀ i : T.ι, @IsFiniteMeasure (T.q i).Outcome _ (ν i) ∧
    @Measure.InnerRegular (T.q i).Outcome _ (ν i) IsCompact

/-- **Topological Observational Extension Theorem (skeleton).**

    Under the classical Kolmogorov hypotheses — lower-directedness, compatible Radon
    probability marginals, and Polish outcome spaces — there should exist a unique
    probability measure on `Omega` recovering all marginals.

    **Status:** Theorem skeleton; the existence proof requires the Kolmogorov extension
    theorem, which is **not yet in Mathlib** (explicitly noted in
    `Mathlib.MeasureTheory.Constructions.ProjectiveFamilyContent`, line 27).

    **What IS in Mathlib:**
    - `MeasureTheory.IsProjectiveLimit.unique` — uniqueness (Projective.lean:151)
    - `MeasureTheory.projectiveFamilyContent` — additive content on measurable cylinders
      (ProjectiveFamilyContent.lean:117)
    - `MeasureTheory.IsTightMeasureSet` — tightness (Tight.lean:55)
    - `MeasureTheory.isCompact_closure_of_isTightMeasureSet` — Prokhorov (Prokhorov.lean:497)

    **The precise remaining gap:**
    The σ-subadditivity of `projectiveFamilyContent` under Polish/Radon hypotheses is the
    missing step.  This corresponds exactly to the Kolmogorov extension theorem.  Once
    Mathlib formalizes it, this theorem should follow as a corollary after translating our
    `TopologicalQuerySystem` data into `IsProjectiveMeasureFamily` form.

    **Hypotheses vs. note.tex:**
    - `dir : LowerDirected` — present in note.tex
    - `compat + Radon` — `CompatibleMarginals` is present; Radon is extra
    - `IsPolish` — not present in note.tex; this is the topological alignment gap

    **Reduction path to Mathlib (once Kolmogorov is formalized):**
    1. From `T : TopologicalQuerySystem` with `dir` and Polish outcome spaces,
       construct `P_fin : ∀ J : Finset T.ι, Measure (∀ j : J, (T.q j).Outcome)` by
       compressing the compatible marginals to finite products.
    2. Verify `IsProjectiveMeasureFamily P_fin`.
    3. Apply the Kolmogorov extension theorem (once available in Mathlib) to get
       `P : Measure (∀ i, (T.q i).Outcome)` with `IsProjectiveLimit P P_fin`.
    4. Restrict `P` to `Omega ⊆ ∀ i, (T.q i).Outcome` (measure-theoretically,
       show `P Omegaᶜ = 0` using compatibility).
    5. The restricted measure has the required marginals by `IsProjectiveLimit`. -/
theorem topological_observational_extension
    (T : TopologicalQuerySystem.{u, v})
    [Nonempty T.ι]
    (dir : T.toQuerySystem.LowerDirected)
    (polish : T.IsPolish)
    (ν : ∀ i : T.ι, Measure ((T.q i).Outcome))
    (radon_compat : T.RadonCompatibleMarginals ν)
    [∀ i, IsProbabilityMeasure (ν i)] :
    ∃ P : Measure T.toQuerySystem.Omega,
      IsProbabilityMeasure P ∧
      ∀ i : T.ι, Measure.map (T.toQuerySystem.eval i) P = ν i := by
  -- Uniqueness would follow from observational_determination (already proved in the
  -- measurable core), since the projective-limit topology makes sigmaQ separating.
  -- Existence requires the Kolmogorov extension theorem (not yet in Mathlib).
  -- See reduction path in the docstring above.
  sorry

end QuerySystem
