/-
# The Product Ulam Carrier — σ-side core (rigidity + empty kernel)

Formalizes the σ-side of the witness construction
(`papers/sigma_essential/witness_candidate/`, verified 2026-07-06):

* `UlamMatrix M` — an Ulam matrix on a linearly ordered `M` (row-disjoint,
  row-covering above the index, EXACTLY column-disjoint); existence
  (`ulamMatrix_exists` = Lem 2.1) from countability of initial segments.
* `carrier U` — the σ-class `L` generated by singletons, cells `C_{α,n} × F`,
  and the three cores `A = M×{0,1}`, `B = M×{0,2}`, `C = M×{1,2}` (fiber 3 spare).
* `rigidity` (= Thm 5.1) — every σ-additive two-valued state on `L` is Dirac
  **on the carrier** (`IsDiracOn`): the row/column pigeonhole.
* `coreBlock`/`corePattern` — the Specker-triple block and the pattern
  `s₀(A)=s₀(B)=s₀(C)=1`, encoded as the majority vote of the three marked points
  `(m₀,0),(m₀,1),(m₀,2)` (majority-of-3 is self-dual, so complement-additivity
  holds for ALL sets — no set-inequality case analysis).
* `kernel_empty` (clause (i)), `no_sigma_state_extends` (= Thm 7.1(2), the
  σ-side), and the reduction `witness_iff_coherent`: the pattern is a witness
  (amended encoding, `SigmaEssentialAmended`) **iff** it is finitely coherent.
  The coherence half (§3 invariant + §6 vote state) is the remaining work.

Everything is parameterized over `(M, <)` uncountable with countable initial
segments; instantiation at `ω₁` is a separate step.
-/
import QuerySystem.SigmaEssentialAmended
import Mathlib.Data.Set.Countable
import Mathlib.Order.Interval.Set.Basic

open Set Function MeasurableSpace

namespace SigmaEssential.Ulam

open SigmaEssential SigmaEssential.Amended

/-! ## §0. Dynkin-system helpers -/

/-- Binary disjoint unions stay in a Dynkin system (pad to an `ℕ`-family). -/
theorem DynkinSystem.has_union_disjoint {Ω : Type*} (d : DynkinSystem Ω)
    {X Y : Set Ω} (hX : d.Has X) (hY : d.Has Y) (hdisj : Disjoint X Y) :
    d.Has (X ∪ Y) := by
  classical
  set f : ℕ → Set Ω := fun n => if n = 0 then X else if n = 1 then Y else ∅ with hf
  have hdisjf : Pairwise (Disjoint on f) := by
    intro i j hij
    apply Set.disjoint_left.mpr
    intro x hxi hxj
    have hxi' : x ∈ X ∧ i = 0 ∨ x ∈ Y ∧ i = 1 := by
      simp only [hf] at hxi
      split_ifs at hxi with h0 h1
      · exact Or.inl ⟨hxi, h0⟩
      · exact Or.inr ⟨hxi, h1⟩
      · exact absurd hxi (Set.notMem_empty x)
    have hxj' : x ∈ X ∧ j = 0 ∨ x ∈ Y ∧ j = 1 := by
      simp only [hf] at hxj
      split_ifs at hxj with h0 h1
      · exact Or.inl ⟨hxj, h0⟩
      · exact Or.inr ⟨hxj, h1⟩
      · exact absurd hxj (Set.notMem_empty x)
    rcases hxi' with ⟨hxX, hi⟩ | ⟨hxY, hi⟩ <;>
      rcases hxj' with ⟨hxX', hj⟩ | ⟨hxY', hj⟩
    · exact hij (hi.trans hj.symm)
    · exact (Set.disjoint_left.mp hdisj) hxX hxY'
    · exact (Set.disjoint_left.mp hdisj) hxX' hxY
    · exact hij (hi.trans hj.symm)
  have hHas : ∀ i, d.Has (f i) := by
    intro i
    simp only [hf]
    split_ifs
    · exact hX
    · exact hY
    · exact d.has_empty
  have hU : (⋃ i, f i) = X ∪ Y := by
    apply Set.Subset.antisymm
    · refine Set.iUnion_subset fun i => ?_
      simp only [hf]
      split_ifs
      · exact Set.subset_union_left
      · exact Set.subset_union_right
      · exact Set.empty_subset _
    · rintro x (hx | hx)
      · exact Set.mem_iUnion.2 ⟨0, by simp [hf, hx]⟩
      · exact Set.mem_iUnion.2 ⟨1, by simp [hf, hx]⟩
  rw [← hU]
  exact d.has_iUnion_nat hdisjf hHas

/-- A countable-set decomposition into first-occurrence singletons: any countable
set is a countable pairwise-disjoint union of singletons and empties. -/
theorem countable_disjointified {Ω : Type*} {N : Set Ω} (hN : N.Countable)
    (hne : N.Nonempty) :
    ∃ g : ℕ → Set Ω, Pairwise (Disjoint on g) ∧ (⋃ n, g n) = N ∧
      ∀ n, g n = ∅ ∨ ∃ ω, g n = {ω} := by
  classical
  obtain ⟨f, rfl⟩ := hN.exists_eq_range hne
  refine ⟨fun n => if ∃ m < n, f m = f n then ∅ else {f n}, ?_, ?_, ?_⟩
  · -- pairwise disjoint: only first occurrences survive
    have key : ∀ {m n : ℕ}, m < n →
        Disjoint (if ∃ k < m, f k = f m then (∅ : Set Ω) else {f m})
          (if ∃ k < n, f k = f n then (∅ : Set Ω) else {f n}) := by
      intro m n hmn
      by_cases h2 : ∃ k < n, f k = f n
      · simp only [h2, if_true]
        exact disjoint_bot_right
      · by_cases h1 : ∃ k < m, f k = f m
        · simp only [h1, if_true]
          exact disjoint_bot_left
        · -- both first occurrences: f m ≠ f n since m < n and n is first
          simp only [h1, h2, if_false]
          rw [Set.disjoint_singleton]
          intro he
          exact h2 ⟨m, hmn, he⟩
    intro m n hmn
    rcases lt_or_gt_of_ne hmn with h | h
    · exact key h
    · exact (key h).symm
  · apply Set.Subset.antisymm
    · refine Set.iUnion_subset fun n => ?_
      split_ifs
      · exact Set.empty_subset _
      · rintro x rfl
        exact ⟨n, rfl⟩
    · rintro x ⟨n, rfl⟩
      have hex : ∃ m, f m = f n := ⟨n, rfl⟩
      set n₀ := Nat.find hex with hn₀
      have he₀ : f n₀ = f n := Nat.find_spec hex
      refine Set.mem_iUnion.2 ⟨n₀, ?_⟩
      have : ¬ ∃ m < n₀, f m = f n₀ := by
        rintro ⟨m, hm, he⟩
        exact Nat.find_min hex hm (he.trans he₀)
      simp only [this, if_false]
      exact (Set.mem_singleton_iff).2 he₀.symm
  · intro n
    dsimp only
    split_ifs
    · exact Or.inl rfl
    · exact Or.inr ⟨f n, rfl⟩

/-- In a Dynkin system generated by a family containing all singletons, every
countable set is a member (σ-class basics, Lem 2.3.2). -/
theorem has_of_countable {Ω : Type*} {G : Set (Set Ω)}
    (hsing : ∀ ω : Ω, {ω} ∈ G) {N : Set Ω} (hN : N.Countable) :
    (DynkinSystem.generate G).Has N := by
  rcases N.eq_empty_or_nonempty with rfl | hne
  · exact (DynkinSystem.generate G).has_empty
  obtain ⟨g, hdisj, hunion, hshape⟩ := countable_disjointified hN hne
  rw [← hunion]
  refine (DynkinSystem.generate G).has_iUnion_nat hdisj fun n => ?_
  rcases hshape n with h | ⟨ω, h⟩
  · rw [h]; exact (DynkinSystem.generate G).has_empty
  · rw [h]; exact DynkinSystem.GenerateHas.basic _ (hsing ω)

/-! ## §1. The Ulam matrix (Lem 2.1) -/

variable {M : Type*} [LinearOrder M]

/-- An **Ulam matrix** on `M`: rows are disjoint families covering everything
above the row index; columns are EXACTLY disjoint (the exactness is load-bearing
in the rigidity proof — the union of two same-column cells must lie in the
σ-class). -/
structure UlamMatrix (M : Type*) [LinearOrder M] where
  /-- the matrix entries -/
  C : M → ℕ → Set M
  /-- row disjointness -/
  row_disjoint : ∀ α : M, Pairwise (Disjoint on C α)
  /-- everything strictly above the row index is covered by the row -/
  row_cover : ∀ {α β : M}, α < β → ∃ n, β ∈ C α n
  /-- exact column disjointness -/
  col_disjoint : ∀ (n : ℕ) {α α' : M}, α ≠ α' → Disjoint (C α n) (C α' n)

/-- **Lemma 2.1 (Ulam).** If every initial segment of `M` is countable, an Ulam
matrix exists: fix injections `g_β : Iio β ↪ ℕ` and put
`C_{α,n} = {β > α : g_β(α) = n}`. -/
theorem ulamMatrix_exists (hseg : ∀ β : M, (Set.Iio β).Countable) :
    Nonempty (UlamMatrix M) := by
  classical
  have hg : ∀ β : M, ∃ g : (Set.Iio β) → ℕ, Function.Injective g := fun β =>
    Set.countable_iff_exists_injective.mp (hseg β)
  choose g hginj using hg
  refine ⟨⟨fun α n => {β | ∃ h : α < β, g β ⟨α, h⟩ = n}, ?_, ?_, ?_⟩⟩
  · -- row disjointness: g_β(α) has a single value
    intro α n m hnm
    apply Set.disjoint_left.mpr
    rintro β ⟨h₁, e₁⟩ ⟨h₂, e₂⟩
    exact hnm (e₁.symm.trans e₂)
  · -- row covering
    intro α β h
    exact ⟨g β ⟨α, h⟩, h, rfl⟩
  · -- exact column disjointness: injectivity of g_β
    intro n α α' hne
    apply Set.disjoint_left.mpr
    rintro β ⟨h₁, e₁⟩ ⟨h₂, e₂⟩
    have : (⟨α, h₁⟩ : Set.Iio β) = ⟨α', h₂⟩ := hginj β (e₁.trans e₂.symm)
    exact hne (congrArg Subtype.val this)

/-! ## §2. The carrier -/

/-- Core `A = M × {0,1}` (fibers named `0,1,2,3`; the paper's `1,2,3,4`). -/
def coreA (M : Type*) : Set (M × Fin 4) := Prod.snd ⁻¹' {0, 1}

/-- Core `B = M × {0,2}`. -/
def coreB (M : Type*) : Set (M × Fin 4) := Prod.snd ⁻¹' {0, 2}

/-- Core `C = M × {1,2}`. -/
def coreC (M : Type*) : Set (M × Fin 4) := Prod.snd ⁻¹' {1, 2}

variable (U : UlamMatrix M)

/-- Cell `D_{α,n} = C_{α,n} × F`. -/
def cell (α : M) (n : ℕ) : Set (M × Fin 4) := Prod.fst ⁻¹' U.C α n

/-- The generator family: all singletons, all cells, the three cores. -/
def generators : Set (Set (M × Fin 4)) :=
  {S | ∃ p, S = {p}} ∪ {S | ∃ α n, S = cell U α n} ∪ {coreA M, coreB M, coreC M}

/-- **The carrier `L`**: the σ-class generated by singletons, cells, cores. -/
def carrier : DynkinSystem (M × Fin 4) := DynkinSystem.generate (generators U)

theorem has_singleton (p : M × Fin 4) : (carrier U).Has {p} :=
  DynkinSystem.GenerateHas.basic _ (Or.inl (Or.inl ⟨p, rfl⟩))

theorem has_cell (α : M) (n : ℕ) : (carrier U).Has (cell U α n) :=
  DynkinSystem.GenerateHas.basic _ (Or.inl (Or.inr ⟨α, n, rfl⟩))

theorem has_coreA : (carrier U).Has (coreA M) :=
  DynkinSystem.GenerateHas.basic _ (Or.inr (Or.inl rfl))

theorem has_coreB : (carrier U).Has (coreB M) :=
  DynkinSystem.GenerateHas.basic _ (Or.inr (Or.inr (Or.inl rfl)))

theorem has_coreC : (carrier U).Has (coreC M) :=
  DynkinSystem.GenerateHas.basic _ (Or.inr (Or.inr (Or.inr rfl)))

theorem has_countable {N : Set (M × Fin 4)} (hN : N.Countable) :
    (carrier U).Has N :=
  has_of_countable (fun ω => Or.inl (Or.inl ⟨ω, rfl⟩)) hN

/-! ## §3. Rigidity (Thm 5.1) -/

/-- `s` is **Dirac on the carrier**: some point evaluation agrees with `s` on
every member of `d`. (Weaker than the spine's structure-equality `IsDirac`, and
the right notion: `Val` is unconstrained off the carrier.) -/
def IsDiracOn {Ω : Type*} (d : DynkinSystem Ω) (s : TwoValuedState d) : Prop :=
  ∃ ω : Ω, ∀ A : Set Ω, d.Has A → (s.Val A ↔ ω ∈ A)

variable {U}

/-- A state that kills singletons kills every countable set (σ-additivity over
the first-occurrence singleton decomposition). -/
theorem val_not_countable (s : TwoValuedState (carrier U))
    (hsing : ∀ p : M × Fin 4, ¬ s.Val {p}) {N : Set (M × Fin 4)}
    (hN : N.Countable) : ¬ s.Val N := by
  rcases N.eq_empty_or_nonempty with rfl | hne
  · exact s.not_val_empty
  obtain ⟨g, hdisj, hunion, hshape⟩ := countable_disjointified hN hne
  have hHas : ∀ n, (carrier U).Has (g n) := by
    intro n
    rcases hshape n with h | ⟨ω, h⟩
    · rw [h]; exact (carrier U).has_empty
    · rw [h]; exact has_singleton U ω
  rw [← hunion]
  rw [s.val_iUnion hdisj hHas]
  rintro ⟨n, hn⟩
  rcases hshape n with h | ⟨ω, h⟩
  · rw [h] at hn; exact s.not_val_empty hn
  · rw [h] at hn; exact hsing ω hn

/-- **Theorem 5.1 (rigidity).** On an uncountable `M` with countable initial
segments, every σ-additive two-valued state on the carrier is Dirac on it. -/
theorem rigidity (huncount : ¬ (Set.univ : Set M).Countable)
    (hseg : ∀ β : M, (Set.Iio β).Countable)
    (s : TwoValuedState (carrier U)) : IsDiracOn (carrier U) s := by
  classical
  -- Main split: does s put mass on a singleton?
  by_cases hsing : ∃ p : M × Fin 4, s.Val {p}
  · -- Dirac case
    obtain ⟨p, hp⟩ := hsing
    refine ⟨p, fun A hA => ?_⟩
    constructor
    · intro hval
      by_contra hnp
      have hsub : {p} ⊆ Aᶜ := by
        rintro x rfl
        exact hnp
      have : s.Val Aᶜ :=
        s.val_mono (has_singleton U p) ((carrier U).has_compl hA) hsub hp
      exact (s.val_compl hA).mp this hval
    · intro hp'
      exact s.val_mono (has_singleton U p) hA
        (by rintro x rfl; exact hp') hp
  · -- singleton-free case: run the Ulam pigeonhole to a contradiction
    exfalso
    push Not at hsing
    -- each row's union is co-countable, hence has value 1
    have hcells_disjoint : ∀ α : M, Pairwise (Disjoint on fun n => cell U α n) := by
      intro α n m hnm
      exact Disjoint.preimage _ (U.row_disjoint α hnm)
    have hrowHas : ∀ α : M, (carrier U).Has (⋃ n, cell U α n) := fun α =>
      (carrier U).has_iUnion_nat (hcells_disjoint α) (fun n => has_cell U α n)
    have hrow_compl_ctble : ∀ α : M, ((⋃ n, cell U α n)ᶜ).Countable := by
      intro α
      have hsub : (⋃ n, cell U α n)ᶜ ⊆ (Set.Iic α) ×ˢ (Set.univ : Set (Fin 4)) := by
        intro p hp
        simp only [mem_compl_iff, mem_iUnion, not_exists] at hp
        have : ¬ α < p.1 := by
          intro hlt
          obtain ⟨n, hn⟩ := U.row_cover hlt
          exact hp n hn
        exact ⟨not_lt.mp this, mem_univ _⟩
      have hIic : (Set.Iic α).Countable := by
        rw [← Set.Iio_insert]
        exact (hseg α).insert α
      exact (hIic.prod (Set.countable_univ)).mono hsub
    have hrowVal : ∀ α : M, s.Val (⋃ n, cell U α n) := by
      intro α
      have hcompl_false : ¬ s.Val ((⋃ n, cell U α n)ᶜ) :=
        val_not_countable s hsing (hrow_compl_ctble α)
      by_contra hval
      exact hcompl_false (((s.val_compl (hrowHas α)).mpr) hval)
    -- pick the true cell in each row
    have hpick : ∀ α : M, ∃ n, s.Val (cell U α n) := by
      intro α
      exact (s.val_iUnion (hcells_disjoint α) (fun n => has_cell U α n)).mp
        (hrowVal α)
    choose pick hpickVal using hpick
    -- pigeonhole: some column catches two rows
    have hcover : (Set.univ : Set M) = ⋃ n : ℕ, {α | pick α = n} := by
      apply Set.Subset.antisymm
      · intro α _
        exact Set.mem_iUnion.2 ⟨pick α, rfl⟩
      · exact fun α _ => mem_univ α
    have hfiber : ∃ n : ℕ, ¬ ({α | pick α = n}).Countable := by
      by_contra hall
      push Not at hall
      exact huncount (hcover ▸ Set.countable_iUnion hall)
    obtain ⟨n₀, hn₀⟩ := hfiber
    have : ∃ α β : M, α ≠ β ∧ pick α = n₀ ∧ pick β = n₀ := by
      by_contra hno
      push Not at hno
      apply hn₀
      apply Set.Subsingleton.countable
      intro α hα β hβ
      by_contra hne
      exact absurd hβ (by simpa [hα] using hno α β hne hα)
    obtain ⟨α, β, hne, hα, hβ⟩ := this
    -- two disjoint cells, both of value 1
    have hdisj : Disjoint (cell U α n₀) (cell U β n₀) :=
      Disjoint.preimage _ (U.col_disjoint n₀ hne)
    have h1 : s.Val (cell U α n₀) := hα ▸ hpickVal α
    have h2 : s.Val (cell U β n₀) := hβ ▸ hpickVal β
    exact s.val_at_most_one (has_cell U α n₀) (has_cell U β n₀) hdisj h1 h2

/-! ## §4. The block and the pattern -/

variable (U)

/-- The Specker-triple block: the ⊥-closure of the three cores. -/
noncomputable def coreBlock : Block (carrier U) := by
  classical
  exact
    { sets := {coreA M, coreB M, coreC M, (coreA M)ᶜ, (coreB M)ᶜ, (coreC M)ᶜ}
      mem_has := by
        intro A hA
        simp only [Finset.mem_insert, Finset.mem_singleton] at hA
        rcases hA with rfl | rfl | rfl | rfl | rfl | rfl
        · exact has_coreA U
        · exact has_coreB U
        · exact has_coreC U
        · exact (carrier U).has_compl (has_coreA U)
        · exact (carrier U).has_compl (has_coreB U)
        · exact (carrier U).has_compl (has_coreC U)
      compl_closed := by
        intro A hA
        simp only [Finset.mem_insert, Finset.mem_singleton] at hA ⊢
        rcases hA with rfl | rfl | rfl | rfl | rfl | rfl
        · tauto
        · tauto
        · tauto
        · rw [compl_compl]; tauto
        · rw [compl_compl]; tauto
        · rw [compl_compl]; tauto }

/-- The **pattern** `s₀`: majority vote of the three marked points
`(m₀,0), (m₀,1), (m₀,2)`. Majority-of-3 is self-dual, so complement-additivity
holds for every set, and on the block it assigns `1` to each core and `0` to
each core complement. -/
noncomputable def corePattern (m₀ : M) : LocalState (carrier U) (coreBlock U) where
  Val S :=
    ((m₀, (0 : Fin 4)) ∈ S ∧ (m₀, (1 : Fin 4)) ∈ S) ∨
    ((m₀, (0 : Fin 4)) ∈ S ∧ (m₀, (2 : Fin 4)) ∈ S) ∨
    ((m₀, (1 : Fin 4)) ∈ S ∧ (m₀, (2 : Fin 4)) ∈ S)
  decVal := Classical.decPred _
  val_compl := by
    intro A _
    by_cases h0 : (m₀, (0 : Fin 4)) ∈ A <;>
      by_cases h1 : (m₀, (1 : Fin 4)) ∈ A <;>
        by_cases h2 : (m₀, (2 : Fin 4)) ∈ A <;>
          simp [h0, h1, h2]

theorem corePattern_val_coreA (m₀ : M) : (corePattern U m₀).Val (coreA M) :=
  Or.inl ⟨by simp [coreA], by simp [coreA]⟩

theorem corePattern_val_coreB (m₀ : M) : (corePattern U m₀).Val (coreB M) :=
  Or.inr (Or.inl ⟨by simp [coreB], by simp [coreB]⟩)

theorem corePattern_val_coreC (m₀ : M) : (corePattern U m₀).Val (coreC M) :=
  Or.inr (Or.inr ⟨by simp [coreC], by simp [coreC]⟩)

omit [LinearOrder M] in
/-- The three cores intersect emptily: `A ∩ B ∩ C = ∅` (fiber check). -/
theorem cores_inter_empty : coreA M ∩ coreB M ∩ coreC M = (∅ : Set (M × Fin 4)) := by
  ext p
  simp only [coreA, coreB, coreC, mem_inter_iff, mem_preimage, mem_insert_iff,
    mem_singleton_iff, mem_empty_iff_false, iff_false]
  rintro ⟨⟨hA, hB⟩, hC⟩
  rcases hA with h | h <;> rcases hB with h' | h' <;> rcases hC with h'' | h'' <;>
    simp_all

/-- **Clause (i): the kernel is empty.** No point realizes the pattern. -/
theorem kernel_empty (m₀ : M) : kernelL (corePattern U m₀) = ∅ := by
  apply Set.eq_empty_iff_forall_notMem.mpr
  intro p hp
  rw [kernelL, mem_sInter] at hp
  have hmemA : p ∈ coreA M := by
    refine hp _ ⟨?_, corePattern_val_coreA U m₀⟩
    simp [coreBlock]
  have hmemB : p ∈ coreB M := by
    refine hp _ ⟨?_, corePattern_val_coreB U m₀⟩
    simp [coreBlock]
  have hmemC : p ∈ coreC M := by
    refine hp _ ⟨?_, corePattern_val_coreC U m₀⟩
    simp [coreBlock]
  have : p ∈ coreA M ∩ coreB M ∩ coreC M := ⟨⟨hmemA, hmemB⟩, hmemC⟩
  rw [cores_inter_empty] at this
  exact this

/-! ## §5. The σ-side main theorem and the reduction to coherence -/

variable {U}

/-- **The σ-side of Thm 7.1: no σ-additive two-valued state extends the
pattern.** Rigidity forces any extension to be Dirac on the carrier; the Dirac
point would lie in every pattern-true core, but `A ∩ B ∩ C = ∅`. -/
theorem no_sigma_state_extends (huncount : ¬ (Set.univ : Set M).Countable)
    (hseg : ∀ β : M, (Set.Iio β).Countable) (m₀ : M)
    (s : TwoValuedState (carrier U)) : ¬ ExtendsS s (corePattern U m₀) := by
  intro hext
  obtain ⟨p, hp⟩ := rigidity huncount hseg s
  have hmemA' : coreA M ∈ (coreBlock U).sets := by simp [coreBlock]
  have hmemB' : coreB M ∈ (coreBlock U).sets := by simp [coreBlock]
  have hmemC' : coreC M ∈ (coreBlock U).sets := by simp [coreBlock]
  have hA : p ∈ coreA M :=
    (hp _ (has_coreA U)).mp ((hext _ hmemA').mpr (corePattern_val_coreA U m₀))
  have hB : p ∈ coreB M :=
    (hp _ (has_coreB U)).mp ((hext _ hmemB').mpr (corePattern_val_coreB U m₀))
  have hC : p ∈ coreC M :=
    (hp _ (has_coreC U)).mp ((hext _ hmemC').mpr (corePattern_val_coreC U m₀))
  have : p ∈ coreA M ∩ coreB M ∩ coreC M := ⟨⟨hA, hB⟩, hC⟩
  rw [cores_inter_empty] at this
  exact this

/-- **The reduction: witness ⟺ coherence.** With the σ-side discharged
unconditionally, the pattern is a σ-essential contextual state (amended
encoding) iff it is finitely coherent — clause (0) is the sole remaining
obligation, exactly the paper's §3 + §6. -/
theorem witness_iff_coherent (huncount : ¬ (Set.univ : Set M).Countable)
    (hseg : ∀ β : M, (Set.Iio β).Countable) (m₀ : M) :
    IsSigmaEssentialL (corePattern U m₀) ↔ FinitelyCoherent (corePattern U m₀) := by
  constructor
  · exact fun h => h.1
  · intro h
    refine ⟨h, ?_⟩
    rintro ⟨s, hs⟩
    exact no_sigma_state_extends huncount hseg m₀ s hs

end SigmaEssential.Ulam
