"""Is it true that for a sequence generated by iterating a deterministic map
f (here M^L = f(M^{L-1})), the FIRST repeat M^t = M^s (t>s, s minimal such that
some later value repeats an earlier one) gives (s, p=t-s) as the MINIMAL
eventually-periodic threshold and period?

Standard rho/tortoise-hare fact: yes. If x_s = x_t with t minimal such repeat
and s minimal for that t, then the sequence is purely periodic from x_s onward
with period exactly t-s, and s is the smallest such threshold, p=t-s the
smallest period. This is standard (functional graph = rho-shape). Verify by
brute force on random finite functions."""
import random

def minimal_sp_bruteforce(seq_gen, cap=200):
    """seq_gen(i) returns the i-th term; detect true minimal (s,p) by
    definition: smallest s,p such that term(i+p)=term(i) for all i>=s."""
    seq = [seq_gen(i) for i in range(cap)]
    N = len(seq)
    for s in range(N):
        for p in range(1, N-s):
            if all(seq[i+p]==seq[i] for i in range(s, N-p)):
                return s, p
    return None

def minimal_sp_firstrepeat(seq_gen, cap=200):
    seen = {}
    seq = []
    for i in range(cap):
        v = seq_gen(i)
        seq.append(v)
        if v in seen:
            s, t = seen[v], i
            return s, t-s
        seen[v] = i
    return None

random.seed(0)
mismatches = 0
for trial in range(200):
    N = random.randint(2,8)
    f = [random.randrange(N) for _ in range(N)]
    x0 = random.randrange(N)
    def gen(i, f=f, x0=x0):
        x = x0
        for _ in range(i):
            x = f[x]
        return x
    a = minimal_sp_bruteforce(gen, cap=30)
    b = minimal_sp_firstrepeat(gen, cap=30)
    if a != b:
        mismatches += 1
        print("MISMATCH", f, x0, a, b)
print(f"{200-mismatches}/200 trials: first-repeat (s,p) == true-minimal (s,p) by definition-search")
